import { canonicalizeJson, freezeReportingStatementSnapshot, sha256CanonicalJson } from "../../src/reporting-statement-internal/reporting-statement-canonicalizer";

const asOf = new Date("2026-08-24T01:02:03.004Z");
function projection(overrides: Record<string, unknown> = {}) {
  return { profile: "PERSONAL_TEACHING_REPORTING_PROJECTION_V1", scope: { academicYearId: "year", targetUserId: "teacher", fromCivilDate: "2026-08-01", toCivilDate: "2026-08-31", asOfInstant: asOf }, responsibilityState: "RESPONSIBILITY_PRESENT", status: "PASS", counts: { distributedElapsedCount: 1, completedCount: 1, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, responsibilityManifest: [{ teachingAssignmentId: "ta-b", schoolClassId: "class-b", subjectId: "subject-b", validFrom: "2026-08-01", validUntil: null }, { teachingAssignmentId: "ta-a", schoolClassId: "class-a", subjectId: "subject-a", validFrom: "2026-08-01", validUntil: null }], sections: [], findings: [], evaluatedAt: "volatile", ...overrides };
}
describe("Reporting Statement canonicalization", () => {
  it("sorts keys, emits compact JSON, rejects undefined, and preserves null", () => { expect(canonicalizeJson({ z: null, a: { b: 1, a: 2 } })).toBe('{"a":{"a":2,"b":1},"z":null}'); expect(() => canonicalizeJson({ x: undefined } as never)).toThrow("Undefined"); expect(() => canonicalizeJson([undefined] as never)).toThrow("Undefined"); });
  it("freezes eligible Personal truth deterministically without mutating it", () => { const source = projection(); const frozen = freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId: "teacher", asOfInstant: asOf, projection: source as never }); expect(frozen.canonicalSnapshotJson).not.toContain("evaluatedAt"); expect(frozen.canonicalSnapshotJson).toContain("2026-08-24T01:02:03.004Z"); expect(frozen.frozenSubjectIds).toEqual(["subject-a", "subject-b"]); expect(source.responsibilityManifest[0].subjectId).toBe("subject-b"); expect(frozen.semanticHash).toBe(sha256CanonicalJson(frozen.canonicalSnapshotJson)); });
  it("rejects blocked and zero-subject projections", () => { expect(() => freezeReportingStatementSnapshot({ statementProfile: "P", submitterUserId: "u", asOfInstant: asOf, projection: projection({ status: "BLOCKED", counts: null }) as never })).toThrow("PASS"); expect(() => freezeReportingStatementSnapshot({ statementProfile: "P", submitterUserId: "u", asOfInstant: asOf, projection: projection({ responsibilityState: "ZERO_RESPONSIBILITY", responsibilityManifest: [] }) as never })).toThrow("zero-responsibility"); });
  it("uses exact UTF-8 SHA-256", () => { expect(sha256CanonicalJson('{"text":"Đam San"}')).toBe("b0c081ed4fd563d7a243a6c8f062b6ddf45faad5e2d56f1bcbd7055c46048e8d"); });
});