import { PrismaClient, ReportingStatementLifecycleState, UserStatus } from "@prisma/client";
import { freezeReportingStatementSnapshot, sha256CanonicalJson } from "../../src/reporting-statement-internal/reporting-statement-canonicalizer";
import { ReportingStatementRepository } from "../../src/reporting-statement-internal/reporting-statement.repository";
import { integration, testDatabaseUrl } from "../helpers/phase01-test-harness";
const asOf = new Date("2026-08-24T01:02:03.004Z");
function frozen(subjectId: string, submitterUserId: string) { return freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId, asOfInstant: asOf, projection: { profile: "PERSONAL_TEACHING_REPORTING_PROJECTION_V1", scope: { academicYearId: "year", targetUserId: submitterUserId, fromCivilDate: "2026-08-01", toCivilDate: "2026-08-31", asOfInstant: asOf }, responsibilityState: "RESPONSIBILITY_PRESENT", status: "PASS", counts: { distributedElapsedCount: 0, completedCount: 0, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, responsibilityManifest: [{ teachingAssignmentId: "a", schoolClassId: "c", subjectId, validFrom: "2026-08-01", validUntil: null }, { teachingAssignmentId: "b", schoolClassId: "c", subjectId, validFrom: "2026-08-02", validUntil: null }], sections: [], findings: [], evaluatedAt: "excluded" } as never }); }
integration("ReportingStatementRepository (isolated PostgreSQL)", () => {
  let prisma: PrismaClient; const repository = new ReportingStatementRepository(); let userId = ""; let yearId = ""; let subjectId = "";
  beforeAll(async () => { process.env.DATABASE_URL = testDatabaseUrl; prisma = new PrismaClient({ datasources: { db: { url: testDatabaseUrl } } }); const user = await prisma.user.create({ data: { username: `statement-${crypto.randomUUID()}`, passwordHash: "test", status: UserStatus.ACTIVE, mustChangePassword: false } }); userId = user.id; const year = await prisma.academicYear.create({ data: { code: `RS-${crypto.randomUUID().slice(0, 8)}`, name: "Statement year" } }); yearId = year.id; const subject = await prisma.subject.create({ data: { code: `RS-${crypto.randomUUID().slice(0, 8)}`, name: "Statement subject" } }); subjectId = subject.id; });
  afterAll(async () => { await prisma.reportingStatementHistory.deleteMany({ where: { actorUserId: userId } }); await prisma.reportingStatementCommand.deleteMany({ where: { actorUserId: userId } }); await prisma.reportingStatementRevisionSubject.deleteMany({ where: { subjectId } }); await prisma.reportingStatementRevisionState.deleteMany({ where: { series: { submitterUserId: userId } } }); await prisma.reportingStatementRevision.deleteMany({ where: { series: { submitterUserId: userId } } }); await prisma.reportingStatementSeries.deleteMany({ where: { submitterUserId: userId } }); await prisma.subject.delete({ where: { id: subjectId } }); await prisma.academicYear.delete({ where: { id: yearId } }); await prisma.user.delete({ where: { id: userId } }); await prisma.$disconnect(); });
  it("persists frozen text/subjects, classifies idempotency, and applies exact CAS", async () => { const bundle = frozen(subjectId, userId); const result = await prisma.$transaction((tx) => repository.persistSubmittedRevision(tx, { series: { statementProfile: "PERSONAL_V1", submitterUserId: userId, academicYearId: yearId, fromCivilDate: new Date("2026-08-01"), toCivilDate: new Date("2026-08-31") }, frozen: bundle, lifecycleToken: crypto.randomUUID(), command: { actorUserId: userId, requestKey: "submit-1", requestFingerprint: "fp-1" }, history: { actorUserId: userId } })); const stored = await repository.readFrozenRevision(prisma, result.revision.id); expect(stored?.canonicalSnapshotJson).toBe(bundle.canonicalSnapshotJson); expect(sha256CanonicalJson(stored!.canonicalSnapshotJson)).toBe(stored!.semanticHash); expect(stored?.subjects.map((x) => x.subjectId)).toEqual([subjectId]); expect((await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "submit-1", "fp-1")).kind).toBe("REPLAY"); expect((await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "submit-1", "changed")).kind).toBe("FINGERPRINT_CONFLICT"); expect((await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "other", "fp-1")).kind).toBe("MISS"); const before = await prisma.reportingStatementRevision.findUniqueOrThrow({ where: { id: result.revision.id } }); expect((await repository.transitionLifecycleCas(prisma, { revisionId: result.revision.id, seriesId: result.series.id, expectedLifecycleState: "SUBMITTED", expectedLifecycleToken: result.state.lifecycleToken, nextLifecycleState: "REJECTED", nextLifecycleToken: crypto.randomUUID() })).transitioned).toBe(true); expect((await repository.transitionLifecycleCas(prisma, { revisionId: result.revision.id, seriesId: result.series.id, expectedLifecycleState: "SUBMITTED", expectedLifecycleToken: result.state.lifecycleToken, nextLifecycleState: "REJECTED", nextLifecycleToken: crypto.randomUUID() })).transitioned).toBe(false); expect((await prisma.reportingStatementRevision.findUniqueOrThrow({ where: { id: result.revision.id } })).canonicalSnapshotJson).toBe(before.canonicalSnapshotJson); expect((await repository.readFrozenRevision(prisma, result.revision.id))?.state?.lifecycleState).toBe(ReportingStatementLifecycleState.REJECTED); });
  it("rejects zero subjects before creating any Statement artifact", async () => { const bundle = frozen(subjectId); bundle.frozenSubjectIds = []; bundle.snapshot.submitterUserId = userId; const before = await prisma.reportingStatementSeries.count({ where: { submitterUserId: userId } }); await expect(prisma.$transaction((tx) => repository.persistSubmittedRevision(tx, { series: { statementProfile: "PERSONAL_ZERO", submitterUserId: userId, academicYearId: yearId, fromCivilDate: new Date("2026-08-01"), toCivilDate: new Date("2026-08-31") }, frozen: bundle, lifecycleToken: crypto.randomUUID(), command: { actorUserId: userId, requestKey: "zero", requestFingerprint: "zero" }, history: { actorUserId: userId } }))).rejects.toThrow("one or more"); expect(await prisma.reportingStatementSeries.count({ where: { submitterUserId: userId } })).toBe(before); });
});
