import { assertFrozenReportingStatementIntegrity, canonicalizeJson, freezeReportingStatementSnapshot, sha256CanonicalJson } from "../../src/reporting-statement-internal/reporting-statement-canonicalizer";
const asOf = new Date("2026-08-24T01:02:03.004Z");
function projection(overrides: Record<string, unknown> = {}) { return { profile: "PERSONAL_TEACHING_REPORTING_PROJECTION_V1", scope: { academicYearId: "year", targetUserId: "teacher", fromCivilDate: "2026-08-01", toCivilDate: "2026-08-31", asOfInstant: asOf }, responsibilityState: "RESPONSIBILITY_PRESENT", status: "PASS", counts: { distributedElapsedCount: 1, completedCount: 1, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, responsibilityManifest: [{ teachingAssignmentId: "ta-b", schoolClassId: "class-b", subjectId: "subject-b", validFrom: "2026-08-01", validUntil: null }, { teachingAssignmentId: "ta-a", schoolClassId: "class-a", subjectId: "subject-a", validFrom: "2026-08-01", validUntil: null }], sections: [], findings: [], evaluatedAt: "volatile", ...overrides }; }
function freeze(overrides: Record<string, unknown> = {}, input: Record<string, unknown> = {}) { return freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId: "teacher", asOfInstant: asOf, projection: projection(overrides) as never, ...input } as never); }
describe("Reporting Statement canonicalization", () => {
  it("recursively sorts keys, emits compact JSON, retains null, and rejects invalid values", () => { expect(canonicalizeJson({ z: null, a: { b: 1, a: 2 } })).toBe('{"a":{"a":2,"b":1},"z":null}'); expect(() => canonicalizeJson({ x: { y: undefined } } as never)).toThrow("Undefined"); expect(() => canonicalizeJson([undefined] as never)).toThrow("Undefined"); expect(() => canonicalizeJson({ x: Infinity } as never)).toThrow("Non-finite"); });
  it("uses exact UTF-8 SHA-256 vectors without BOM", () => { expect(sha256CanonicalJson("{}")).toBe("44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"); expect(sha256CanonicalJson('{"text":"Đam San"}')).toBe("dd13b7a41b162d601ad461e39bbef0b358e3552a7601d1e452abc2e0abba23a4"); });
  it("freezes eligible Personal truth deterministically without mutating input", () => { const source = projection(); const first = freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId: "teacher", asOfInstant: asOf, projection: source as never }); const second = freeze(); expect(first.canonicalSnapshotJson).toBe(second.canonicalSnapshotJson); expect(first.semanticHash).toBe(second.semanticHash); expect(first.canonicalSnapshotJson).not.toContain("evaluatedAt"); expect(first.canonicalSnapshotJson).toContain("2026-08-24T01:02:03.004Z"); expect(first.frozenSubjectIds).toEqual(["subject-a", "subject-b"]); expect(source.responsibilityManifest[0].subjectId).toBe("subject-b"); });
  it("changes semantic text and hash for a different pinned asOf", () => { const later = new Date("2026-08-24T01:02:03.005Z"); const p = projection({ scope: { ...projection().scope, asOfInstant: later } }); const changed = freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId: "teacher", asOfInstant: later, projection: p as never }); expect(changed.semanticHash).not.toBe(freeze().semanticHash); });
  it("accepts only owner-consistent responsibility-present PASS with nonempty subjects", () => { expect(() => freeze({ status: "BLOCKED", counts: null })).toThrow("PASS"); expect(() => freeze({ responsibilityState: "ZERO_RESPONSIBILITY", responsibilityManifest: [] })).toThrow("zero-responsibility"); expect(() => freeze({ responsibilityManifest: [] })).toThrow("at least one"); expect(() => freeze({}, { submitterUserId: "other" })).toThrow("owner"); expect(() => freeze({ scope: { ...projection().scope, asOfInstant: new Date("2026-08-24T01:02:03.005Z") } })).toThrow("asOfInstant"); });
  it("rejects unsafe frozen-bundle tampering", () => { const good = freeze(); expect(() => assertFrozenReportingStatementIntegrity({ ...good, semanticHash: "0".repeat(64) } as never)).toThrow("hash integrity"); expect(() => assertFrozenReportingStatementIntegrity({ ...good, frozenSubjectIds: [] } as never)).toThrow("subject integrity"); });
  it("keeps generated and persistence metadata out of the explicit snapshot", () => { const result = freeze({ id: "generated", createdAt: "volatile" }); expect(result.canonicalSnapshotJson).not.toContain("generated"); expect(result.canonicalSnapshotJson).not.toContain("createdAt"); expect(result.snapshot.fromCivilDate).toBe("2026-08-01"); });
});
