import { PrismaClient, UserStatus } from "@prisma/client";
import { freezeReportingStatementSnapshot, sha256CanonicalJson } from "../../src/reporting-statement-internal/reporting-statement-canonicalizer";
import { ReportingStatementRepository } from "../../src/reporting-statement-internal/reporting-statement.repository";
import { integration, testDatabaseUrl } from "../helpers/phase01-test-harness";

const asOf = new Date("2026-08-24T01:02:03.004Z");
function createFrozen(subjectId: string, submitterUserId: string, academicYearId: string) {
  return freezeReportingStatementSnapshot({ statementProfile: "PERSONAL_V1", submitterUserId, asOfInstant: asOf, projection: { profile: "PERSONAL_TEACHING_REPORTING_PROJECTION_V1", scope: { academicYearId, targetUserId: submitterUserId, fromCivilDate: "2026-08-01", toCivilDate: "2026-08-31", asOfInstant: asOf }, responsibilityState: "RESPONSIBILITY_PRESENT", status: "PASS", counts: { distributedElapsedCount: 0, completedCount: 0, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, responsibilityManifest: [{ teachingAssignmentId: "a", schoolClassId: "c", subjectId, validFrom: "2026-08-01", validUntil: null }, { teachingAssignmentId: "b", schoolClassId: "c", subjectId, validFrom: "2026-08-02", validUntil: null }], sections: [], findings: [], evaluatedAt: "excluded" } as never });
}
integration("ReportingStatementRepository (isolated PostgreSQL)", () => {
  const repository = new ReportingStatementRepository(); let prisma: PrismaClient; let userId = ""; let yearId = ""; let subjectId = "";
  const counts = () => Promise.all([prisma.reportingStatementSeries.count(), prisma.reportingStatementRevision.count(), prisma.reportingStatementRevisionState.count(), prisma.reportingStatementRevisionSubject.count(), prisma.reportingStatementCommand.count(), prisma.reportingStatementHistory.count()]);
  beforeAll(async () => { process.env.DATABASE_URL = testDatabaseUrl; prisma = new PrismaClient({ datasources: { db: { url: testDatabaseUrl } } }); const user = await prisma.user.create({ data: { username: `statement-${crypto.randomUUID()}`, passwordHash: "test", status: UserStatus.ACTIVE, mustChangePassword: false } }); userId = user.id; yearId = (await prisma.academicYear.create({ data: { code: `RS-${crypto.randomUUID().slice(0, 8)}`, name: "Statement year" } })).id; subjectId = (await prisma.subject.create({ data: { code: `RS-${crypto.randomUUID().slice(0, 8)}`, name: "Statement subject" } })).id; });
  afterAll(async () => { const ids = (await prisma.reportingStatementSeries.findMany({ where: { submitterUserId: userId }, select: { id: true } })).map((x) => x.id); await prisma.reportingStatementHistory.deleteMany({ where: { seriesId: { in: ids } } }); await prisma.reportingStatementCommand.deleteMany({ where: { seriesId: { in: ids } } }); await prisma.reportingStatementRevisionSubject.deleteMany({ where: { subjectId } }); await prisma.reportingStatementRevisionState.deleteMany({ where: { seriesId: { in: ids } } }); await prisma.reportingStatementRevision.deleteMany({ where: { seriesId: { in: ids } } }); await prisma.reportingStatementSeries.deleteMany({ where: { id: { in: ids } } }); await prisma.subject.delete({ where: { id: subjectId } }); await prisma.academicYear.delete({ where: { id: yearId } }); await prisma.user.delete({ where: { id: userId } }); await prisma.$disconnect(); });
  it("persists the complete submitted topology and exact replay/CAS evidence", async () => { const frozen = createFrozen(subjectId, userId, yearId); const token = crypto.randomUUID(); const result = await prisma.$transaction((tx) => repository.persistSubmittedRevision(tx, { series: { statementProfile: "PERSONAL_V1", submitterUserId: userId, academicYearId: yearId, fromCivilDate: new Date("2026-08-01T00:00:00.000Z"), toCivilDate: new Date("2026-08-31T00:00:00.000Z") }, frozen, lifecycleToken: token, command: { actorUserId: userId, requestKey: "submit-1", requestFingerprint: "fp-1" }, history: { actorUserId: userId } })); const read = await repository.readFrozenRevision(prisma, result.revision.id); expect(read).toMatchObject({ seriesId: result.series.id, canonicalSnapshotJson: frozen.canonicalSnapshotJson, semanticHash: frozen.semanticHash, snapshotProfile: frozen.snapshot.snapshotProfile, serializerVersion: frozen.snapshot.serializerVersion, state: { revisionId: result.revision.id, seriesId: result.series.id, lifecycleState: "SUBMITTED", lifecycleToken: token } }); expect(read?.subjects.map((x) => x.subjectId)).toEqual([subjectId]); expect(sha256CanonicalJson(read!.canonicalSnapshotJson)).toBe(read!.semanticHash); const replay = await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "submit-1", "fp-1"); expect(replay).toMatchObject({ kind: "REPLAY", command: { seriesId: result.series.id, resultRevisionId: result.revision.id, resultLifecycleToken: token, requestFingerprint: "fp-1" } }); expect((await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "submit-1", "changed")).kind).toBe("FINGERPRINT_CONFLICT"); expect((await repository.classifyAcceptedCommand(prisma, userId, "SUBMIT", "other", "fp-1")).kind).toBe("MISS"); const next = crypto.randomUUID(); expect((await repository.transitionLifecycleCas(prisma, { revisionId: result.revision.id, seriesId: result.series.id, expectedLifecycleState: "SUBMITTED", expectedLifecycleToken: token, nextLifecycleState: "REJECTED", nextLifecycleToken: next })).transitioned).toBe(true); expect((await repository.transitionLifecycleCas(prisma, { revisionId: result.revision.id, seriesId: result.series.id, expectedLifecycleState: "SUBMITTED", expectedLifecycleToken: token, nextLifecycleState: "REJECTED", nextLifecycleToken: crypto.randomUUID() })).transitioned).toBe(false); expect((await repository.readFrozenRevision(prisma, result.revision.id))?.state).toMatchObject({ lifecycleState: "REJECTED", lifecycleToken: next }); });
  it.each(["statementProfile", "submitterUserId", "academicYearId", "fromCivilDate", "toCivilDate"] as const)("rejects %s mismatch before all Statement writes", async (field) => { const frozen = createFrozen(subjectId, userId, yearId); const series = { statementProfile: "PERSONAL_V1", submitterUserId: userId, academicYearId: yearId, fromCivilDate: new Date("2026-08-01T00:00:00.000Z"), toCivilDate: new Date("2026-08-31T00:00:00.000Z") }; if (field === "statementProfile") series.statementProfile = "OTHER"; if (field === "submitterUserId") series.submitterUserId = crypto.randomUUID(); if (field === "academicYearId") series.academicYearId = crypto.randomUUID(); if (field === "fromCivilDate") series.fromCivilDate = new Date("2026-08-02T00:00:00.000Z"); if (field === "toCivilDate") series.toCivilDate = new Date("2026-08-30T00:00:00.000Z"); const before = await counts(); await expect(prisma.$transaction((tx) => repository.persistSubmittedRevision(tx, { series, frozen, lifecycleToken: crypto.randomUUID(), command: { actorUserId: userId, requestKey: crypto.randomUUID(), requestFingerprint: "bad" }, history: { actorUserId: userId } }))).rejects.toThrow("series and frozen"); expect(await counts()).toEqual(before); });
});
