/**
 * @baogiang/contracts
 * Shared TypeScript types and interfaces for baogiang-damsan.
 *
 * These contracts define the API surface between frontend and backend.
 * Business domain models are NOT included in Phase 00.
 */

// ============================================================
// Health Check Contracts
// ============================================================

/** Status of a single health indicator */
export type HealthStatus = 'ok' | 'error' | 'shutting_down';

/** Response from GET /api/health/live */
export interface HealthLiveResponse {
  status: HealthStatus;
  timestamp: string;
  uptime: number;
  version: string;
  phase: string;
}

/** Detail of a single health check component */
export interface HealthCheckDetail {
  status: HealthStatus;
  message?: string;
  latencyMs?: number;
}

/** Response from GET /api/health/ready */
export interface HealthReadyResponse {
  status: HealthStatus;
  timestamp: string;
  checks: {
    database: HealthCheckDetail;
    [key: string]: HealthCheckDetail;
  };
}

// ============================================================
// API Error Contracts
// ============================================================

/** Standard API error response shape */
export interface ApiErrorResponse {
  statusCode: number;
  error: string;
  message: string | string[];
  requestId?: string;
  timestamp: string;
  path?: string;
}

// ============================================================
// Feature Flag Contracts
// ============================================================

/** Feature flags available in the system */
export interface FeatureFlags {
  /** AI assistant master switch - disabled until final AI phase */
  AI_ENABLED: boolean;
  /** AI active mode switch */
  AI_ACTIVE_MODE_ENABLED: boolean;
  /** AI passive mode switch */
  AI_PASSIVE_MODE_ENABLED: boolean;
  /** Web Push notifications */
  WEB_PUSH_ENABLED: boolean;
}

/** Default feature flags - all disabled in Phase 00 */
export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  AI_ENABLED: false,
  AI_ACTIVE_MODE_ENABLED: false,
  AI_PASSIVE_MODE_ENABLED: false,
  WEB_PUSH_ENABLED: false,
};

// ============================================================
// Capability / Permission Contracts
// ============================================================

/**
 * Scope of a capability grant.
 * Capabilities are always scoped; never global by default.
 */
export type CapabilityScope =
  | 'PERSONAL'        // affects only own data
  | 'SUBJECT_GROUP'   // affects a teaching group / department (tổ chuyên môn)
  | 'SUBJECT'         // affects a specific subject
  | 'ACTIVITY'        // affects an extracurricular activity (GDĐP, HĐTN-HN)
  | 'SCHOOL_WIDE';    // affects entire school

/**
 * Base capability identifiers.
 * All professional users start with TEACHER_BASE.
 * Additional capabilities are accumulated, never replaced.
 *
 * Note: This is a foundation type only.
 * Full capability definitions come in Phase 01+.
 */
export type CapabilityKey =
  | 'TEACHER_BASE'           // every professional user
  | 'SUBJECT_GROUP_LEAD'     // tổ trưởng capabilities
  | 'APPROVAL_PRINCIPAL'     // hiệu trưởng approval scope
  | 'APPROVAL_VICE_PRINCIPAL'// phó hiệu trưởng approval scope
  | 'GDDDP_COORDINATOR'      // GDĐP coordination
  | 'HĐTN_COORDINATOR'       // HĐTN-HN coordination
  | 'SYSTEM_ADMIN'           // system administration (NOT professional approval)
  | 'AI_ACTIVE_USE_SCHOOL'   // AI active use school-wide (BGH)
  | 'AI_ACTIVE_USE_DEPARTMENT' // AI active use department-wide (tổ trưởng)
  | 'AI_ACTIVE_USE_ACTIVITY' // AI active use activity-wide (điều phối)
  | 'AI_RECEIVE_SUGGESTION'  // Receive passive AI suggestions
  | 'AI_CONFIRM_SUGGESTION'  // Confirm AI suggestion to trigger business command
  | 'AI_EDIT_DRAFT'          // Edit draft generated by AI
  | 'AI_CONFIGURE_POLICY'    // Configure AI policy/task/quota/budget
  | 'AI_VIEW_USAGE'          // View AI usage
  | 'AI_VIEW_COST'           // View AI cost
  | 'AI_VIEW_AUDIT'          // View AI audit logs
  | 'AI_DISABLE_SYSTEM';     // System-wide AI kill switch capability

/**
 * A capability with its scope.
 * Capabilities and roles accumulate; they do not override each other.
 */
export interface ScopedCapability {
  key: CapabilityKey;
  scope: CapabilityScope;
  /** Optional additional constraint (e.g., specific subject group ID) */
  resourceId?: string;
}

/**
 * Authentication context passed through request pipeline.
 * Populated by auth middleware in Phase 01+.
 * In Phase 00, this is a type definition only.
 */
export interface AuthContext {
  userId: string;
  displayName: string;
  capabilities: ScopedCapability[];
  /** Whether the user is in read-only mode (e.g., token expired but still navigating) */
  isReadOnly: boolean;
}

// ============================================================
// Notification Contracts (foundation types for Phase 03+)
// ============================================================

/** Notification priority levels */
export type NotificationPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

/** Notification read/processing status */
export type NotificationStatus = 'UNREAD' | 'READ' | 'PROCESSED';

/** Base notification shape */
export interface BaseNotification {
  id: string;
  userId: string;
  title: string;
  body: string;
  priority: NotificationPriority;
  status: NotificationStatus;
  deepLink?: string;
  createdAt: string;
  readAt?: string;
}
