/**
 * @baogiang/contracts
 * Shared TypeScript types and interfaces for baogiang-damsan.
 *
 * These contracts define the API surface between frontend and backend.
 * Phase 01 adds public-safe identity, catalog, assignment, and audit contracts.
 */

// ============================================================
// Health Check Contracts
// ============================================================

/** Status of a single health indicator */
export type HealthStatus = 'ok' | 'error' | 'shutting_down';

/** Response from GET /api/health/live */
export interface HealthLiveResponse {
  status: HealthStatus;
  timestamp: string;
  uptime: number;
  version: string;
  phase: string;
}

/** Detail of a single health check component */
export interface HealthCheckDetail {
  status: HealthStatus;
  message?: string;
  latencyMs?: number;
}

/** Response from GET /api/health/ready */
export interface HealthReadyResponse {
  status: HealthStatus;
  timestamp: string;
  checks: {
    database: HealthCheckDetail;
    [key: string]: HealthCheckDetail;
  };
}

// ============================================================
// API Error Contracts
// ============================================================

/** Standard API error response shape */
export interface ApiErrorResponse {
  statusCode: number;
  error: string;
  message: string | string[];
  requestId?: string;
  timestamp: string;
  path?: string;
}

// ============================================================
// Feature Flag Contracts
// ============================================================

/** Feature flags available in the system */
export interface FeatureFlags {
  /** AI assistant master switch - disabled until final AI phase */
  AI_ENABLED: boolean;
  /** AI active mode switch */
  AI_ACTIVE_MODE_ENABLED: boolean;
  /** AI passive mode switch */
  AI_PASSIVE_MODE_ENABLED: boolean;
  /** Web Push notifications */
  WEB_PUSH_ENABLED: boolean;
}

/** Default feature flags - all disabled in Phase 00 */
export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  AI_ENABLED: false,
  AI_ACTIVE_MODE_ENABLED: false,
  AI_PASSIVE_MODE_ENABLED: false,
  WEB_PUSH_ENABLED: false,
};

// ============================================================
// Capability / Permission Contracts
// ============================================================

/**
 * Scope of a capability grant.
 * Capabilities are always scoped; never global by default.
 */
export type CapabilityScope =
  | 'PERSONAL'        // affects only own data
  | 'SUBJECT_GROUP'   // affects a teaching group / department (tổ chuyên môn)
  | 'SUBJECT'         // affects a specific subject
  | 'ACTIVITY'        // affects an extracurricular activity (GDĐP, HĐTN-HN)
  | 'SCHOOL_WIDE';    // affects entire school

/**
 * Base capability identifiers.
 * All professional users start with TEACHER_BASE.
 * Additional capabilities are accumulated, never replaced.
 *
 * Note: This is a foundation type only.
 * Full capability definitions come in Phase 01+.
 */
export type CapabilityKey =
  | 'TEACHER_BASE'           // every professional user
  | 'SUBJECT_GROUP_LEAD'     // tổ trưởng capabilities
  | 'APPROVAL_PRINCIPAL'     // hiệu trưởng approval scope
  | 'APPROVAL_VICE_PRINCIPAL'// phó hiệu trưởng approval scope
  | 'GDDDP_COORDINATOR'      // GDĐP coordination
  | 'HĐTN_COORDINATOR'       // HĐTN-HN coordination
  | 'SYSTEM_ADMIN'           // system administration (NOT professional approval)
  | 'USER_MANAGE'
  | 'SUBJECT_GROUP_MANAGE'
  | 'SUBJECT_MANAGE'
  | 'CAPABILITY_GRANT'
  | 'AUDIT_VIEW'
  | 'ADDITIONAL_DUTY_CATALOG_MANAGE'
  | 'ADDITIONAL_DUTY_ASSIGNMENT_MANAGE'
  | 'ACADEMIC_STRUCTURE_MANAGE'
  | 'TIMETABLE_MANAGE'
  | 'PPCT_MANAGE'
  | 'CALENDAR_EXCEPTION_MANAGE'
  | 'TEACHING_OPERATION_MANAGE'
  | 'SPECIAL_ACTIVITY_MANAGE'
  | 'TEACHING_EXECUTION_RECORD'
  | 'TEACHING_EXECUTION_MANAGE'
  | 'AI_ACTIVE_USE_SCHOOL'   // AI active use school-wide (BGH)
  | 'AI_ACTIVE_USE_DEPARTMENT' // AI active use department-wide (tổ trưởng)
  | 'AI_ACTIVE_USE_ACTIVITY' // AI active use activity-wide (điều phối)
  | 'AI_RECEIVE_SUGGESTION'  // Receive passive AI suggestions
  | 'AI_CONFIRM_SUGGESTION'  // Confirm AI suggestion to trigger business command
  | 'AI_EDIT_DRAFT'          // Edit draft generated by AI
  | 'AI_CONFIGURE_POLICY'    // Configure AI policy/task/quota/budget
  | 'AI_VIEW_USAGE'          // View AI usage
  | 'AI_VIEW_COST'           // View AI cost
  | 'AI_VIEW_AUDIT'          // View AI audit logs
  | 'AI_DISABLE_SYSTEM';     // System-wide AI kill switch capability

/**
 * A capability with its scope.
 * Capabilities and roles accumulate; they do not override each other.
 */
export interface ScopedCapability {
  key: CapabilityKey;
  scope: CapabilityScope;
  /** Optional additional constraint (e.g., specific subject group ID) */
  resourceId?: string;
}

/**
 * Authentication context passed through request pipeline.
 * Populated by auth middleware in Phase 01+.
 * In Phase 00, this is a type definition only.
 */
export interface AuthContext {
  userId: string;
  displayName: string;
  capabilities: ScopedCapability[];
  /** Whether the user is in read-only mode (e.g., token expired but still navigating) */
  isReadOnly: boolean;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface AuthUserResponse {
  id: string;
  username: string;
  displayName: string;
  status: 'ACTIVE';
  mustChangePassword: boolean;
}

export interface LoginResponse {
  user: AuthUserResponse;
  expiresAt: string;
}

export interface AuthMeResponse {
  user: AuthUserResponse;
  /** Effective, active capability grants at request time. */
  capabilities: ScopedCapability[];
}

export interface AuthMutationResponse {
  success: true;
}

// ============================================================
// Phase 01 Identity, Catalog, Assignment, and Audit Contracts
// ============================================================

export type UserStatus = 'PENDING' | 'ACTIVE' | 'LOCKED' | 'DISABLED';
export type CatalogStatus = 'ACTIVE' | 'INACTIVE';
export type AuditResult = 'SUCCESS' | 'DENIED' | 'FAILURE';

export interface ValidityWindow {
  validFrom: string;
  validUntil?: string;
}

export interface UserSummary {
  id: string;
  username: string;
  status: UserStatus;
  mustChangePassword: boolean;
  lockedUntil?: string;
  lastLoginAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface StaffProfileSummary {
  id: string;
  userId: string;
  staffCode?: string;
  displayName: string;
  email?: string;
  phone?: string;
  positionTitle?: string;
  isTeachingStaff: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface UserManagementRecord extends UserSummary {
  profile: StaffProfileSummary | null;
}

export interface UserManagementListResponse {
  items: UserManagementRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface CatalogEntry {
  id: string;
  code: string;
  name: string;
  status: CatalogStatus;
  createdAt: string;
  updatedAt: string;
}

export interface CatalogListResponse {
  items: CatalogEntry[];
  page: number;
  pageSize: number;
  total: number;
}

export interface SubjectGroupMembershipRecord extends ValidityWindow {
  id: string;
  userId: string;
  subjectGroupId: string;
  isPrimary: boolean;
}

export interface StaffSubjectRecord extends ValidityWindow {
  id: string;
  userId: string;
  subjectId: string;
  isPrimary: boolean;
}
export interface SubjectGroupMembershipListResponse { items: SubjectGroupMembershipRecord[]; page: number; pageSize: number; total: number; }
export interface StaffSubjectListResponse { items: StaffSubjectRecord[]; page: number; pageSize: number; total: number; }

export interface CapabilityDefinitionRecord {
  key: CapabilityKey;
  description: string;
  allowedScopeTypes: CapabilityScope[];
  isSystem: boolean;
  isActive: boolean;
}

export interface CapabilityGrantRecord extends ValidityWindow {
  id: string;
  userId: string;
  capabilityKey: CapabilityKey;
  scopeType: CapabilityScope;
  scopeResourceId?: string;
  grantedByUserId?: string;
  revokedAt?: string;
  revokedByUserId?: string;
  revokeReason?: string;
}
export interface CapabilityDefinitionListResponse { items: CapabilityDefinitionRecord[]; page: number; pageSize: number; total: number; }
export interface CapabilityGrantListResponse { items: CapabilityGrantRecord[]; page: number; pageSize: number; total: number; }

export interface AuditEventRecord {
  id: string;
  actorUserId?: string;
  action: string;
  entityType: string;
  entityId?: string;
  requestId?: string;
  result: AuditResult;
  metadata?: Record<string, unknown>;
  createdAt: string;
}
export interface AuditEventListResponse { items: AuditEventRecord[]; page: number; pageSize: number; total: number; }

// ============================================================
// Teaching execution evidence
// ============================================================
export type TeachingExecutionStatus = 'ACTIVE' | 'REVERSED';
export type CurricularTeachingExecutionKind = 'NORMAL' | 'MAKEUP';

export interface CurricularTeachingExecutionRecord {
  id: string; kind: CurricularTeachingExecutionKind; status: TeachingExecutionStatus;
  academicYearId: string; schoolClassId: string; subjectId: string;
  sourceNormalOccurrenceKey: string; sourceCivilDate: CivilDateString;
  originalTimetableVersionId: string; originalTimetableEntryId: string;
  sourceAcademicCalendarVersionId: string; sourceTimeSlotDefinitionId: string;
  ppctClassAssociationId: string; ppctPlanId: string; ppctVersionId: string; ppctItemId: string; ppctItemRevisionId: string;
  executionCivilDate: CivilDateString; executionAcademicCalendarVersionId: string; executionTimeSlotDefinitionId: string;
  executionAcademicWeekId: string; executionAcademicWeekSegmentId: string;
  responsibleTeacherUserId: string; actualTeacherUserId: string;
  operationalLessonDispositionId: string | null; makeupTeachingScheduleId: string | null;
  schoolClassCodeSnapshot: string; schoolClassNameSnapshot: string; subjectCodeSnapshot: string; subjectNameSnapshot: string;
  responsibleTeacherDisplayNameSnapshot: string; actualTeacherDisplayNameSnapshot: string;
  note: string | null; replacesId: string | null; reversedByUserId: string | null; reversedAt: string | null; reversalReason: string | null;
  createdByUserId: string; createdAt: string; updatedAt: string;
}
export interface SpecialActivityParticipationExecutionRecord {
  id: string; status: TeachingExecutionStatus; specialActivityId: string; specialActivityStaffingId: string; specialActivityTimeSlotId: string;
  academicYearId: string; executionCivilDate: CivilDateString; executionAcademicCalendarVersionId: string; executionTimeSlotDefinitionId: string;
  executionAcademicWeekId: string | null; executionAcademicWeekSegmentId: string | null; actualTeacherUserId: string;
  activityTitleSnapshot: string; actualTeacherDisplayNameSnapshot: string; replacesId: string | null; reversedByUserId: string | null; reversedAt: string | null; reversalReason: string | null;
  createdByUserId: string; createdAt: string; updatedAt: string;
}
export interface TeachingExecutionMutationResult<T> { outcome: 'CREATED' | 'IDEMPOTENT_REPLAY' | 'REVERSED'; item: T; }

export interface AdditionalDutyDefinitionRecord extends ValidityWindow {
  id: string;
  code: string;
  name: string;
  description?: string;
  category: string;
  isActive: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface StaffAdditionalDutyAssignmentRecord extends ValidityWindow {
  id: string;
  staffProfileId: string;
  dutyDefinitionId: string;
  scopeType: CapabilityScope;
  scopeResourceId?: string;
  note?: string;
  createdByUserId: string;
  createdAt: string;
  updatedAt: string;
}

export interface AdditionalDutyDefinitionListResponse {
  items: AdditionalDutyDefinitionRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface AdditionalDutyDefinitionOptionsResponse {
  items: AdditionalDutyDefinitionRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface StaffAdditionalDutyAssignmentListResponse {
  items: StaffAdditionalDutyAssignmentRecord[];
  page: number;
  pageSize: number;
  total: number;
}

// ============================================================
// Phase 02 Academic Structure Contracts
// ============================================================

export type AcademicWeekday = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
export type AcademicWeekKind = 'OFFICIAL' | 'RESERVE';
export type CivilDateString = `${number}-${number}-${number}`;

export interface AcademicYearRecord {
  id: string;
  code: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface AcademicYearListResponse {
  items: AcademicYearRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface AcademicSemesterRecord {
  id: string;
  code: string;
  name: string;
  ordinal: number;
  startDate: CivilDateString;
  endDate: CivilDateString;
  createdAt: string;
  updatedAt: string;
}

export interface AcademicWeekSegmentRecord {
  id: string;
  label: string;
  segmentOrder: number;
  startDate: CivilDateString;
  endDate: CivilDateString;
  createdAt: string;
  updatedAt: string;
}

export interface AcademicWeekRecord {
  id: string;
  kind: AcademicWeekKind;
  officialWeekNumber: number | null;
  reserveWeekNumber: number | null;
  displayLabel: string;
  sortOrder: number;
  segments: AcademicWeekSegmentRecord[];
  createdAt: string;
  updatedAt: string;
}

export interface CalendarInterruptionRecord {
  id: string;
  code: string;
  name: string;
  startDate: CivilDateString;
  endDate: CivilDateString;
  createdAt: string;
  updatedAt: string;
}

export interface AcademicCalendarVersionSummary {
  id: string;
  academicYearId: string;
  versionNumber: number;
  startDate: CivilDateString;
  endDate: CivilDateString;
  officialWeekCount: number;
  reserveWeekCount: number;
  teachingWeekdays: AcademicWeekday[];
  isActive: boolean;
  activatedAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface AcademicCalendarVersionDetail extends AcademicCalendarVersionSummary {
  semesters: AcademicSemesterRecord[];
  weeks: AcademicWeekRecord[];
  interruptions: CalendarInterruptionRecord[];
}

export interface AcademicCalendarVersionListResponse {
  items: AcademicCalendarVersionSummary[];
  page: number;
  pageSize: number;
  total: number;
}

export interface SchoolClassRecord {
  id: string;
  academicYearId: string;
  code: string;
  name: string;
  gradeLevel: 10 | 11 | 12;
  status: CatalogStatus;
  createdAt: string;
  updatedAt: string;
}

export interface SchoolClassListResponse {
  items: SchoolClassRecord[];
  page: number;
  pageSize: number;
  total: number;
}

// ============================================================
// Phase 03 Teaching Assignment Contracts
// ============================================================

export interface TeachingAssignmentClassSummary {
  id: string;
  code: string;
  name: string;
  gradeLevel: number;
  status: CatalogStatus;
}

export interface TeachingAssignmentSubjectSummary {
  id: string;
  code: string;
  name: string;
  status: CatalogStatus;
}

export interface TeachingAssignmentTeacherSummary {
  userId: string;
  username: string;
  displayName: string;
  staffCode: string | null;
  userStatus: UserStatus;
  isTeachingStaff: boolean | null;
}

export interface TeachingAssignmentRecord {
  id: string;
  academicYearId: string;
  schoolClassId: string;
  subjectId: string;
  teacherUserId: string;
  validFrom: CivilDateString;
  validUntil: CivilDateString | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
  schoolClass: TeachingAssignmentClassSummary;
  subject: TeachingAssignmentSubjectSummary;
  teacher: TeachingAssignmentTeacherSummary;
}

export interface TeachingAssignmentListResponse {
  items: TeachingAssignmentRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface TeachingAssignmentChangeResult {
  previous: TeachingAssignmentRecord;
  replacement: TeachingAssignmentRecord;
}

export interface TeachingAssignmentAcademicYearOption {
  id: string;
  code: string;
  name: string;
}

export interface TeachingAssignmentAcademicYearOptionListResponse {
  items: TeachingAssignmentAcademicYearOption[];
  page: number;
  pageSize: number;
  total: number;
}

export interface TeachingAssignmentActiveCalendarOption {
  id: string;
  versionNumber: number;
  startDate: CivilDateString;
  endDate: CivilDateString;
}

export interface TeachingAssignmentWorkspaceOptionsResponse {
  academicYear: TeachingAssignmentAcademicYearOption;
  activeCalendar: TeachingAssignmentActiveCalendarOption | null;
  classes: TeachingAssignmentClassSummary[];
  subjects: TeachingAssignmentSubjectSummary[];
  historicalTeachers: TeachingAssignmentTeacherSummary[];
}

export interface TeachingAssignmentEligibleTeacherListResponse {
  items: TeachingAssignmentTeacherSummary[];
  page: number;
  pageSize: number;
  total: number;
}

// ============================================================
// Phase 04 Timetable / Time-slot Contracts
// ============================================================

export type TimeSlotSession = 'MORNING' | 'AFTERNOON' | 'EVENING';
export type WallClockTimeString = `${number}:${number}:${number}`;

export interface TimeSlotDefinitionRecord {
  id: string;
  academicYearId: string;
  weekday: AcademicWeekday;
  session: TimeSlotSession;
  ordinal: number;
  revision: number;
  displayLabel: string;
  startTime: WallClockTimeString;
  endTime: WallClockTimeString;
  isActive: boolean;
  allowRegularTeaching: boolean;
  allowMakeupTeaching: boolean;
  allowSelfStudy: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TimeSlotDefinitionListResponse {
  items: TimeSlotDefinitionRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface TimeSlotRevisionResult {
  previous: TimeSlotDefinitionRecord;
  replacement: TimeSlotDefinitionRecord;
}

export type TimetableVersionStatus = 'DRAFT' | 'VALIDATED' | 'APPROVED' | 'ACTIVE' | 'SUPERSEDED';

export interface TimetableVersionRecord {
  id: string;
  academicYearId: string;
  versionNumber: number;
  status: TimetableVersionStatus;
  calendarVersionId: string | null;
  effectiveAcademicWeekId: string | null;
  effectiveFrom: CivilDateString | null;
  effectiveUntil: CivilDateString | null;
  contentChecksum: string | null;
  note: string | null;
  createdByUserId: string;
  validatedByUserId: string | null;
  validatedAt: string | null;
  approvedByUserId: string | null;
  approvedAt: string | null;
  activatedByUserId: string | null;
  activatedAt: string | null;
  supersededAt: string | null;
  createdAt: string;
  updatedAt: string;
  entryCount: number;
}

export interface TimetableVersionListResponse {
  items: TimetableVersionRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface TimetableEntryTeachingAssignmentSummary {
  id: string;
  validFrom: CivilDateString;
  validUntil: CivilDateString | null;
}

export interface TimetableEntryRecord {
  id: string;
  timetableVersionId: string;
  academicYearId: string;
  weekday: AcademicWeekday;
  timeSlotDefinitionId: string;
  schoolClassId: string;
  subjectId: string;
  teachingAssignmentId: string;
  teacherUserId: string;
  createdAt: string;
  timeSlot: TimeSlotDefinitionRecord;
  schoolClass: TeachingAssignmentClassSummary;
  subject: TeachingAssignmentSubjectSummary;
  teacher: TeachingAssignmentTeacherSummary;
  teachingAssignment: TimetableEntryTeachingAssignmentSummary;
}

export interface TimetableEntryListResponse {
  items: TimetableEntryRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface TimetableEntryReplaceResult {
  version: TimetableVersionRecord;
  previousCount: number;
  entryCount: number;
}

export type TimetableValidationIssueCode =
  | 'TARGET_REQUIRED'
  | 'TARGET_CALENDAR_NOT_ACTIVE'
  | 'TARGET_WEEK_NO_SEGMENTS'
  | 'TARGET_EFFECTIVE_FROM_MISMATCH'
  | 'EMPTY_TIMETABLE'
  | 'WEEKDAY_NOT_IN_CALENDAR'
  | 'SLOT_NOT_ACTIVE'
  | 'SLOT_NOT_REGULAR_TEACHING'
  | 'CLASS_NOT_ACTIVE'
  | 'SUBJECT_NOT_ACTIVE'
  | 'TEACHER_NOT_ACTIVE'
  | 'TEACHER_NOT_TEACHING_STAFF'
  | 'ASSIGNMENT_COVERAGE_GAP'
  | 'CLASS_TIME_OVERLAP'
  | 'TEACHER_TIME_OVERLAP';

export interface TimetableValidationIssue {
  code: TimetableValidationIssueCode;
  message: string;
  entryIds?: string[];
  weekday?: AcademicWeekday;
  schoolClassId?: string;
  teacherUserId?: string;
  timeSlotDefinitionIds?: string[];
}

export type TimetableDeferredCheck =
  | 'TIMETABLE_COMPLETENESS'
  | 'PPCT_ASSOCIATION'
  | 'SPECIAL_ACTIVITY_COLLISIONS';

export interface TimetableValidationReport {
  versionId: string;
  validationScope: 'NORMAL_BASE_TIMETABLE';
  statusBefore: TimetableVersionStatus;
  statusAfter: TimetableVersionStatus;
  valid: boolean;
  issues: TimetableValidationIssue[];
  deferredChecks: TimetableDeferredCheck[];
  validatedByUserId: string | null;
  validatedAt: string | null;
  version: TimetableVersionRecord;
}

export interface TimetableActivationResult {
  versionId: string;
  activationScope: 'NORMAL_BASE_TIMETABLE';
  statusBefore: 'APPROVED';
  statusAfter: 'APPROVED' | 'ACTIVE';
  activated: boolean;
  issues: TimetableValidationIssue[];
  deferredChecks: TimetableDeferredCheck[];
  supersededVersion: TimetableVersionRecord | null;
  version: TimetableVersionRecord;
}

export interface TimetableEffectiveResolution {
  academicYearId: string;
  date: CivilDateString;
  version: TimetableVersionRecord | null;
}

// ============================================================
// LOCAL-FC-05B1 Deterministic Timetable Readiness Read Model
// ============================================================

export type TimetableReadinessProfile = 'NORMAL_BASE_PPCT_V1';

export type TimetableReadinessRootState = 'PASS' | 'FAIL';

export type TimetableReadinessDimensionState = 'PASS' | 'FAIL' | 'NOT_ASSESSED';

export type TimetableReadinessFindingSeverity = 'BLOCKER' | 'WARNING' | 'INFO';

export type TimetableReadinessDimensionKey =
  | 'NORMAL_BASE_TIMETABLE_FOUNDATION'
  | 'PPCT_ASSOCIATION_BINDING'
  | 'PPCT_CAPACITY'
  | 'OPERATIONAL_OVERLAYS'
  | 'SUBSTITUTION_CANCELLATION_MAKEUP'
  | 'LOCAL_OPERATIONAL_EXCEPTIONS'
  | 'SPECIAL_ACTIVITY_COLLISIONS'
  | 'RESOLVED_OCCURRENCE_EXECUTION'
  | 'PROGRESS_DEBT_REPORTING';

export interface TimetableReadinessDimensionResult {
  key: TimetableReadinessDimensionKey;
  state: TimetableReadinessDimensionState;
  required: boolean;
}

export interface TimetableReadinessStream {
  academicYearId: string;
  schoolClassId: string;
  subjectId: string;
}

export interface TimetableReadinessScope {
  timetableVersionId: string;
  academicYearId: string;
  from: CivilDateString;
  to: CivilDateString;
  affectedStreams: Array<Omit<TimetableReadinessStream, 'academicYearId'>>;
}

export interface TimetableReadinessFinding {
  code: string;
  dimension: TimetableReadinessDimensionKey;
  severity: TimetableReadinessFindingSeverity;
  message: string;
  stream?: TimetableReadinessStream;
  date?: CivilDateString;
  timetableEntryIds?: string[];
  ppctClassAssociationId?: string;
  ppctVersionId?: string;
}

export interface TimetableReadinessProvenance {
  timetableVersionId: string;
  academicCalendarVersionId: string | null;
  ppctClassAssociationIds: string[];
  ppctVersionIds: string[];
}

export interface TimetableReadinessResponse {
  profile: TimetableReadinessProfile;
  productLabel: 'TIMETABLE READINESS — NORMAL BASE + PPCT BINDING';
  scope: TimetableReadinessScope;
  result: TimetableReadinessRootState;
  dimensions: TimetableReadinessDimensionResult[];
  findings: TimetableReadinessFinding[];
  provenance: TimetableReadinessProvenance;
  evaluatedAt: string;
}

// ============================================================
// LOCAL-FC-05A2 PPCT Control Plane Contracts
// ============================================================

export type PpctVersionStatus = 'DRAFT' | 'PUBLISHED' | 'SUPERSEDED';

export interface PpctPlanRecord {
  id: string;
  academicYearId: string;
  subjectId: string;
  gradeLevel: 10 | 11 | 12;
  createdAt: string;
  updatedAt: string;
}

export interface PpctVersionRecord {
  id: string;
  ppctPlanId: string;
  versionNumber: number;
  status: PpctVersionStatus;
  createdByUserId: string;
  publishedByUserId: string | null;
  publishedAt: string | null;
  supersededByUserId: string | null;
  supersededAt: string | null;
  createdAt: string;
  updatedAt: string;
  itemCount: number;
}

export interface PpctItemRevisionRecord {
  id: string;
  ppctVersionId: string;
  ppctPlanId: string;
  itemId: string;
  sequence: number;
  title: string;
  lessonType: string;
  createdAt: string;
}

export interface PpctLineageEdgeRecord {
  id: string;
  ppctPlanId: string;
  predecessorVersionId: string;
  predecessorItemId: string;
  successorVersionId: string;
  successorItemId: string;
  createdAt: string;
}

export interface PpctVersionContent {
  version: PpctVersionRecord;
  items: PpctItemRevisionRecord[];
  lineage: PpctLineageEdgeRecord[];
}

export interface PpctClassAssociationRecord {
  id: string;
  academicYearId: string;
  schoolClassId: string;
  subjectId: string;
  gradeLevel: 10 | 11 | 12;
  ppctPlanId: string;
  ppctVersionId: string;
  ppctVersionStatus: PpctVersionStatus;
  effectiveFrom: CivilDateString;
  effectiveUntil: CivilDateString | null;
  createdByUserId: string;
  createdAt: string;
  updatedAt: string;
}

export interface PpctPlanListResponse {
  items: PpctPlanRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface PpctVersionListResponse {
  items: PpctVersionRecord[];
  page: number;
  pageSize: number;
  total: number;
}

export interface PpctAssociationHistoryResponse {
  items: PpctClassAssociationRecord[];
}

export interface PpctAssociationSwitchResult {
  previousAssociation: PpctClassAssociationRecord | null;
  association: PpctClassAssociationRecord;
}

export type PpctResolution =
  | {
      resolved: false;
      academicYearId: string;
      schoolClassId: string;
      subjectId: string;
      date: CivilDateString;
    }
  | {
      resolved: true;
      academicYearId: string;
      schoolClassId: string;
      subjectId: string;
      date: CivilDateString;
      association: PpctClassAssociationRecord;
      plan: PpctPlanRecord;
      version: PpctVersionRecord;
      items: PpctItemRevisionRecord[];
      lineage: PpctLineageEdgeRecord[];
    };

// ============================================================
// Phase 04B3 Timetable Import Configuration Contracts
// ============================================================

export type TimetableImportTeacherIdentifierMode =
  | 'GENERIC_EXACT'
  | 'STAFF_CODE'
  | 'USERNAME'
  | 'APPROVED_ALIAS';

export type TimetableImportSemanticField =
  | 'WEEKDAY'
  | 'SESSION'
  | 'PERIOD_ORDINAL'
  | 'SCHOOL_CLASS'
  | 'SUBJECT'
  | 'TEACHER';

export type TimetableImportAliasEntityType = 'TEACHER' | 'SCHOOL_CLASS' | 'SUBJECT';

export interface TimetableImportColumnMappingRecord {
  semanticField: TimetableImportSemanticField;
  sourceHeader: string;
}

export interface TimetableImportProfileRevisionRecord {
  id: string;
  profileId: string;
  revision: number;
  isActive: boolean;
  sheetNameHint: string | null;
  headerRowHint: number | null;
  teacherIdentifierMode: TimetableImportTeacherIdentifierMode;
  createdByUserId: string;
  retiredByUserId: string | null;
  retiredAt: string | null;
  createdAt: string;
  columnMappings: TimetableImportColumnMappingRecord[];
}

export interface TimetableImportProfileRecord {
  id: string;
  sourceKey: string;
  name: string;
  createdByUserId: string;
  createdAt: string;
  updatedAt: string;
  activeRevision: TimetableImportProfileRevisionRecord | null;
}

export interface TimetableImportProfileDetail extends TimetableImportProfileRecord {
  revisions: TimetableImportProfileRevisionRecord[];
}

export interface TimetableImportProfileListResponse {
  items: TimetableImportProfileRecord[];
}

export interface TimetableImportAliasRecord {
  id: string;
  profileId: string;
  entityType: TimetableImportAliasEntityType;
  academicYearId: string | null;
  sourceValue: string;
  teacherUserId: string | null;
  schoolClassId: string | null;
  subjectId: string | null;
  isActive: boolean;
  createdByUserId: string;
  retiredByUserId: string | null;
  retiredAt: string | null;
  createdAt: string;
}

export interface TimetableImportAliasListResponse {
  items: TimetableImportAliasRecord[];
}

export type TimetableImportWorksheetState = 'VISIBLE' | 'HIDDEN' | 'VERY_HIDDEN';
export type TimetableImportIssueSeverity = 'ERROR' | 'WARNING';
export type TimetableImportIssueCategory = 'WORKBOOK' | 'SHEET' | 'HEADER' | 'ROW' | 'RESOLUTION' | 'VALIDATION';
export type TimetableImportPreviewIssueCode =
  | 'HIDDEN_MAPPED_DATA' | 'NONBLANK_ROW_WITHOUT_MAPPED_DATA' | 'PARTIALLY_BLANK_MAPPED_ROW'
  | 'FORMULA_IN_MAPPED_CELL' | 'HYPERLINK_IN_MAPPED_CELL' | 'MERGED_MAPPED_CELL'
  | 'UNSUPPORTED_MAPPED_CELL_TYPE' | 'MAPPED_VALUE_TOO_LONG'
  | 'INVALID_WEEKDAY' | 'INVALID_SESSION' | 'INVALID_PERIOD_ORDINAL' | 'WEEKDAY_NOT_IN_CALENDAR'
  | 'SLOT_NOT_FOUND' | 'SLOT_NOT_ACTIVE' | 'SLOT_NOT_REGULAR_TEACHING'
  | 'CLASS_NOT_FOUND' | 'CLASS_INACTIVE' | 'CLASS_IDENTITY_CONFLICT'
  | 'SUBJECT_NOT_FOUND' | 'SUBJECT_INACTIVE' | 'SUBJECT_IDENTITY_CONFLICT'
  | 'TEACHER_NOT_FOUND' | 'TEACHER_AMBIGUOUS' | 'TEACHER_INACTIVE' | 'TEACHER_NOT_TEACHING_STAFF'
  | 'ASSIGNMENT_NOT_FOUND' | 'ASSIGNMENT_AMBIGUOUS' | 'ASSIGNMENT_COVERAGE_GAP'
  | 'DUPLICATE_CANONICAL_ROW' | 'CLASS_TIME_OVERLAP' | 'TEACHER_TIME_OVERLAP' | 'EMPTY_TIMETABLE';

export interface TimetableImportPreviewIssue {
  code: TimetableImportPreviewIssueCode;
  severity: TimetableImportIssueSeverity;
  category: TimetableImportIssueCategory;
  message: string;
  sourceRowNumber?: number;
  relatedSourceRowNumbers?: number[];
  semanticField?: TimetableImportSemanticField;
  boundedSourceValue?: string;
}

export interface TimetableImportHeaderCandidate {
  rowNumber: number;
  matchedSemanticFields: TimetableImportSemanticField[];
  complete: boolean;
}

export interface TimetableImportWorksheetInspection {
  name: string;
  state: TimetableImportWorksheetState;
  nonBlank: boolean;
  selectable: boolean;
  rowCount: number;
  columnCount: number;
  matchesProfileSheetHint: boolean;
  headerCandidates: TimetableImportHeaderCandidate[];
}

export interface TimetableImportWorkbookInspectionResponse {
  profileRevisionId: string;
  profileId: string;
  sourceFileName: string;
  sheets: TimetableImportWorksheetInspection[];
  issues: TimetableImportPreviewIssue[];
}

export interface TimetableImportCanonicalPreviewRow {
  sourceRowNumber: number;
  weekday: AcademicWeekday;
  timeSlotDefinitionId: string;
  schoolClassId: string;
  schoolClassCode: string;
  subjectId: string;
  subjectCode: string;
  teachingAssignmentId: string;
  teacherUserId: string;
  teacherDisplayName: string;
  teacherStaffCode: string | null;
  normalizedSourceValues: Record<TimetableImportSemanticField, string>;
}

export interface TimetableImportPreviewDiffRow {
  weekday: AcademicWeekday;
  timeSlotDefinitionId: string;
  schoolClassId: string;
  sourceRowNumber?: number;
  subjectId: string;
  teachingAssignmentId: string;
  teacherUserId: string;
}

export interface TimetableImportPreviewChangedRow {
  before: TimetableImportPreviewDiffRow;
  after: TimetableImportPreviewDiffRow;
  changedFields: Array<'SUBJECT' | 'TEACHING_ASSIGNMENT' | 'TEACHER'>;
}

export interface TimetableImportPreviewDiff {
  added: TimetableImportPreviewDiffRow[];
  changed: TimetableImportPreviewChangedRow[];
  removed: TimetableImportPreviewDiffRow[];
  unchangedCount: number;
  counts: { added: number; changed: number; removed: number; unchanged: number };
}

export interface TimetableImportWorkbookPreviewResponse {
  profileId: string;
  profileRevisionId: string;
  source: { sourceFileName: string; sheetName: string; headerRowNumber: number; sourceRowCount: number };
  target: { academicYearId: string; calendarVersionId: string; effectiveAcademicWeekId: string; effectiveFrom: CivilDateString; calendarEndDate: CivilDateString };
  rows: TimetableImportCanonicalPreviewRow[];
  issues: TimetableImportPreviewIssue[];
  blockingIssueCount: number;
  warningCount: number;
  canConfirm: boolean;
  baseline: { date: CivilDateString; timetableVersion: null | { id: string; versionNumber: number; status: TimetableVersionStatus; effectiveFrom: CivilDateString | null; effectiveUntil: CivilDateString | null } };
  diff: TimetableImportPreviewDiff | null;
}

export type TimetableImportConfirmationOutcome = 'CREATED' | 'IDEMPOTENT_REPLAY';

export interface TimetableImportReceiptRecord {
  id: string;
  timetableVersionId: string;
  profileRevisionId: string;
  checksumAlgorithm: 'SHA-256';
  serializationVersion: 'semantic-v1';
  requestIdempotencyKey: string | null;
  requestFingerprint: string | null;
  sourceFileName: string;
  sheetName: string;
  headerRowNumber: number;
  sourceRowCount: number;
  normalizedEntryCount: number;
  createdByUserId: string;
  committedAt: string;
}

export interface TimetableImportWorkbookConfirmResponse {
  outcome: TimetableImportConfirmationOutcome;
  receipt: TimetableImportReceiptRecord;
  version: TimetableVersionRecord;
}

// ============================================================
// Operational Overlay Contracts (LOCAL-FC-05C2A)
// ============================================================

export type OperationalOverlayStatus = 'ACTIVE' | 'REVERSED';
export type CalendarExceptionScope = 'SCHOOL_WIDE' | 'GRADE' | 'CLASS';
export type CalendarExceptionTimeSelector = 'WHOLE_DAY' | 'SESSION' | 'EXACT_SLOTS';
export type OperationalLessonDispositionType =
  | 'AUTHORIZED_CANCELLATION'
  | 'ABSENCE_NO_REPLACEMENT'
  | 'SAME_SUBJECT_SUBSTITUTION'
  | 'DIFFERENT_SUBJECT_SUPERVISION';
export type OperationalOverlayMutationOutcome = 'CREATED' | 'REVERSED' | 'IDEMPOTENT_REPLAY';

export interface OperationalOverlayCollisionCoverage {
  profile: 'CANONICAL_CLASS_TEACHER_TIME_V1';
  specialActivity: 'ASSESSED';
  room: 'NOT_ASSESSED';
}

// ============================================================
// Special Activity Contracts (LOCAL-FC-05D2)
// ============================================================
export type SpecialActivityStatus = 'ACTIVE' | 'REVERSED';
export type SpecialActivityScope = 'SCHOOL_WIDE' | 'GRADE' | 'CLASS';
export interface SpecialActivityStaffingRecord { scheduledTeacherUserId: string; staffProfileId: string; eligibilityCheckedAt: string; eligibilityWasActive: boolean; eligibilityWasTeachingStaff: boolean; }
export interface SpecialActivityRecord {
  id: string; academicYearId: string; academicCalendarVersionId: string; civilDate: CivilDateString;
  scope: SpecialActivityScope; gradeLevel: 10 | 11 | 12 | null; schoolClassId: string | null;
  title: string; note: string | null; status: SpecialActivityStatus; replacesId: string | null;
  createdByUserId: string; reversedByUserId: string | null; reversedAt: string | null; reversalReason: string | null;
  createdAt: string; updatedAt: string; exactTimeSlotDefinitionIds: string[]; frozenSchoolClassIds: string[]; staffing: SpecialActivityStaffingRecord[];
}
export interface SpecialActivityCollisionCoverage { profile: 'CANONICAL_CLASS_TEACHER_TIME_V1'; specialActivity: 'ASSESSED'; room: 'NOT_ASSESSED'; }
export interface SpecialActivityCreateResult { outcome: 'CREATED' | 'IDEMPOTENT_REPLAY'; record: SpecialActivityRecord; collisionCoverage: SpecialActivityCollisionCoverage; }
export interface SpecialActivityReverseResult { outcome: 'REVERSED' | 'IDEMPOTENT_REPLAY'; record: SpecialActivityRecord; collisionCoverage: SpecialActivityCollisionCoverage; }
export interface SpecialActivityListResponse { items: SpecialActivityRecord[]; page: number; pageSize: number; total: number; collisionCoverage: SpecialActivityCollisionCoverage; }

export interface CalendarExceptionRecord {
  id: string;
  academicYearId: string;
  academicCalendarVersionId: string;
  civilDate: CivilDateString;
  scope: CalendarExceptionScope;
  gradeLevel: 10 | 11 | 12 | null;
  schoolClassId: string | null;
  timeSelector: CalendarExceptionTimeSelector;
  session: TimeSlotSession | null;
  exactTimeSlotDefinitionIds: string[];
  note: string | null;
  status: OperationalOverlayStatus;
  replacesId: string | null;
  createdByUserId: string;
  reversedByUserId: string | null;
  reversedAt: string | null;
  reversalReason: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface OperationalLessonDispositionRecord {
  id: string;
  academicYearId: string;
  timetableVersionId: string;
  timetableEntryId: string;
  sourceCivilDate: CivilDateString;
  academicCalendarVersionId: string;
  timeSlotDefinitionId: string;
  schoolClassId: string;
  subjectId: string;
  teachingAssignmentId: string;
  responsibleTeacherUserId: string;
  dispositionType: OperationalLessonDispositionType;
  assignedTeacherUserId: string | null;
  eligibilityCheckedAt: string | null;
  eligibilityWasActive: boolean | null;
  eligibilityWasTeachingStaff: boolean | null;
  eligibilitySameSubject: boolean | null;
  eligibilityStaffSubjectId: string | null;
  note: string | null;
  status: OperationalOverlayStatus;
  replacesId: string | null;
  createdByUserId: string;
  reversedByUserId: string | null;
  reversedAt: string | null;
  reversalReason: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CalendarExceptionCreateResult { outcome: 'CREATED' | 'IDEMPOTENT_REPLAY'; record: CalendarExceptionRecord; collisionCoverage: OperationalOverlayCollisionCoverage; }
export interface CalendarExceptionReverseResult { outcome: 'REVERSED' | 'IDEMPOTENT_REPLAY'; record: CalendarExceptionRecord; collisionCoverage: OperationalOverlayCollisionCoverage; }
export interface OperationalLessonDispositionCreateResult { outcome: 'CREATED' | 'IDEMPOTENT_REPLAY'; record: OperationalLessonDispositionRecord; collisionCoverage: OperationalOverlayCollisionCoverage; }
export interface OperationalLessonDispositionReverseResult { outcome: 'REVERSED' | 'IDEMPOTENT_REPLAY'; record: OperationalLessonDispositionRecord; collisionCoverage: OperationalOverlayCollisionCoverage; }
export interface CalendarExceptionListResponse { items: CalendarExceptionRecord[]; page: number; pageSize: number; total: number; collisionCoverage: OperationalOverlayCollisionCoverage; }
export interface OperationalLessonDispositionListResponse { items: OperationalLessonDispositionRecord[]; page: number; pageSize: number; total: number; collisionCoverage: OperationalOverlayCollisionCoverage; }

// ============================================================
// Notification Contracts (foundation types for Phase 03+)
// ============================================================

/** Notification priority levels */
export type NotificationPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

/** Notification read/processing status */
export type NotificationStatus = 'UNREAD' | 'READ' | 'PROCESSED';

/** Base notification shape */
export interface BaseNotification {
  id: string;
  userId: string;
  title: string;
  body: string;
  priority: NotificationPriority;
  status: NotificationStatus;
  deepLink?: string;
  createdAt: string;
  readAt?: string;
}
