import { Injectable } from "@nestjs/common";
import { Prisma, ReportingStatementCommandType, ReportingStatementHistoryEvent, ReportingStatementLifecycleState } from "@prisma/client";
import { FrozenReportingStatementSnapshot } from "./reporting-statement-canonicalizer";
export type ReportingStatementTx = Prisma.TransactionClient;
export interface SeriesLogicalKey { statementProfile: string; submitterUserId: string; academicYearId: string; fromCivilDate: Date; toCivilDate: Date; }
export interface AcceptedCommandReplay { id: string; seriesId: string; targetRevisionId: string | null; resultRevisionId: string; resultLifecycleState: ReportingStatementLifecycleState; resultLifecycleToken: string; submissionAsOfInstant: Date | null; requestFingerprint: string; }
export type AcceptedCommandClassification = { kind: "MISS" } | { kind: "REPLAY"; command: AcceptedCommandReplay } | { kind: "FINGERPRINT_CONFLICT"; command: AcceptedCommandReplay };
export interface CreateRevisionInput { id?: string; predecessorRevisionId?: string | null; supersedesRevisionId?: string | null; submittedAt?: Date; submitterDisplayNameSnapshot?: string | null; submitterStaffCodeSnapshot?: string | null; }
export interface CreateAcceptedCommandInput { id?: string; actorUserId: string; requestKey: string; requestFingerprint: string; acceptedAt?: Date; targetRevisionId?: string | null; }
export interface AppendHistoryInput { id?: string; actorUserId: string; actorDisplayNameSnapshot?: string | null; actorStaffCodeSnapshot?: string | null; createdAt?: Date; causedByRevisionId?: string | null; }
export interface PersistSubmittedRevisionInput { series: SeriesLogicalKey; frozen: FrozenReportingStatementSnapshot; revision?: CreateRevisionInput; lifecycleToken: string; command: CreateAcceptedCommandInput; history: AppendHistoryInput; }
@Injectable()
export class ReportingStatementRepository {
  async findSeriesByLogicalKey(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.findUnique({ where: { statementProfile_submitterUserId_academicYearId_fromCivilDate_toCivilDate: key } }); }
  async createSeries(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.create({ data: key }); }
  async lockSeries(tx: ReportingStatementTx, seriesId: string) { const rows = await tx.$queryRaw<{ id: string }[]>(Prisma.sql`SELECT id FROM reporting_statement_series WHERE id = ${seriesId}::uuid FOR UPDATE`); return rows[0] ?? null; }
  async loadCurrentSubmitted(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED }, include: { revision: true } }); }
  async loadCurrentApproved(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.APPROVED }, include: { revision: true } }); }
  async loadAcceptedCommand(tx: ReportingStatementTx, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string): Promise<AcceptedCommandReplay | null> { return tx.reportingStatementCommand.findUnique({ where: { actorUserId_commandType_requestKey: { actorUserId, commandType, requestKey } }, select: { id: true, seriesId: true, targetRevisionId: true, resultRevisionId: true, resultLifecycleState: true, resultLifecycleToken: true, submissionAsOfInstant: true, requestFingerprint: true } }); }
  async classifyAcceptedCommand(tx: ReportingStatementTx, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string, fingerprint: string): Promise<AcceptedCommandClassification> { const command = await this.loadAcceptedCommand(tx, actorUserId, commandType, requestKey); return command ? { kind: command.requestFingerprint === fingerprint ? "REPLAY" : "FINGERPRINT_CONFLICT", command } : { kind: "MISS" }; }
  async createRevision(tx: ReportingStatementTx, seriesId: string, frozen: FrozenReportingStatementSnapshot, input: CreateRevisionInput = {}) { return tx.reportingStatementRevision.create({ data: { ...input, seriesId, snapshotProfile: frozen.snapshot.snapshotProfile, serializerVersion: frozen.snapshot.serializerVersion, canonicalSnapshotJson: frozen.canonicalSnapshotJson, semanticHash: frozen.semanticHash, asOfInstant: frozen.asOfInstant, submitterDisplayNameSnapshot: frozen.snapshot.submitterDisplayNameSnapshot, submitterStaffCodeSnapshot: frozen.snapshot.submitterStaffCodeSnapshot } }); }
  async createRevisionSubjects(tx: ReportingStatementTx, revisionId: string, subjectIds: readonly string[]) { const normalized = [...new Set(subjectIds)].sort(); if (!normalized.length) throw new Error("Reporting Statement revisions require one or more frozen subjects."); await tx.reportingStatementRevisionSubject.createMany({ data: normalized.map((subjectId) => ({ revisionId, subjectId })) }); return normalized; }
  async createInitialRevisionState(tx: ReportingStatementTx, revisionId: string, seriesId: string, lifecycleToken: string) { return tx.reportingStatementRevisionState.create({ data: { revisionId, seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED, lifecycleToken } }); }
  async createAcceptedCommand(tx: ReportingStatementTx, seriesId: string, revisionId: string, state: { lifecycleState: ReportingStatementLifecycleState; lifecycleToken: string }, asOfInstant: Date, input: CreateAcceptedCommandInput) { return tx.reportingStatementCommand.create({ data: { ...input, commandType: ReportingStatementCommandType.SUBMIT, seriesId, resultRevisionId: revisionId, resultLifecycleState: state.lifecycleState, resultLifecycleToken: state.lifecycleToken, submissionAsOfInstant: asOfInstant } }); }
  async appendHistory(tx: ReportingStatementTx, seriesId: string, revisionId: string, commandId: string, lifecycleToken: string, asOfInstant: Date, input: AppendHistoryInput) { return tx.reportingStatementHistory.create({ data: { ...input, seriesId, revisionId, eventType: ReportingStatementHistoryEvent.SUBMITTED, stateBefore: null, stateAfter: ReportingStatementLifecycleState.SUBMITTED, commandId, lifecycleTokenBefore: null, lifecycleTokenAfter: lifecycleToken, submissionAsOfInstant: asOfInstant } }); }
  async transitionLifecycleCas(tx: ReportingStatementTx, input: { revisionId: string; seriesId: string; expectedLifecycleState: ReportingStatementLifecycleState; expectedLifecycleToken: string; nextLifecycleState: ReportingStatementLifecycleState; nextLifecycleToken: string; }): Promise<{ transitioned: boolean }> { const result = await tx.reportingStatementRevisionState.updateMany({ where: { revisionId: input.revisionId, seriesId: input.seriesId, lifecycleState: input.expectedLifecycleState, lifecycleToken: input.expectedLifecycleToken }, data: { lifecycleState: input.nextLifecycleState, lifecycleToken: input.nextLifecycleToken } }); return { transitioned: result.count === 1 }; }
  async persistSubmittedRevision(tx: ReportingStatementTx, input: PersistSubmittedRevisionInput) { if (!input.frozen.frozenSubjectIds.length) throw new Error("Reporting Statement revisions require one or more frozen subjects."); const series = (await this.findSeriesByLogicalKey(tx, input.series)) ?? await this.createSeries(tx, input.series); await this.lockSeries(tx, series.id); const revision = await this.createRevision(tx, series.id, input.frozen, input.revision); const frozenSubjectIds = await this.createRevisionSubjects(tx, revision.id, input.frozen.frozenSubjectIds); const state = await this.createInitialRevisionState(tx, revision.id, series.id, input.lifecycleToken); const command = await this.createAcceptedCommand(tx, series.id, revision.id, state, input.frozen.asOfInstant, input.command); const history = await this.appendHistory(tx, series.id, revision.id, command.id, state.lifecycleToken, input.frozen.asOfInstant, input.history); return { series, revision, state, command, history, frozenSubjectIds }; }
  async readFrozenRevision(tx: ReportingStatementTx, revisionId: string) { return tx.reportingStatementRevision.findUnique({ where: { id: revisionId }, include: { series: true, state: true, subjects: { orderBy: { subjectId: "asc" } }, commandResults: true, historyEntries: { orderBy: { createdAt: "asc" } } } }); }
}
