import { Injectable } from "@nestjs/common";
import { Prisma, PrismaClient, ReportingStatementCommandType, ReportingStatementHistoryEvent, ReportingStatementLifecycleState } from "@prisma/client";
import { assertFrozenReportingStatementIntegrity, FrozenReportingStatementSnapshot } from "./reporting-statement-canonicalizer";
export type ReportingStatementTx = Prisma.TransactionClient;
export type ReportingStatementReadDb = Prisma.TransactionClient | PrismaClient;
export interface SeriesLogicalKey { statementProfile: string; submitterUserId: string; academicYearId: string; fromCivilDate: Date; toCivilDate: Date; }
export interface AcceptedCommandReplay { id: string; seriesId: string; targetRevisionId: string | null; resultRevisionId: string; resultLifecycleState: ReportingStatementLifecycleState; resultLifecycleToken: string; submissionAsOfInstant: Date | null; requestFingerprint: string; }
export type AcceptedCommandClassification = { kind: "MISS" } | { kind: "REPLAY"; command: AcceptedCommandReplay } | { kind: "FINGERPRINT_CONFLICT"; command: AcceptedCommandReplay };
export interface CreateRevisionInput { id?: string; predecessorRevisionId?: string | null; supersedesRevisionId?: string | null; submittedAt?: Date;  }
export interface CreateAcceptedCommandInput { id?: string; actorUserId: string; requestKey: string; requestFingerprint: string; acceptedAt?: Date; targetRevisionId?: string | null; }
export interface AppendHistoryInput { id?: string; actorUserId: string; actorDisplayNameSnapshot?: string | null; actorStaffCodeSnapshot?: string | null; createdAt?: Date; causedByRevisionId?: string | null; }
export interface PersistSubmittedRevisionInput { series: SeriesLogicalKey; frozen: FrozenReportingStatementSnapshot; revision?: CreateRevisionInput; lifecycleToken: string; command: CreateAcceptedCommandInput; history: AppendHistoryInput; }
@Injectable()
export class ReportingStatementRepository {
  async findSeriesByLogicalKey(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.findUnique({ where: { statementProfile_submitterUserId_academicYearId_fromCivilDate_toCivilDate: key } }); }
  private async createSeries(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.create({ data: key }); }
  async lockSeries(tx: ReportingStatementTx, seriesId: string) { const rows = await tx.$queryRaw<{ id: string }[]>(Prisma.sql`SELECT id FROM reporting_statement_series WHERE id = ${seriesId}::uuid FOR UPDATE`); return rows[0] ?? null; }
  async loadCurrentSubmitted(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED }, include: { revision: true } }); }
  async loadCurrentApproved(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.APPROVED }, include: { revision: true } }); }
  async loadAcceptedCommand(tx: ReportingStatementReadDb, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string): Promise<AcceptedCommandReplay | null> { return tx.reportingStatementCommand.findUnique({ where: { actorUserId_commandType_requestKey: { actorUserId, commandType, requestKey } }, select: { id: true, seriesId: true, targetRevisionId: true, resultRevisionId: true, resultLifecycleState: true, resultLifecycleToken: true, submissionAsOfInstant: true, requestFingerprint: true } }); }
  async classifyAcceptedCommand(tx: ReportingStatementReadDb, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string, fingerprint: string): Promise<AcceptedCommandClassification> { const command = await this.loadAcceptedCommand(tx, actorUserId, commandType, requestKey); return command ? { kind: command.requestFingerprint === fingerprint ? "REPLAY" : "FINGERPRINT_CONFLICT", command } : { kind: "MISS" }; }
  private async createRevision(tx: ReportingStatementTx, seriesId: string, frozen: FrozenReportingStatementSnapshot, input: CreateRevisionInput = {}, asOfInstant: Date) { return tx.reportingStatementRevision.create({ data: { ...input, seriesId, snapshotProfile: frozen.snapshot.snapshotProfile, serializerVersion: frozen.snapshot.serializerVersion, canonicalSnapshotJson: frozen.canonicalSnapshotJson, semanticHash: frozen.semanticHash, asOfInstant, submitterDisplayNameSnapshot: frozen.snapshot.submitterDisplayNameSnapshot, submitterStaffCodeSnapshot: frozen.snapshot.submitterStaffCodeSnapshot } }); }
  private async createRevisionSubjects(tx: ReportingStatementTx, revisionId: string, subjectIds: readonly string[]) { const normalized = [...new Set(subjectIds)].sort(); if (!normalized.length) throw new Error("Reporting Statement revisions require one or more frozen subjects."); await tx.reportingStatementRevisionSubject.createMany({ data: normalized.map((subjectId) => ({ revisionId, subjectId })) }); return normalized; }
  private async createInitialRevisionState(tx: ReportingStatementTx, revisionId: string, seriesId: string, lifecycleToken: string) { return tx.reportingStatementRevisionState.create({ data: { revisionId, seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED, lifecycleToken } }); }
  private async createAcceptedCommand(tx: ReportingStatementTx, seriesId: string, revisionId: string, state: { lifecycleState: ReportingStatementLifecycleState; lifecycleToken: string }, asOfInstant: Date, input: CreateAcceptedCommandInput) { return tx.reportingStatementCommand.create({ data: { ...input, commandType: ReportingStatementCommandType.SUBMIT, seriesId, resultRevisionId: revisionId, resultLifecycleState: state.lifecycleState, resultLifecycleToken: state.lifecycleToken, submissionAsOfInstant: asOfInstant } }); }
  private async appendHistory(tx: ReportingStatementTx, seriesId: string, revisionId: string, commandId: string, lifecycleToken: string, asOfInstant: Date, input: AppendHistoryInput) { return tx.reportingStatementHistory.create({ data: { ...input, seriesId, revisionId, eventType: ReportingStatementHistoryEvent.SUBMITTED, stateBefore: null, stateAfter: ReportingStatementLifecycleState.SUBMITTED, commandId, lifecycleTokenBefore: null, lifecycleTokenAfter: lifecycleToken, submissionAsOfInstant: asOfInstant } }); }
  async transitionLifecycleCas(tx: ReportingStatementTx, input: { revisionId: string; seriesId: string; expectedLifecycleState: ReportingStatementLifecycleState; expectedLifecycleToken: string; nextLifecycleState: ReportingStatementLifecycleState; nextLifecycleToken: string; }): Promise<{ transitioned: boolean }> { const result = await tx.reportingStatementRevisionState.updateMany({ where: { revisionId: input.revisionId, seriesId: input.seriesId, lifecycleState: input.expectedLifecycleState, lifecycleToken: input.expectedLifecycleToken }, data: { lifecycleState: input.nextLifecycleState, lifecycleToken: input.nextLifecycleToken } }); return { transitioned: result.count === 1 }; }
  async persistSubmittedRevision(tx: ReportingStatementTx, input: PersistSubmittedRevisionInput) { assertFrozenReportingStatementIntegrity(input.frozen); if (input.series.statementProfile !== input.frozen.snapshot.statementProfile || input.series.submitterUserId !== input.frozen.snapshot.submitterUserId || input.series.academicYearId !== input.frozen.snapshot.academicYearId || civilDate(input.series.fromCivilDate) !== input.frozen.snapshot.fromCivilDate || civilDate(input.series.toCivilDate) !== input.frozen.snapshot.toCivilDate) throw new Error("Reporting Statement series and frozen snapshot integrity failed."); const asOfInstant = new Date(input.frozen.snapshot.asOfInstant); const series = (await this.findSeriesByLogicalKey(tx, input.series)) ?? await this.createSeries(tx, input.series); await this.lockSeries(tx, series.id); const revision = await this.createRevision(tx, series.id, input.frozen, input.revision, asOfInstant); const frozenSubjectIds = await this.createRevisionSubjects(tx, revision.id, input.frozen.frozenSubjectIds); const state = await this.createInitialRevisionState(tx, revision.id, series.id, input.lifecycleToken); const command = await this.createAcceptedCommand(tx, series.id, revision.id, state, asOfInstant, input.command); const history = await this.appendHistory(tx, series.id, revision.id, command.id, state.lifecycleToken, asOfInstant, input.history); return { series, revision, state, command, history, frozenSubjectIds }; }
  async readFrozenRevision(tx: ReportingStatementReadDb, revisionId: string) { return tx.reportingStatementRevision.findUnique({ where: { id: revisionId }, include: { series: true, state: true, subjects: { orderBy: { subjectId: "asc" } }, commandResults: true, historyEntries: { orderBy: [{ createdAt: "asc" }, { id: "asc" }] } } }); }
  async loadRevision(tx: ReportingStatementTx, revisionId: string) { return tx.reportingStatementRevision.findUnique({ where: { id: revisionId }, include: { series: true, state: true, subjects: { orderBy: { subjectId: "asc" } } } }); }
  async lineageTail(tx: ReportingStatementTx, seriesId: string) { const rows = await tx.reportingStatementRevision.findMany({ where: { seriesId }, select: { id: true, predecessorRevisionId: true } }); const parents = new Set(rows.map((x) => x.predecessorRevisionId).filter(Boolean)); const tails = rows.filter((x) => !parents.has(x.id)); return tails.length === 1 ? tails[0] : tails.length === 0 ? null : undefined; }
  async createDecision(tx: ReportingStatementTx, input: { actorUserId: string; commandType: ReportingStatementCommandType; requestKey: string; requestFingerprint: string; seriesId: string; targetRevisionId: string; resultRevisionId: string; resultLifecycleState: ReportingStatementLifecycleState; resultLifecycleToken: string; }) { return tx.reportingStatementCommand.create({ data: input }); }
  async appendDecisionHistory(tx: ReportingStatementTx, input: { seriesId: string; revisionId: string; eventType: ReportingStatementHistoryEvent; stateBefore: ReportingStatementLifecycleState; stateAfter: ReportingStatementLifecycleState; actorUserId: string; actorDisplayNameSnapshot?: string | null; actorStaffCodeSnapshot?: string | null; commandId: string; lifecycleTokenBefore: string; lifecycleTokenAfter: string; causedByRevisionId?: string; }) { return tx.reportingStatementHistory.create({ data: input }); }
  async listRevisions(tx: ReportingStatementReadDb, where: Prisma.ReportingStatementRevisionWhereInput, page: number, pageSize: number) {
    const [items, total] = await Promise.all([
      tx.reportingStatementRevision.findMany({
        where,
        include: { series: true, state: true },
        orderBy: [{ submittedAt: "desc" }, { id: "asc" }],
        skip: (page - 1) * pageSize,
        take: pageSize,
      }),
      tx.reportingStatementRevision.count({ where }),
    ]);
    return { items, total };
  }
}

function civilDate(value: Date): string { return value.toISOString().slice(0, 10); }
