import { Injectable } from "@nestjs/common";
import { Prisma, ReportingStatementCommandType, ReportingStatementHistoryEvent, ReportingStatementLifecycleState } from "@prisma/client";
export type ReportingStatementTx = Prisma.TransactionClient;
export type AcceptedCommandClassification = { kind: "MISS" } | { kind: "REPLAY"; command: AcceptedCommandReplay } | { kind: "FINGERPRINT_CONFLICT"; command: AcceptedCommandReplay };
export interface AcceptedCommandReplay { id: string; seriesId: string; targetRevisionId: string | null; resultRevisionId: string; resultLifecycleState: ReportingStatementLifecycleState; resultLifecycleToken: string; submissionAsOfInstant: Date | null; requestFingerprint: string; }
export interface SeriesLogicalKey { statementProfile: string; submitterUserId: string; academicYearId: string; fromCivilDate: Date; toCivilDate: Date; }
export interface PersistSubmittedRevisionInput { series: SeriesLogicalKey; revision: { id?: string; predecessorRevisionId?: string | null; supersedesRevisionId?: string | null; snapshotProfile: string; serializerVersion: string; canonicalSnapshotJson: string; semanticHash: string; asOfInstant: Date; submitterDisplayNameSnapshot?: string | null; submitterStaffCodeSnapshot?: string | null; submittedAt?: Date }; frozenSubjectIds: readonly string[]; lifecycleToken: string; command: { id?: string; actorUserId: string; requestKey: string; requestFingerprint: string; acceptedAt?: Date }; history: { id?: string; actorUserId: string; actorDisplayNameSnapshot?: string | null; actorStaffCodeSnapshot?: string | null; createdAt?: Date }; }
@Injectable()
export class ReportingStatementRepository {
  async findSeriesByLogicalKey(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.findUnique({ where: { statementProfile_submitterUserId_academicYearId_fromCivilDate_toCivilDate: key } }); }
  async createSeries(tx: ReportingStatementTx, key: SeriesLogicalKey) { return tx.reportingStatementSeries.create({ data: key }); }
  async lockSeries(tx: ReportingStatementTx, seriesId: string) { const rows = await tx.$queryRaw<{ id: string }[]>(Prisma.sql`SELECT id FROM reporting_statement_series WHERE id = ${seriesId}::uuid FOR UPDATE`); return rows[0] ?? null; }
  async loadCurrentSubmitted(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED }, include: { revision: true } }); }
  async loadCurrentApproved(tx: ReportingStatementTx, seriesId: string) { return tx.reportingStatementRevisionState.findFirst({ where: { seriesId, lifecycleState: ReportingStatementLifecycleState.APPROVED }, include: { revision: true } }); }
  async loadAcceptedCommand(tx: ReportingStatementTx, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string): Promise<AcceptedCommandReplay | null> { return tx.reportingStatementCommand.findUnique({ where: { actorUserId_commandType_requestKey: { actorUserId, commandType, requestKey } }, select: { id: true, seriesId: true, targetRevisionId: true, resultRevisionId: true, resultLifecycleState: true, resultLifecycleToken: true, submissionAsOfInstant: true, requestFingerprint: true } }); }
  async classifyAcceptedCommand(tx: ReportingStatementTx, actorUserId: string, commandType: ReportingStatementCommandType, requestKey: string, fingerprint: string): Promise<AcceptedCommandClassification> { const command = await this.loadAcceptedCommand(tx, actorUserId, commandType, requestKey); if (!command) return { kind: "MISS" }; return { kind: command.requestFingerprint === fingerprint ? "REPLAY" : "FINGERPRINT_CONFLICT", command }; }
  async createRevision(tx: ReportingStatementTx, data: Prisma.ReportingStatementRevisionCreateArgs["data"]) { return tx.reportingStatementRevision.create({ data }); }
  async createRevisionSubjects(tx: ReportingStatementTx, revisionId: string, subjectIds: readonly string[]) { const normalized = [...new Set(subjectIds)].sort(); if (!normalized.length) throw new Error("Reporting Statement revisions require one or more frozen subjects."); await tx.reportingStatementRevisionSubject.createMany({ data: normalized.map((subjectId) => ({ revisionId, subjectId })) }); return normalized; }
  async createInitialRevisionState(tx: ReportingStatementTx, revisionId: string, seriesId: string, lifecycleToken: string) { return tx.reportingStatementRevisionState.create({ data: { revisionId, seriesId, lifecycleState: ReportingStatementLifecycleState.SUBMITTED, lifecycleToken } }); }
  async createAcceptedCommand(tx: ReportingStatementTx, data: Prisma.ReportingStatementCommandCreateArgs["data"]) { return tx.reportingStatementCommand.create({ data }); }
  async appendHistory(tx: ReportingStatementTx, data: Prisma.ReportingStatementHistoryCreateArgs["data"]) { return tx.reportingStatementHistory.create({ data }); }
  async transitionLifecycleCas(tx: ReportingStatementTx, input: { revisionId: string; seriesId: string; expectedLifecycleState: ReportingStatementLifecycleState; expectedLifecycleToken: string; nextLifecycleState: ReportingStatementLifecycleState; nextLifecycleToken: string; }): Promise<{ transitioned: boolean }> { const result = await tx.reportingStatementRevisionState.updateMany({ where: { revisionId: input.revisionId, seriesId: input.seriesId, lifecycleState: input.expectedLifecycleState, lifecycleToken: input.expectedLifecycleToken }, data: { lifecycleState: input.nextLifecycleState, lifecycleToken: input.nextLifecycleToken } }); return { transitioned: result.count === 1 }; }
  async persistSubmittedRevision(tx: ReportingStatementTx, input: PersistSubmittedRevisionInput) { const subjects = [...new Set(input.frozenSubjectIds)].sort(); if (!subjects.length) throw new Error("Reporting Statement revisions require one or more frozen subjects."); const series = (await this.findSeriesByLogicalKey(tx, input.series)) ?? await this.createSeries(tx, input.series); await this.lockSeries(tx, series.id); const revision = await this.createRevision(tx, { ...input.revision, seriesId: series.id }); await this.createRevisionSubjects(tx, revision.id, subjects); const state = await this.createInitialRevisionState(tx, revision.id, series.id, input.lifecycleToken); const command = await this.createAcceptedCommand(tx, { ...input.command, commandType: ReportingStatementCommandType.SUBMIT, seriesId: series.id, resultRevisionId: revision.id, resultLifecycleState: state.lifecycleState, resultLifecycleToken: state.lifecycleToken, submissionAsOfInstant: input.revision.asOfInstant }); const history = await this.appendHistory(tx, { ...input.history, seriesId: series.id, revisionId: revision.id, eventType: ReportingStatementHistoryEvent.SUBMITTED, stateBefore: null, stateAfter: ReportingStatementLifecycleState.SUBMITTED, commandId: command.id, causedByRevisionId: null, lifecycleTokenBefore: null, lifecycleTokenAfter: state.lifecycleToken, submissionAsOfInstant: input.revision.asOfInstant }); return { series, revision, state, command, history, frozenSubjectIds: subjects }; }
  async readFrozenRevision(tx: ReportingStatementTx, revisionId: string) { return tx.reportingStatementRevision.findUnique({ where: { id: revisionId }, include: { series: true, state: true, subjects: { orderBy: { subjectId: "asc" } }, commandResults: true, historyEntries: { orderBy: { createdAt: "asc" } } } }); }
}