import { createHash } from "crypto";
import { BadRequestException } from "@nestjs/common";
import { PersonalReportingProjection } from "../personal-reporting-projection/personal-reporting-projection.types";

export const REPORTING_STATEMENT_SNAPSHOT_V1 = "REPORTING_STATEMENT_SNAPSHOT_V1" as const;
export const REPORTING_STATEMENT_SERIALIZER_V1 = "REPORTING_STATEMENT_CANONICAL_JSON_V1" as const;
type CanonicalValue = null | boolean | number | string | CanonicalValue[] | { [key: string]: CanonicalValue };
export interface ReportingStatementSnapshotV1 { snapshotProfile: typeof REPORTING_STATEMENT_SNAPSHOT_V1; serializerVersion: typeof REPORTING_STATEMENT_SERIALIZER_V1; statementProfile: string; submitterUserId: string; submitterDisplayNameSnapshot: string | null; submitterStaffCodeSnapshot: string | null; academicYearId: string; fromCivilDate: string; toCivilDate: string; asOfInstant: string; personalProjectionProfile: string; responsibilityState: "RESPONSIBILITY_PRESENT"; responsibilityManifest: CanonicalValue[]; sections: CanonicalValue[]; counts: CanonicalValue; }
export interface FreezeReportingStatementInput { statementProfile: string; submitterUserId: string; submitterDisplayNameSnapshot?: string | null; submitterStaffCodeSnapshot?: string | null; asOfInstant: Date; projection: PersonalReportingProjection; }
export interface FrozenReportingStatementSnapshot { snapshot: ReportingStatementSnapshotV1; canonicalSnapshotJson: string; semanticHash: string; frozenSubjectIds: string[]; asOfInstant: Date; }

export function canonicalizeJson(value: CanonicalValue): string { assertCanonicalValue(value, "$"); return serialize(value); }
export function sha256CanonicalJson(canonicalSnapshotJson: string): string { return createHash("sha256").update(Buffer.from(canonicalSnapshotJson, "utf8")).digest("hex"); }
export function freezeReportingStatementSnapshot(input: FreezeReportingStatementInput): FrozenReportingStatementSnapshot {
  const { projection } = input;
  if (projection.responsibilityState !== "RESPONSIBILITY_PRESENT") throw new BadRequestException("A zero-responsibility projection cannot create a Statement.");
  if (projection.status !== "PASS" || projection.counts === null) throw new BadRequestException("Only a PASS Personal projection can create a Statement.");
  const frozenSubjectIds = [...new Set(projection.responsibilityManifest.map((x) => x.subjectId))].sort(compare);
  if (!frozenSubjectIds.length) throw new BadRequestException("A Reporting Statement requires at least one frozen subject.");
  if (projection.scope.targetUserId !== input.submitterUserId) throw new BadRequestException("Personal projection owner must equal the Statement submitter.");
  if (projection.scope.asOfInstant.getTime() !== input.asOfInstant.getTime()) throw new BadRequestException("Projection asOfInstant must equal the pinned Statement asOfInstant.");
  const snapshot: ReportingStatementSnapshotV1 = { snapshotProfile: REPORTING_STATEMENT_SNAPSHOT_V1, serializerVersion: REPORTING_STATEMENT_SERIALIZER_V1, statementProfile: requiredString(input.statementProfile, "statementProfile"), submitterUserId: requiredString(input.submitterUserId, "submitterUserId"), submitterDisplayNameSnapshot: input.submitterDisplayNameSnapshot ?? null, submitterStaffCodeSnapshot: input.submitterStaffCodeSnapshot ?? null, academicYearId: requiredString(projection.scope.academicYearId, "academicYearId"), fromCivilDate: civilDate(projection.scope.fromCivilDate), toCivilDate: civilDate(projection.scope.toCivilDate), asOfInstant: instant(input.asOfInstant), personalProjectionProfile: projection.profile, responsibilityState: "RESPONSIBILITY_PRESENT", responsibilityManifest: projection.responsibilityManifest.slice().sort(compareInterval).map((x) => ({ ...x })), sections: projection.sections.slice().sort(compareSection).map((x) => ({ schoolClassId: x.schoolClassId, subjectId: x.subjectId, responsibilityIntervals: x.responsibilityIntervals.slice().sort(compareInterval).map((i) => ({ ...i })), status: x.status, counts: x.counts === null ? null : { ...x.counts }, details: x.details.slice().sort(compareDetail).map((d) => ({ ...d })), findings: x.findings.slice().sort(compareFinding).map((f) => ({ ...f, entityIds: f.entityIds.slice().sort(compare) })) })), counts: { ...projection.counts } };
  const canonicalSnapshotJson = canonicalizeJson(snapshot as unknown as CanonicalValue);
  return { snapshot, canonicalSnapshotJson, semanticHash: sha256CanonicalJson(canonicalSnapshotJson), frozenSubjectIds, asOfInstant: new Date(input.asOfInstant.getTime()) };
}
function serialize(value: CanonicalValue): string { if (value === null) return "null"; if (typeof value === "string") return JSON.stringify(value); if (typeof value === "boolean") return value ? "true" : "false"; if (typeof value === "number") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(serialize).join(",")}]`; return `{${Object.keys(value).sort(compare).map((k) => `${JSON.stringify(k)}:${serialize(value[k])}`).join(",")}}`; }
function assertCanonicalValue(value: unknown, path: string): asserts value is CanonicalValue { if (value === undefined) throw new TypeError(`Undefined is not permitted in canonical JSON at ${path}.`); if (value === null || typeof value === "string" || typeof value === "boolean") return; if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError(`Non-finite number is not permitted in canonical JSON at ${path}.`); return; } if (Array.isArray(value)) { value.forEach((x, i) => assertCanonicalValue(x, `${path}[${i}]`)); return; } if (typeof value !== "object" || Object.getPrototypeOf(value) !== Object.prototype) throw new TypeError(`Unsupported canonical JSON value at ${path}.`); Object.entries(value).forEach(([k, x]) => assertCanonicalValue(x, `${path}.${k}`)); }
function compare(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }
function compareInterval(a: { schoolClassId: string; subjectId: string; validFrom: string; validUntil: string | null; teachingAssignmentId: string }, b: typeof a): number { return compare(a.schoolClassId, b.schoolClassId) || compare(a.subjectId, b.subjectId) || compare(a.validFrom, b.validFrom) || compare(a.validUntil ?? "9999-12-31", b.validUntil ?? "9999-12-31") || compare(a.teachingAssignmentId, b.teachingAssignmentId); }
function compareSection(a: { schoolClassId: string; subjectId: string }, b: typeof a): number { return compare(a.schoolClassId, b.schoolClassId) || compare(a.subjectId, b.subjectId); }
function compareDetail(a: { sourceCivilDate: string; sourceSlotStart: string; sourceSlotEnd: string; sourceNormalOccurrenceKey: string }, b: typeof a): number { return compare(a.sourceCivilDate, b.sourceCivilDate) || compare(a.sourceSlotStart, b.sourceSlotStart) || compare(a.sourceSlotEnd, b.sourceSlotEnd) || compare(a.sourceNormalOccurrenceKey, b.sourceNormalOccurrenceKey); }
function compareFinding(a: { code: string; occurrenceKey: string | null; reason: string }, b: typeof a): number { return compare(a.code, b.code) || compare(a.occurrenceKey ?? "", b.occurrenceKey ?? "") || compare(a.reason, b.reason); }
function requiredString(value: string, name: string): string { if (!value.trim()) throw new BadRequestException(`${name} is required.`); return value; }
function civilDate(value: string): string { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new BadRequestException("Civil dates must use YYYY-MM-DD."); return value; }
function instant(value: Date): string { if (Number.isNaN(value.getTime())) throw new BadRequestException("asOfInstant must be valid."); return value.toISOString(); }
