import { createHash } from "crypto";
import { BadRequestException } from "@nestjs/common";
import { PersonalReportingProjection, PersonalReportingSection, PersonalResponsibilityInterval } from "../personal-reporting-projection/personal-reporting-projection.types";
export const REPORTING_STATEMENT_SNAPSHOT_V1 = "REPORTING_STATEMENT_SNAPSHOT_V1" as const;
export const REPORTING_STATEMENT_SERIALIZER_V1 = "REPORTING_STATEMENT_CANONICAL_JSON_V1" as const;
type CanonicalValue = null | boolean | number | string | CanonicalValue[] | { [key: string]: CanonicalValue };
type DeepReadonly<T> = T extends (infer U)[] ? readonly DeepReadonly<U>[] : T extends object ? { readonly [K in keyof T]: DeepReadonly<T[K]> } : T;
export interface ReportingStatementSnapshotV1 { readonly snapshotProfile: typeof REPORTING_STATEMENT_SNAPSHOT_V1; readonly serializerVersion: typeof REPORTING_STATEMENT_SERIALIZER_V1; readonly statementProfile: string; readonly submitterUserId: string; readonly submitterDisplayNameSnapshot: string | null; readonly submitterStaffCodeSnapshot: string | null; readonly academicYearId: string; readonly fromCivilDate: string; readonly toCivilDate: string; readonly asOfInstant: string; readonly personalProjectionProfile: string; readonly responsibilityState: "RESPONSIBILITY_PRESENT"; readonly responsibilityManifest: readonly DeepReadonly<PersonalResponsibilityInterval>[]; readonly sections: readonly DeepReadonly<PersonalReportingSection>[]; readonly counts: DeepReadonly<NonNullable<PersonalReportingProjection["counts"]>>; }
export interface FreezeReportingStatementInput { statementProfile: string; submitterUserId: string; submitterDisplayNameSnapshot?: string | null; submitterStaffCodeSnapshot?: string | null; asOfInstant: Date; projection: PersonalReportingProjection; }
export interface FrozenReportingStatementSnapshot { readonly snapshot: ReportingStatementSnapshotV1; readonly canonicalSnapshotJson: string; readonly semanticHash: string; readonly frozenSubjectIds: readonly string[]; }
export function canonicalizeJson(value: CanonicalValue): string { assertCanonicalValue(value, "$"); return serialize(value); }
export function sha256CanonicalJson(text: string): string { return createHash("sha256").update(Buffer.from(text, "utf8")).digest("hex"); }
export function freezeReportingStatementSnapshot(input: FreezeReportingStatementInput): FrozenReportingStatementSnapshot { const p = input.projection; if (p.responsibilityState !== "RESPONSIBILITY_PRESENT") throw new BadRequestException("A zero-responsibility projection cannot create a Statement."); if (p.status !== "PASS" || p.counts === null) throw new BadRequestException("Only a PASS Personal projection can create a Statement."); if (p.scope.targetUserId !== input.submitterUserId) throw new BadRequestException("Personal projection owner must equal the Statement submitter."); if (p.scope.asOfInstant.getTime() !== input.asOfInstant.getTime()) throw new BadRequestException("Projection asOfInstant must equal the pinned Statement asOfInstant."); const subjects = [...new Set(p.responsibilityManifest.map((x) => x.subjectId))].sort(compare); if (!subjects.length) throw new BadRequestException("A Reporting Statement requires at least one frozen subject."); const snapshot: ReportingStatementSnapshotV1 = { snapshotProfile: REPORTING_STATEMENT_SNAPSHOT_V1, serializerVersion: REPORTING_STATEMENT_SERIALIZER_V1, statementProfile: required(input.statementProfile), submitterUserId: required(input.submitterUserId), submitterDisplayNameSnapshot: input.submitterDisplayNameSnapshot ?? null, submitterStaffCodeSnapshot: input.submitterStaffCodeSnapshot ?? null, academicYearId: required(p.scope.academicYearId), fromCivilDate: civil(p.scope.fromCivilDate), toCivilDate: civil(p.scope.toCivilDate), asOfInstant: instant(input.asOfInstant), personalProjectionProfile: p.profile, responsibilityState: "RESPONSIBILITY_PRESENT", responsibilityManifest: p.responsibilityManifest.slice().sort(interval).map((x) => ({ ...x })), sections: p.sections.slice().sort(section).map((x) => ({ ...x, responsibilityIntervals: x.responsibilityIntervals.slice().sort(interval).map((i) => ({ ...i })), details: x.details.slice().sort(detail).map((d) => ({ ...d })), findings: x.findings.slice().sort(finding).map((f) => ({ ...f, entityIds: f.entityIds.slice().sort(compare) })) })), counts: { ...p.counts } }; const canonicalSnapshotJson = canonicalizeJson(snapshot as unknown as CanonicalValue); return freezeDeep({ snapshot, canonicalSnapshotJson, semanticHash: sha256CanonicalJson(canonicalSnapshotJson), frozenSubjectIds: subjects }); }
export function assertFrozenReportingStatementIntegrity(frozen: FrozenReportingStatementSnapshot): void { const canonical = canonicalizeJson(frozen.snapshot as unknown as CanonicalValue); if (canonical !== frozen.canonicalSnapshotJson) throw new Error("Frozen Reporting Statement canonical snapshot integrity failed."); if (sha256CanonicalJson(frozen.canonicalSnapshotJson) !== frozen.semanticHash) throw new Error("Frozen Reporting Statement semantic hash integrity failed."); if (frozen.snapshot.snapshotProfile !== REPORTING_STATEMENT_SNAPSHOT_V1 || frozen.snapshot.serializerVersion !== REPORTING_STATEMENT_SERIALIZER_V1) throw new Error("Frozen Reporting Statement version integrity failed."); const subjects = [...new Set(frozen.snapshot.responsibilityManifest.map((x) => x.subjectId))].sort(compare); if (subjects.length === 0 || subjects.length !== frozen.frozenSubjectIds.length || subjects.some((x, i) => x !== frozen.frozenSubjectIds[i])) throw new Error("Frozen Reporting Statement subject integrity failed."); if (instant(new Date(frozen.snapshot.asOfInstant)) !== frozen.snapshot.asOfInstant) throw new Error("Frozen Reporting Statement asOf integrity failed."); }
function serialize(v: CanonicalValue): string { if (v === null) return "null"; if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return JSON.stringify(v); if (Array.isArray(v)) return "[" + v.map(serialize).join(",") + "]"; return "{" + Object.keys(v).sort(compare).map((k) => JSON.stringify(k) + ":" + serialize(v[k])).join(",") + "}"; }
function assertCanonicalValue(v: unknown, path: string): asserts v is CanonicalValue { if (v === undefined) throw new TypeError("Undefined is not permitted in canonical JSON at " + path); if (v === null || typeof v === "string" || typeof v === "boolean") return; if (typeof v === "number") { if (!Number.isFinite(v)) throw new TypeError("Non-finite number is not permitted in canonical JSON at " + path); return; } if (Array.isArray(v)) { v.forEach((x, i) => assertCanonicalValue(x, path + "[" + i + "]")); return; } if (typeof v !== "object" || Object.getPrototypeOf(v) !== Object.prototype) throw new TypeError("Unsupported canonical JSON value at " + path); Object.entries(v).forEach(([k, x]) => assertCanonicalValue(x, path + "." + k)); }
function finding(a: { code: string; occurrenceKey: string | null; reason: string; entityIds: string[] }, b: { code: string; occurrenceKey: string | null; reason: string; entityIds: string[] }): number { return compare(a.code,b.code)||compare(a.occurrenceKey ?? "",b.occurrenceKey ?? "")||compare(a.reason,b.reason)||a.entityIds.slice().sort(compare).join("\u0000").localeCompare(b.entityIds.slice().sort(compare).join("\u0000")); }
function compare(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; } function interval(a: PersonalResponsibilityInterval, b: PersonalResponsibilityInterval): number { return compare(a.schoolClassId,b.schoolClassId)||compare(a.subjectId,b.subjectId)||compare(a.validFrom,b.validFrom)||compare(a.validUntil ?? "9999-12-31",b.validUntil ?? "9999-12-31")||compare(a.teachingAssignmentId,b.teachingAssignmentId); } function section(a: PersonalReportingSection,b: PersonalReportingSection): number { return compare(a.schoolClassId,b.schoolClassId)||compare(a.subjectId,b.subjectId); } function detail(a: { sourceCivilDate:string;sourceSlotStart:string;sourceSlotEnd:string;sourceNormalOccurrenceKey:string },b:typeof a):number{return compare(a.sourceCivilDate,b.sourceCivilDate)||compare(a.sourceSlotStart,b.sourceSlotStart)||compare(a.sourceSlotEnd,b.sourceSlotEnd)||compare(a.sourceNormalOccurrenceKey,b.sourceNormalOccurrenceKey);} function required(v:string):string { if(!v.trim()) throw new BadRequestException("Required string missing."); return v;} function civil(v:string):string { if(!/^\d{4}-\d{2}-\d{2}$/.test(v)) throw new BadRequestException("Civil dates must use YYYY-MM-DD.");return v;} function instant(v:Date):string {if(Number.isNaN(v.getTime())) throw new BadRequestException("asOfInstant must be valid.");return v.toISOString();} function freezeDeep<T>(value:T):T { if(value && typeof value === "object" && !Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value as object)) freezeDeep(child);}return value;}
