import { ConflictException, ForbiddenException } from '@nestjs/common';
import { ReportingStatementsService } from '../../src/reporting-statements/reporting-statements.service';
const request = (id = 'actor') => ({ auth: { user: { id, mustChangePassword: false } } }) as never;
const replay = { kind: 'REPLAY', command: { resultRevisionId: 'r', seriesId: 's', resultLifecycleState: 'APPROVED', resultLifecycleToken: 't', submissionAsOfInstant: null } };
function setup(command: unknown = replay, row: unknown = { series: { submitterUserId: 'owner' }, subjects: [{ subjectId: 'a' }], state: {} }) { const repository = { classifyAcceptedCommand: jest.fn().mockResolvedValue(command), readFrozenRevision: jest.fn().mockResolvedValue(row), loadRevision: jest.fn() }; const authorization = { evaluate: jest.fn().mockResolvedValue({ allowed: true }) }; return { repository, authorization, sut: new ReportingStatementsService({ $transaction: jest.fn() } as never, repository as never, {} as never, authorization as never, { write: jest.fn() } as never, { now: jest.fn() }) }; }
describe('ReportingStatementsService decision and read', () => {
  it('replays APPROVE only after authorization and without mutation', async () => { const x = setup(); await expect(x.sut.decide('r', { expectedLifecycleToken: 't', requestKey: 'k' }, request(), 'APPROVE')).resolves.toMatchObject({ replay: true }); expect(x.authorization.evaluate).toHaveBeenCalled(); expect(x.repository.loadRevision).not.toHaveBeenCalled(); });
  it('rejects changed APPROVE fingerprint', async () => { const x = setup({ kind: 'FINGERPRINT_CONFLICT', command: {} }); await expect(x.sut.decide('r', { expectedLifecycleToken: 't', request(), requestKey: 'k' } as never, request(), 'APPROVE')).rejects.toBeInstanceOf(ConflictException); });
  it('replays REJECT after authorization', async () => { const x = setup(); await expect(x.sut.decide('r', { expectedLifecycleToken: 't', requestKey: 'k' }, request(), 'REJECT')).resolves.toMatchObject({ replay: true }); expect(x.authorization.evaluate).toHaveBeenCalled(); });
  it('denies self decision without lifecycle mutation', async () => { const x = setup({ kind: 'MISS' }); x.repository.loadRevision.mockResolvedValue({ series: { submitterUserId: 'actor' }, state: { lifecycleState: 'SUBMITTED', lifecycleToken: 't' } }); x.sut['prisma'].$transaction.mockImplementation((fn: Function) => fn({ ...x.repository })); await expect(x.sut.decide('r', { expectedLifecycleToken: 't', requestKey: 'k' }, request(), 'APPROVE')).rejects.toBeInstanceOf(ForbiddenException); });
  it('authorizes owner PERSONAL read', async () => { const x = setup(undefined, { series: { submitterUserId: 'actor' }, subjects: [] }); await expect(x.sut.read('r', request())).resolves.toBeDefined(); expect(x.authorization.evaluate).toHaveBeenCalledWith(expect.objectContaining({ requestedScope: 'PERSONAL' })); });
  it('allows non-owner SCHOOL_WIDE read', async () => { const x = setup(undefined, { series: { submitterUserId: 'owner' }, subjects: [{ subjectId: 'a' }] }); await expect(x.sut.read('r', request())).resolves.toBeDefined(); expect(x.authorization.evaluate).toHaveBeenCalledWith(expect.objectContaining({ requestedScope: 'SCHOOL_WIDE' })); });
  it('requires every frozen SUBJECT and denies partial/empty subject sets', async () => { const x = setup(undefined, { series: { submitterUserId: 'owner' }, subjects: [{ subjectId: 'a' }, { subjectId: 'b' }] }); x.authorization.evaluate.mockResolvedValueOnce({ allowed: false }).mockResolvedValueOnce({ allowed: true }).mockResolvedValueOnce({ allowed: false }); await expect(x.sut.read('r', request())).rejects.toBeInstanceOf(ForbiddenException); const z = setup(undefined, { series: { submitterUserId: 'owner' }, subjects: [] }); z.authorization.evaluate.mockResolvedValue({ allowed: false }); await expect(z.sut.read('r', request())).rejects.toBeInstanceOf(ForbiddenException); });
});
