import { ConflictException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { ReportingStatementsService } from '../../src/reporting-statements/reporting-statements.service';

const asOf = new Date('2026-08-25T00:00:00.000Z');
const dto = { academicYearId: 'year', fromCivilDate: '2026-08-01', toCivilDate: '2026-08-31', requestKey: 'key' };
const request = { auth: { user: { id: 'actor', mustChangePassword: false } }, headers: {} } as never;
const projection = (overrides: Record<string, unknown> = {}) => ({ profile: 'PERSONAL_TEACHING_REPORTING_PROJECTION_V1', scope: { academicYearId: 'year', targetUserId: 'actor', fromCivilDate: '2026-08-01', toCivilDate: '2026-08-31', asOfInstant: asOf }, responsibilityState: 'RESPONSIBILITY_PRESENT', status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 1, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, responsibilityManifest: [{ teachingAssignmentId: 'assignment', schoolClassId: 'class', subjectId: 'subject', validFrom: '2026-08-01', validUntil: null }], sections: [{ schoolClassId: 'class', subjectId: 'subject', responsibilityIntervals: [], status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 1, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 }, details: [], findings: [] }], findings: [], evaluatedAt: asOf.toISOString(), ...overrides });
function setup(classifications: unknown[]) { const repository = { classifyAcceptedCommand: jest.fn(() => Promise.resolve(classifications.shift() ?? { kind: 'MISS' })), findSeriesByLogicalKey: jest.fn().mockResolvedValue(null), lockSeries: jest.fn(), lineageTail: jest.fn(), loadCurrentApproved: jest.fn(), loadCurrentSubmitted: jest.fn(), persistSubmittedRevision: jest.fn().mockResolvedValue({ revision: { id: 'revision' }, series: { id: 'series' }, state: { lifecycleState: 'SUBMITTED', lifecycleToken: 'token' } }) }; const tx = { ...repository, user: { findUnique: jest.fn().mockResolvedValue({ profile: null }) } }; const prisma = { $transaction: jest.fn(async (fn: (value: unknown) => unknown) => fn(tx)) }; const auth = { evaluate: jest.fn().mockResolvedValue({ allowed: true }) }; const resolver = { resolveInTransaction: jest.fn().mockResolvedValue(projection()) }; const clock = { now: jest.fn(() => asOf) }; return { sut: new ReportingStatementsService(prisma as never, repository as never, resolver as never, auth as never, { write: jest.fn() } as never, clock), repository, resolver, auth, clock, prisma }; }
describe('ReportingStatementsService.submit', () => {
  it('authorizes before exact replay without semantic work', async () => { const x = setup([{ kind: 'REPLAY', command: { resultRevisionId: 'r', seriesId: 's', resultLifecycleState: 'SUBMITTED', resultLifecycleToken: 't', submissionAsOfInstant: asOf } }]); const result = await x.sut.submit(dto as never, request); expect(result.replay).toBe(true); expect(x.auth.evaluate.mock.invocationCallOrder[0]).toBeLessThan(x.repository.classifyAcceptedCommand.mock.invocationCallOrder[0]); expect(x.clock.now).not.toHaveBeenCalled(); expect(x.resolver.resolveInTransaction).not.toHaveBeenCalled(); expect(x.repository.persistSubmittedRevision).not.toHaveBeenCalled(); });
  it('rejects a fingerprint conflict before clock and projection', async () => { const x = setup([{ kind: 'FINGERPRINT_CONFLICT', command: {} }]); await expect(x.sut.submit(dto as never, request)).rejects.toBeInstanceOf(ConflictException); expect(x.clock.now).not.toHaveBeenCalled(); expect(x.resolver.resolveInTransaction).not.toHaveBeenCalled(); });
  it('pins clock once and passes its instant through transaction projection and persistence', async () => { const x = setup([{ kind: 'MISS' }, { kind: 'MISS' }]); await x.sut.submit(dto as never, request); expect(x.clock.now).toHaveBeenCalledTimes(1); expect(x.resolver.resolveInTransaction).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ asOfInstant: asOf })); expect(x.repository.persistSubmittedRevision).toHaveBeenCalledWith(expect.anything(), expect.anything()); });
  it.each([
    ['BLOCKED', projection({ status: 'BLOCKED', counts: null })],
    ['ZERO_RESPONSIBILITY', projection({ responsibilityState: 'ZERO_RESPONSIBILITY', responsibilityManifest: [], sections: [], counts: { distributedElapsedCount: 0, completedCount: 0, openDebtCount: 0, lateCount: 0, unconfirmedGapCount: 0 } })],
  ])('rejects %s personal truth before persistence artifacts', async (_case, unsafeProjection) => { const x = setup([{ kind: 'MISS' }, { kind: 'MISS' }]); x.resolver.resolveInTransaction.mockResolvedValue(unsafeProjection); await expect(x.sut.submit(dto as never, request)).rejects.toThrow(); expect(x.repository.persistSubmittedRevision).not.toHaveBeenCalled(); });
  it('retries P2034 with reauthorization, reclassification and the same pinned instant', async () => { const x = setup([{ kind: 'MISS' }, { kind: 'MISS' }, { kind: 'MISS' }]); let calls = 0; x.repository.persistSubmittedRevision.mockImplementation(() => { calls += 1; if (calls === 1) throw new Prisma.PrismaClientKnownRequestError('serialization', { code: 'P2034', clientVersion: '5' }); return Promise.resolve({ revision: { id: 'r' }, series: { id: 's' }, state: { lifecycleState: 'SUBMITTED', lifecycleToken: 't' } }); }); await x.sut.submit(dto as never, request); expect(x.clock.now).toHaveBeenCalledTimes(1); expect(x.auth.evaluate.mock.calls.length).toBeGreaterThan(1); expect(x.repository.classifyAcceptedCommand.mock.calls.length).toBeGreaterThan(2); expect(x.resolver.resolveInTransaction).toHaveBeenCalledTimes(2); expect(x.resolver.resolveInTransaction.mock.calls[0][1].asOfInstant).toBe(x.resolver.resolveInTransaction.mock.calls[1][1].asOfInstant); });
  it('retries a known command identity P2002 and replays the accepted command', async () => { const replay = { kind: 'REPLAY', command: { resultRevisionId: 'r', seriesId: 's', resultLifecycleState: 'SUBMITTED', resultLifecycleToken: 't', submissionAsOfInstant: asOf } }; const x = setup([{ kind: 'MISS' }, { kind: 'MISS' }, replay]); x.repository.persistSubmittedRevision.mockRejectedValue(new Prisma.PrismaClientKnownRequestError('command identity race', { code: 'P2002', clientVersion: '5', meta: { target: 'reporting_statement_commands_actor_type_request_key' } })); const result = await x.sut.submit(dto as never, request); expect(result.replay).toBe(true); expect(x.prisma.$transaction).toHaveBeenCalledTimes(2); expect(x.clock.now).toHaveBeenCalledTimes(1); expect(x.resolver.resolveInTransaction).toHaveBeenCalledTimes(1); expect(x.repository.persistSubmittedRevision).toHaveBeenCalledTimes(1); });
  it('propagates an unrelated P2002 without retrying', async () => { const x = setup([{ kind: 'MISS' }, { kind: 'MISS' }]); const error = new Prisma.PrismaClientKnownRequestError('unrelated unique constraint', { code: 'P2002', clientVersion: '5', meta: { target: 'some_other_unique_constraint' } }); x.repository.persistSubmittedRevision.mockRejectedValue(error); await expect(x.sut.submit(dto as never, request)).rejects.toBe(error); expect(x.prisma.$transaction).toHaveBeenCalledTimes(1); });
});
