import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditResult, CatalogStatus, Prisma } from '@prisma/client';
import { AuditService } from '../audit/audit.service'; import { PrismaService } from '../prisma/prisma.service'; import { RequestMeta } from '../auth/auth.types';
type Kind = 'membership' | 'staffSubject'; type Row = { id:string; userId:string; validFrom:Date; validUntil:Date|null; isPrimary:boolean; subjectGroupId?:string; subjectId?:string };
@Injectable() export class AssignmentsService { constructor(private prisma:PrismaService, private audit:AuditService) {}
 private config(kind:Kind) { return kind==='membership' ? { model:'subjectGroupMembership' as const, target:'subjectGroupId', catalog:'subjectGroup' as const, action:'SUBJECT_GROUP_MEMBERSHIP', entity:'SubjectGroupMembership' } : { model:'staffSubject' as const, target:'subjectId', catalog:'subject' as const, action:'STAFF_SUBJECT', entity:'StaffSubject' }; }
 private record(row:Row) { return { ...row, validFrom:row.validFrom.toISOString(), validUntil:row.validUntil?.toISOString() }; }
 private dates(from?:string, until?:string) { const validFrom=from?new Date(from):new Date(); const validUntil=until?new Date(until):null; if(Number.isNaN(+validFrom)|| (validUntil&&Number.isNaN(+validUntil)) || (validUntil&&validUntil<=validFrom)) throw new BadRequestException('Khoảng thời gian không hợp lệ.'); return {validFrom,validUntil}; }
 async list(kind:Kind,q:any) { const c=this.config(kind); const where:any={}; for(const k of ['userId',c.target,'isPrimary']) if(q[k]!==undefined) where[k]=q[k]; if(q.activeAt){const at=new Date(q.activeAt); if(Number.isNaN(+at)) throw new BadRequestException('Thời điểm không hợp lệ.'); where.AND=[{validFrom:{lte:at}},{OR:[{validUntil:null},{validUntil:{gt:at}}]}];} const m:any=(this.prisma as any)[c.model]; const [items,total]=await Promise.all([m.findMany({where,skip:(q.page-1)*q.pageSize,take:q.pageSize,orderBy:[{validFrom:'desc'},{id:'asc'}]}),m.count({where})]); return {items:items.map((x:Row)=>this.record(x)),page:q.page,pageSize:q.pageSize,total}; }
 async get(kind:Kind,id:string) { const row=await (this.prisma as any)[this.config(kind).model].findUnique({where:{id}}); if(!row)throw new NotFoundException('Không tìm thấy bản ghi.');return this.record(row); }
 async create(kind:Kind,dto:any,actor:string,meta:RequestMeta) { const c=this.config(kind), dates=this.dates(dto.validFrom,dto.validUntil), target=dto[c.target]; const user=await this.prisma.user.findUnique({where:{id:dto.userId},select:{id:true}}); const catalog=await (this.prisma as any)[c.catalog].findUnique({where:{id:target},select:{id:true,status:true}}); if(!user||!catalog)throw new NotFoundException('Không tìm thấy tham chiếu.'); if(catalog.status!==CatalogStatus.ACTIVE)throw new ConflictException('Danh mục không còn hoạt động.'); try{return await this.prisma.$transaction(async tx=>{const row=await (tx as any)[c.model].create({data:{userId:dto.userId,[c.target]:target,...dates,isPrimary:dto.isPrimary??false}}); await this.audit.write({actorUserId:actor,action:`${c.action}_CREATED`,entityType:c.entity,entityId:row.id,requestId:meta.requestId,result:AuditResult.SUCCESS},tx);return this.record(row);});}catch(e){this.conflict(e);} }
 async update(kind:Kind,id:string,dto:any,actor:string,meta:RequestMeta) { if(Object.keys(dto).length===0)throw new BadRequestException('Phải có trường cần cập nhật.'); const c=this.config(kind); try{return await this.prisma.$transaction(async tx=>{const m:any=(tx as any)[c.model], old=await m.findUnique({where:{id}});if(!old)throw new NotFoundException('Không tìm thấy bản ghi.'); if(dto.validUntil===null)throw new BadRequestException('Không thể mở lại lịch sử.'); const dates=this.dates(dto.validFrom??old.validFrom.toISOString(),dto.validUntil===undefined?old.validUntil?.toISOString():dto.validUntil); const data:any={...dates};if(dto.isPrimary!==undefined)data.isPrimary=dto.isPrimary;const row=await m.update({where:{id},data});await this.audit.write({actorUserId:actor,action:`${c.action}_UPDATED`,entityType:c.entity,entityId:id,requestId:meta.requestId,result:AuditResult.SUCCESS,metadata:{changedFields:Object.keys(data)}},tx);return this.record(row);});}catch(e){this.conflict(e);} }
 async end(kind:Kind,id:string,dto:any,actor:string,meta:RequestMeta) {const c=this.config(kind);return this.prisma.$transaction(async tx=>{const m:any=(tx as any)[c.model],old=await m.findUnique({where:{id}});if(!old)throw new NotFoundException('Không tìm thấy bản ghi.');if(old.validUntil)return this.record(old);const end=dto.endAt?new Date(dto.endAt):new Date();if(Number.isNaN(+end)||end<=old.validFrom)throw new BadRequestException('Thời điểm kết thúc không hợp lệ.');const row=await m.update({where:{id},data:{validUntil:end}});await this.audit.write({actorUserId:actor,action:`${c.action}_ENDED`,entityType:c.entity,entityId:id,requestId:meta.requestId,result:AuditResult.SUCCESS,metadata:{previousValidUntil:null,newValidUntil:end.toISOString()}},tx);return this.record(row);});}
 private conflict(e:unknown):never {if(e instanceof Prisma.PrismaClientKnownRequestError&&(e.code==='P2002'||e.code==='P2003'||e.code==='P2010'))throw new ConflictException('Bản ghi trùng hoặc chồng lấn thời gian.');throw e;}
}
