import { ConflictException, ForbiddenException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AuthenticatedRequest } from '../../src/auth/auth.types';
import { TeachingExecutionsService } from '../../src/teaching-executions/teaching-executions.service';
import { reverseFingerprint } from '../../src/teaching-executions/teaching-execution-policy';

const now = new Date('2026-08-01T00:45:00.000Z');
const request = (id = 'teacher') => ({ auth: { user: { id, mustChangePassword: false } }, headers: {}, method: 'POST', path: '/api/teaching-executions' } as unknown as AuthenticatedRequest);

const activityRow = (patch: Partial<Prisma.SpecialActivityParticipationExecutionGetPayload<object>> = {}): Prisma.SpecialActivityParticipationExecutionGetPayload<object> => ({
  id: 'participation', status: 'ACTIVE', specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', academicYearId: 'year', executionCivilDate: new Date('2026-08-01Z'), executionAcademicCalendarVersionId: 'calendar', executionTimeSlotDefinitionId: 'slot', executionAcademicWeekId: null, executionAcademicWeekSegmentId: null, actualTeacherUserId: 'teacher', activityTitleSnapshot: 'Activity', actualTeacherDisplayNameSnapshot: 'Teacher', createRequestKey: 'activity-key', createRequestFingerprint: 'activity-fingerprint', reversedByUserId: null, reversedAt: null, reversalReason: null, reverseRequestKey: null, reverseRequestFingerprint: null, replacesId: null, createdByUserId: 'creator', createdAt: new Date('2026-08-01T01:00:00Z'), updatedAt: new Date('2026-08-01T01:00:00Z'), ...patch,
});

const curricularRow = (patch: Partial<Prisma.CurricularTeachingExecutionGetPayload<object>> = {}): Prisma.CurricularTeachingExecutionGetPayload<object> => ({
  id: 'execution', kind: 'NORMAL', status: 'ACTIVE', academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', sourceNormalOccurrenceKey: 'NORMAL:entry:2026-08-01', sourceCivilDate: new Date('2026-08-01Z'), originalTimetableVersionId: 'version', originalTimetableEntryId: 'entry', sourceAcademicCalendarVersionId: 'calendar', sourceTimeSlotDefinitionId: 'slot', originalTeachingAssignmentId: 'assignment', responsibleTeacherUserId: 'responsible', ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'ppct-version', ppctItemId: 'item', ppctItemRevisionId: 'revision', operationalLessonDispositionId: null, operationalDispositionType: null, makeupTeachingScheduleId: null, executionCivilDate: new Date('2026-08-01Z'), executionAcademicCalendarVersionId: 'calendar', executionTimeSlotDefinitionId: 'slot', executionAcademicWeekId: 'week', executionAcademicWeekSegmentId: 'segment', actualTeacherUserId: 'teacher', schoolClassCodeSnapshot: '10A', schoolClassNameSnapshot: '10A', subjectCodeSnapshot: 'M', subjectNameSnapshot: 'Math', responsibleTeacherDisplayNameSnapshot: 'Responsible', actualTeacherDisplayNameSnapshot: 'Teacher', note: null, createRequestKey: 'key', createRequestFingerprint: 'fingerprint', reversedByUserId: null, reversedAt: null, reversalReason: null, reverseRequestKey: null, reverseRequestFingerprint: null, replacesId: null, createdByUserId: 'creator', createdAt: new Date('2026-08-01T01:00:00Z'), updatedAt: new Date('2026-08-01T01:00:00Z'), ...patch,
});

function baseService(prisma: object, access: object, structural: object = {}, audit: object = { write: jest.fn() }, clock = { now: () => now }) {
  return new TeachingExecutionsService(prisma as never, { resolve: jest.fn(), resolveInTransaction: jest.fn() } as never, structural as never, audit as never, access as never, clock);
}

describe('activity participation confirmation', () => {
  function harness(patch: { activity?: object | null; findings?: object[]; segments?: object[]; accessError?: Error } = {}) {
    const activity = patch.activity === undefined ? { id: 'activity', status: 'ACTIVE', academicYearId: 'year', academicCalendarVersionId: 'calendar', civilDate: new Date('2026-08-01Z'), title: 'Activity', staffing: [{ id: 'staffing', scheduledTeacherUserId: 'teacher', scheduledTeacher: { profile: { displayName: 'Teacher' } } }], timeSlots: [{ id: 'activity-slot', timeSlotDefinitionId: 'slot', timeSlotDefinition: { endTime: new Date('1970-01-01T07:45:00Z') } }] } : patch.activity;
    const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(null), create: jest.fn().mockResolvedValue(activityRow()) }, specialActivity: { findUnique: jest.fn().mockResolvedValue(activity) }, academicWeekSegment: { findMany: jest.fn().mockResolvedValue(patch.segments ?? []) } };
    const prisma = { $transaction: jest.fn((callback: (client: typeof tx) => Promise<unknown>) => callback(tx)) };
    const structural = { resolveInTransaction: jest.fn().mockResolvedValue({ findings: patch.findings ?? [] }) };
    const access = { requireActivity: patch.accessError ? jest.fn().mockRejectedValue(patch.accessError) : jest.fn().mockResolvedValue('PERSONAL'), requireCurricular: jest.fn() };
    const audit = { write: jest.fn().mockResolvedValue(undefined) };
    return { sut: baseService(prisma, access, structural, audit), tx, prisma, structural, access, audit };
  }

  it('confirms exact activity/staffing/slot, derives teacher, retains null week, and audits on the supplied tx', async () => {
    const h = harness();
    const result = await h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'new-key' }, request());
    expect(h.prisma.$transaction).toHaveBeenCalledWith(expect.any(Function), { isolationLevel: 'Serializable' });
    expect(h.structural.resolveInTransaction).toHaveBeenCalledWith(h.tx, expect.objectContaining({ academicYearId: 'year' }));
    expect(h.access.requireActivity).toHaveBeenCalledWith(expect.any(Object), 'teacher');
    expect(h.tx.specialActivityParticipationExecution.create).toHaveBeenCalledWith({ data: expect.objectContaining({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', actualTeacherUserId: 'teacher', executionAcademicWeekId: null, executionAcademicWeekSegmentId: null, activityTitleSnapshot: 'Activity', actualTeacherDisplayNameSnapshot: 'Teacher' }) });
    expect(h.audit.write).toHaveBeenCalledWith(expect.objectContaining({ action: 'TEACHING_EXECUTION_CONFIRMED', result: 'SUCCESS' }), h.tx);
    expect(result.outcome).toBe('CREATED');
  });

  it.each([
    ['wrong staffing', { specialActivityId: 'activity', specialActivityStaffingId: 'wrong', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }],
    ['wrong slot', { specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'wrong', requestKey: 'k' }],
  ])('rejects %s without a write or success audit', async (_label, dto) => {
    const h = harness();
    await expect(h.sut.confirmActivity(dto, request())).rejects.toThrow('không thuộc');
    expect(h.tx.specialActivityParticipationExecution.create).not.toHaveBeenCalled(); expect(h.audit.write).not.toHaveBeenCalled();
  });
  it('rejects a REVERSED activity root', async () => { const h = harness({ activity: { id: 'activity', status: 'REVERSED' } }); await expect(h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }, request())).rejects.toThrow('không còn ACTIVE'); });
  it('rejects a structural blocker involving the activity', async () => { const h = harness({ findings: [{ entityIds: ['activity'] }] }); await expect(h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }, request())).rejects.toThrow('blocker cấu trúc'); });
  it('rejects missing scheduled-teacher display snapshot', async () => { const h = harness({ activity: { id: 'activity', status: 'ACTIVE', academicYearId: 'year', academicCalendarVersionId: 'calendar', civilDate: new Date('2026-08-01Z'), title: 'Activity', staffing: [{ id: 'staffing', scheduledTeacherUserId: 'teacher', scheduledTeacher: { profile: null } }], timeSlots: [{ id: 'activity-slot', timeSlotDefinitionId: 'slot', timeSlotDefinition: { endTime: new Date('1970-01-01T07:45:00Z') } }] } }); await expect(h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }, request())).rejects.toThrow('display snapshot'); });
  it('rejects ambiguous activity academic segments', async () => { const h = harness({ segments: [{ id: 'a', academicWeekId: 'w1' }, { id: 'b', academicWeekId: 'w2' }] }); await expect(h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }, request())).rejects.toThrow('mơ hồ'); });
  it('denies wrong PERSONAL/SUBJECT actors before writing', async () => { const h = harness({ accessError: new ForbiddenException() }); await expect(h.sut.confirmActivity({ specialActivityId: 'activity', specialActivityStaffingId: 'staffing', specialActivityTimeSlotId: 'activity-slot', requestKey: 'k' }, request('other'))).rejects.toBeInstanceOf(ForbiddenException); expect(h.tx.specialActivityParticipationExecution.create).not.toHaveBeenCalled(); });
});

describe('activity replay authorization ordering', () => {
  it('allows authorized replay and conflicts only after authorization', async () => {
    const access = { requireActivity: jest.fn().mockResolvedValue('SCHOOL_WIDE') }; const sut = baseService({}, access);
    const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(activityRow()) } };
    await expect(sut['activityReplay'](tx as never, 'activity-key', 'activity-fingerprint', request('manager'))).resolves.toMatchObject({ outcome: 'IDEMPOTENT_REPLAY' });
    await expect(sut['activityReplay'](tx as never, 'activity-key', 'different', request('manager'))).rejects.toBeInstanceOf(ConflictException);
  });
  it('denies before fingerprint disclosure', async () => { const access = { requireActivity: jest.fn().mockRejectedValue(new ForbiddenException()) }; const sut = baseService({}, access); const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(activityRow()) } }; await expect(sut['activityReplay'](tx as never, 'activity-key', 'different', request('other'))).rejects.toBeInstanceOf(ForbiddenException); });
});

describe('reversal SERIALIZABLE, CAS, authorization and audit', () => {
  function curricularHarness(row = curricularRow(), updateCount = 1) {
    const reversed = curricularRow({ status: 'REVERSED', reversedByUserId: 'teacher', reversedAt: now, reversalReason: 'Reason', reverseRequestKey: 'reverse', reverseRequestFingerprint: reverseFingerprint('execution', row.updatedAt.toISOString(), 'Reason') });
    const tx = { curricularTeachingExecution: { findUnique: jest.fn().mockResolvedValue(row), updateMany: jest.fn().mockResolvedValue({ count: updateCount }), findUniqueOrThrow: jest.fn().mockResolvedValue(reversed) } };
    const prisma = { $transaction: jest.fn((cb: (client: typeof tx) => Promise<unknown>) => cb(tx)) }; const audit = { write: jest.fn().mockResolvedValue(undefined) }; const access = { requireCurricular: jest.fn().mockResolvedValue('PERSONAL') };
    return { sut: baseService(prisma, access, {}, audit), tx, prisma, audit, access, reversed };
  }
  it('curricular ACTIVE -> REVERSED uses exact CAS and same-tx success audit', async () => { const h = curricularHarness(); const result = await h.sut.reverseCurricular('execution', { requestKey: 'reverse', expectedUpdatedAt: curricularRow().updatedAt.toISOString(), reversalReason: 'Reason' }, request()); expect(h.prisma.$transaction).toHaveBeenCalledWith(expect.any(Function), { isolationLevel: 'Serializable' }); expect(h.tx.curricularTeachingExecution.updateMany).toHaveBeenCalledWith({ where: { id: 'execution', status: 'ACTIVE', updatedAt: curricularRow().updatedAt }, data: expect.objectContaining({ status: 'REVERSED', reversedByUserId: 'teacher', reversedAt: now, reversalReason: 'Reason' }) }); expect(h.audit.write).toHaveBeenCalledWith(expect.objectContaining({ action: 'TEACHING_EXECUTION_REVERSED' }), h.tx); expect(result.item).toMatchObject({ status: 'REVERSED', reversedByUserId: 'teacher', reversalReason: 'Reason' }); });
  it('rejects stale CAS without success audit', async () => { const h = curricularHarness(); await expect(h.sut.reverseCurricular('execution', { requestKey: 'reverse', expectedUpdatedAt: '2020-01-01T00:00:00.000Z', reversalReason: 'Reason' }, request())).rejects.toThrow('đã thay đổi'); expect(h.tx.curricularTeachingExecution.updateMany).not.toHaveBeenCalled(); expect(h.audit.write).not.toHaveBeenCalled(); });
  it('replays same reversal identity and rejects changed/unrelated identities after authorization', async () => { const updatedAt = curricularRow().updatedAt.toISOString(); const fingerprint = reverseFingerprint('execution', updatedAt, 'Reason'); const row = curricularRow({ status: 'REVERSED', reverseRequestKey: 'reverse', reverseRequestFingerprint: fingerprint }); const h = curricularHarness(row); await expect(h.sut.reverseCurricular('execution', { requestKey: 'reverse', expectedUpdatedAt: updatedAt, reversalReason: 'Reason' }, request())).resolves.toMatchObject({ outcome: 'IDEMPOTENT_REPLAY' }); await expect(h.sut.reverseCurricular('execution', { requestKey: 'reverse', expectedUpdatedAt: updatedAt, reversalReason: 'Changed' }, request())).rejects.toBeInstanceOf(ConflictException); await expect(h.sut.reverseCurricular('execution', { requestKey: 'other', expectedUpdatedAt: updatedAt, reversalReason: 'Reason' }, request())).rejects.toBeInstanceOf(ConflictException); expect(h.access.requireCurricular).toHaveBeenCalled(); });

  it('activity ACTIVE -> REVERSED uses SERIALIZABLE CAS and same-tx audit', async () => { const row = activityRow(); const reversed = activityRow({ status: 'REVERSED', reversedByUserId: 'teacher', reversedAt: now, reversalReason: 'Reason' }); const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(row), updateMany: jest.fn().mockResolvedValue({ count: 1 }), findUniqueOrThrow: jest.fn().mockResolvedValue(reversed) } }; const prisma = { $transaction: jest.fn((cb: (client: typeof tx) => Promise<unknown>) => cb(tx)) }; const audit = { write: jest.fn() }; const sut = baseService(prisma, { requireActivity: jest.fn().mockResolvedValue('PERSONAL') }, {}, audit); await sut.reverseActivity('participation', { requestKey: 'reverse', expectedUpdatedAt: row.updatedAt.toISOString(), reversalReason: 'Reason' }, request()); expect(prisma.$transaction).toHaveBeenCalledWith(expect.any(Function), { isolationLevel: 'Serializable' }); expect(tx.specialActivityParticipationExecution.updateMany).toHaveBeenCalledWith({ where: { id: 'participation', status: 'ACTIVE', updatedAt: row.updatedAt }, data: expect.objectContaining({ status: 'REVERSED', reversedAt: now }) }); expect(audit.write).toHaveBeenCalledWith(expect.objectContaining({ action: 'TEACHING_EXECUTION_REVERSED' }), tx); });
  it('activity reversal rejects stale CAS and emits no success audit', async () => { const row = activityRow(); const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(row), updateMany: jest.fn(), findUniqueOrThrow: jest.fn() } }; const audit = { write: jest.fn() }; const sut = baseService({ $transaction: (cb: (client: typeof tx) => unknown) => cb(tx) }, { requireActivity: jest.fn().mockResolvedValue('PERSONAL') }, {}, audit); await expect(sut.reverseActivity('participation', { requestKey: 'reverse', expectedUpdatedAt: '2020-01-01T00:00:00.000Z', reversalReason: 'Reason' }, request())).rejects.toBeInstanceOf(ConflictException); expect(audit.write).not.toHaveBeenCalled(); });
  it('activity reversal replay authorizes before same/different/unrelated request identity disclosure', async () => { const updatedAt = activityRow().updatedAt.toISOString(); const fingerprint = reverseFingerprint('participation', updatedAt, 'Reason'); const row = activityRow({ status: 'REVERSED', reverseRequestKey: 'reverse', reverseRequestFingerprint: fingerprint }); const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(row), updateMany: jest.fn(), findUniqueOrThrow: jest.fn() } }; const access = { requireActivity: jest.fn().mockResolvedValue('PERSONAL') }; const sut = baseService({ $transaction: (cb: (client: typeof tx) => unknown) => cb(tx) }, access); await expect(sut.reverseActivity('participation', { requestKey: 'reverse', expectedUpdatedAt: updatedAt, reversalReason: 'Reason' }, request())).resolves.toMatchObject({ outcome: 'IDEMPOTENT_REPLAY' }); await expect(sut.reverseActivity('participation', { requestKey: 'reverse', expectedUpdatedAt: updatedAt, reversalReason: 'Changed' }, request())).rejects.toBeInstanceOf(ConflictException); await expect(sut.reverseActivity('participation', { requestKey: 'other', expectedUpdatedAt: updatedAt, reversalReason: 'Reason' }, request())).rejects.toBeInstanceOf(ConflictException); access.requireActivity.mockRejectedValueOnce(new ForbiddenException()); await expect(sut.reverseActivity('participation', { requestKey: 'reverse', expectedUpdatedAt: updatedAt, reversalReason: 'Changed' }, request('other'))).rejects.toBeInstanceOf(ForbiddenException); });
});

describe('replacement topology and time/week policy', () => {
  const source = { academicYearId: 'year', schoolClass: { id: 'class' }, subjectId: 'subject', timetableEntryId: 'entry', civilDate: '2026-08-01', ppctItemId: 'item', ppctBinding: { ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'ppct-version' } };
  it('accepts only a REVERSED exact curricular predecessor and rejects every locked-field mismatch', async () => { const sut = baseService({}, {}); const tx = { curricularTeachingExecution: { findUnique: jest.fn().mockResolvedValue(curricularRow({ status: 'REVERSED' })) } }; await expect(sut['requireCurricularReplacement'](tx as never, 'execution', source)).resolves.toBeUndefined(); for (const patch of [{ academicYearId: 'other' }, { schoolClassId: 'other' }, { subjectId: 'other' }, { originalTimetableEntryId: 'other' }, { sourceCivilDate: new Date('2026-08-02Z') }, { ppctClassAssociationId: 'other' }, { ppctPlanId: 'other' }, { ppctVersionId: 'other' }, { ppctItemId: 'other' }, { status: 'ACTIVE' as const }]) { tx.curricularTeachingExecution.findUnique.mockResolvedValueOnce(curricularRow({ status: 'REVERSED', ...patch })); await expect(sut['requireCurricularReplacement'](tx as never, 'execution', source)).rejects.toBeInstanceOf(ConflictException); } tx.curricularTeachingExecution.findUnique.mockResolvedValueOnce(null); await expect(sut['requireCurricularReplacement'](tx as never, 'missing', source)).rejects.toBeInstanceOf(ConflictException); });
  it('accepts only exact REVERSED activity topology', async () => { const sut = baseService({}, {}); const tx = { specialActivityParticipationExecution: { findUnique: jest.fn().mockResolvedValue(activityRow({ status: 'REVERSED' })) } }; await expect(sut['requireActivityReplacement'](tx as never, 'participation', 'activity', 'staffing', 'activity-slot')).resolves.toBeUndefined(); for (const patch of [{ specialActivityId: 'other' }, { specialActivityStaffingId: 'other' }, { specialActivityTimeSlotId: 'other' }, { status: 'ACTIVE' as const }]) { tx.specialActivityParticipationExecution.findUnique.mockResolvedValueOnce(activityRow({ status: 'REVERSED', ...patch })); await expect(sut['requireActivityReplacement'](tx as never, 'participation', 'activity', 'staffing', 'activity-slot')).rejects.toBeInstanceOf(ConflictException); } });
  it('uses HCM civil time at, after, and before the exact boundary independent of host date', async () => { const sut = baseService({}, {}); await expect(sut['assertEnded']('2026-08-01', '00:15:00', new Date('2026-07-31T17:15:00Z'))).resolves.toBeUndefined(); await expect(sut['assertEnded']('2026-08-01', '00:15:00', new Date('2026-07-31T17:15:01Z'))).resolves.toBeUndefined(); await expect(sut['assertEnded']('2026-08-01', '00:15:00', new Date('2026-07-31T17:14:59.999Z'))).rejects.toBeInstanceOf(ConflictException); });
  it('requires exactly one curricular segment, retains it, and allows null/null only for activity', async () => { const sut = baseService({}, {}); const tx = { academicWeekSegment: { findMany: jest.fn() } }; tx.academicWeekSegment.findMany.mockResolvedValueOnce([]); await expect(sut['requireWeek'](tx as never, 'calendar', new Date('2026-08-01Z'), true)).rejects.toBeInstanceOf(ConflictException); tx.academicWeekSegment.findMany.mockResolvedValueOnce([{ id: 'a', academicWeekId: 'w1' }, { id: 'b', academicWeekId: 'w2' }]); await expect(sut['requireWeek'](tx as never, 'calendar', new Date('2026-08-01Z'), true)).rejects.toBeInstanceOf(ConflictException); tx.academicWeekSegment.findMany.mockResolvedValueOnce([{ id: 'segment', academicWeekId: 'week' }]); await expect(sut['requireWeek'](tx as never, 'calendar', new Date('2026-08-01Z'), true)).resolves.toEqual({ weekId: 'week', segmentId: 'segment' }); tx.academicWeekSegment.findMany.mockResolvedValueOnce([]); await expect(sut['requireWeek'](tx as never, 'calendar', new Date('2026-08-01Z'), false)).resolves.toEqual({ weekId: null, segmentId: null }); tx.academicWeekSegment.findMany.mockResolvedValueOnce([{ id: 'a', academicWeekId: 'w1' }, { id: 'b', academicWeekId: 'w2' }]); await expect(sut['requireWeek'](tx as never, 'calendar', new Date('2026-08-01Z'), false)).rejects.toBeInstanceOf(ConflictException); });
});

describe('exact bounded public response keys', () => {
  const curricularKeys = ['actualTeacherDisplayNameSnapshot','actualTeacherUserId','academicYearId','createdAt','createdByUserId','executionAcademicCalendarVersionId','executionAcademicWeekId','executionAcademicWeekSegmentId','executionCivilDate','executionTimeSlotDefinitionId','id','kind','makeupTeachingScheduleId','note','operationalDispositionType','operationalLessonDispositionId','originalTeachingAssignmentId','originalTimetableEntryId','originalTimetableVersionId','ppctClassAssociationId','ppctItemId','ppctItemRevisionId','ppctPlanId','ppctVersionId','replacesId','responsibleTeacherDisplayNameSnapshot','responsibleTeacherUserId','reversalReason','reversedAt','reversedByUserId','schoolClassCodeSnapshot','schoolClassId','schoolClassNameSnapshot','sourceAcademicCalendarVersionId','sourceCivilDate','sourceNormalOccurrenceKey','sourceTimeSlotDefinitionId','status','subjectCodeSnapshot','subjectId','subjectNameSnapshot','updatedAt'].sort();
  const activityKeys = ['academicYearId','activityTitleSnapshot','actualTeacherDisplayNameSnapshot','actualTeacherUserId','createdAt','createdByUserId','executionAcademicCalendarVersionId','executionAcademicWeekId','executionAcademicWeekSegmentId','executionCivilDate','executionTimeSlotDefinitionId','id','replacesId','reversalReason','reversedAt','reversedByUserId','specialActivityId','specialActivityStaffingId','specialActivityTimeSlotId','status','updatedAt'].sort();
  it.each(['NORMAL create','MAKEUP create','curricular replay','curricular GET','curricular reversal'])('%s exposes the exact curricular key set', () => { expect(Object.keys(baseService({}, {})['curricularRecord'](curricularRow())).sort()).toEqual(curricularKeys); });
  it.each(['activity create','activity replay','activity GET','activity reversal'])('%s exposes the exact activity key set', () => { expect(Object.keys(baseService({}, {})['activityRecord'](activityRow())).sort()).toEqual(activityKeys); });
});
