import { Prisma } from '@prisma/client';
import { integration, normalizedCode, Phase01Harness, testOrigin } from '../helpers/phase01-test-harness';

integration('Teaching Execution runtime relational invariants (PostgreSQL)', () => {
  const h = new Phase01Harness();
  beforeAll(async () => h.start()); afterAll(async () => { try { await clean(); } finally { await h.stop(); } }); beforeEach(async () => clean());
  async function clean() {
    await h.prisma.specialActivityParticipationExecution.deleteMany(); await h.prisma.curricularTeachingExecution.deleteMany();
    await h.prisma.specialActivityStaffing.deleteMany(); await h.prisma.specialActivityTimeSlot.deleteMany(); await h.prisma.specialActivityClassTarget.deleteMany(); await h.prisma.specialActivity.deleteMany();
    await h.prisma.makeupTeachingSchedule.deleteMany(); await h.prisma.operationalLessonDisposition.deleteMany(); await h.prisma.calendarExceptionTimeSlot.deleteMany(); await h.prisma.calendarException.deleteMany();
    await h.prisma.ppctItemLineage.deleteMany(); await h.prisma.ppctClassAssociation.deleteMany(); await h.prisma.ppctItemRevision.deleteMany(); await h.prisma.ppctItem.deleteMany(); await h.prisma.ppctVersion.deleteMany(); await h.prisma.ppctPlan.deleteMany(); await h.clean();
  }
  async function fixture() {
    await h.seedCapabilities([{ key: 'TEACHING_EXECUTION_RECORD', scopes: ['PERSONAL'] }, { key: 'TEACHING_EXECUTION_MANAGE', scopes: ['SUBJECT','SCHOOL_WIDE'] }]);
    const actor = await h.actor({ grants: [{ capabilityKey: 'TEACHING_EXECUTION_RECORD', scopeType: 'PERSONAL' }] });
    const year = await h.prisma.academicYear.create({ data: { code: normalizedCode('EXEC'), name: 'Execution year' } });
    const calendar = await h.prisma.academicCalendarVersion.create({ data: { academicYearId: year.id, versionNumber: 1, startDate: new Date('2026-08-01Z'), endDate: new Date('2027-05-31Z'), officialWeekCount: 35, reserveWeekCount: 1, teachingWeekdays: ['MONDAY','TUESDAY'], isActive: true, activatedAt: new Date('2026-08-01Z') } });
    const week = await h.prisma.academicWeek.create({ data: { calendarVersionId: calendar.id, kind: 'OFFICIAL', officialWeekNumber: 1, displayLabel: 'Week 1', sortOrder: 1 } });
    const segment = await h.prisma.academicWeekSegment.create({ data: { academicWeekId: week.id, calendarVersionId: calendar.id, label: 'Week 1', segmentOrder: 1, startDate: new Date('2026-08-01Z'), endDate: new Date('2026-08-31Z') } });
    const schoolClass = await h.prisma.schoolClass.create({ data: { academicYearId: year.id, code: normalizedCode('C'), name: '10A', gradeLevel: 10 } });
    const subject = await h.prisma.subject.create({ data: { code: normalizedCode('S'), name: 'Subject' } });
    const slot = await h.prisma.timeSlotDefinition.create({ data: { academicYearId: year.id, weekday: 'MONDAY', session: 'MORNING', ordinal: 1, revision: 1, displayLabel: 'One', startTime: new Date('1970-01-01T07:00:00Z'), endTime: new Date('1970-01-01T07:45:00Z'), allowRegularTeaching: true, allowMakeupTeaching: true } });
    const makeupSlot = await h.prisma.timeSlotDefinition.create({ data: { academicYearId: year.id, weekday: 'TUESDAY', session: 'MORNING', ordinal: 1, revision: 1, displayLabel: 'Makeup', startTime: new Date('1970-01-01T07:00:00Z'), endTime: new Date('1970-01-01T07:45:00Z'), allowRegularTeaching: false, allowMakeupTeaching: true } });
    const assignment = await h.prisma.teachingAssignment.create({ data: { academicYearId: year.id, schoolClassId: schoolClass.id, subjectId: subject.id, teacherUserId: actor.id, validFrom: new Date('2026-08-01Z') } });
    const timetable = await h.prisma.timetableVersion.create({ data: { academicYearId: year.id, versionNumber: 1, status: 'ACTIVE', calendarVersionId: calendar.id, effectiveAcademicWeekId: week.id, effectiveFrom: new Date('2026-08-10Z'), createdByUserId: actor.id, validatedByUserId: actor.id, validatedAt: new Date('2026-08-01Z'), approvedByUserId: actor.id, approvedAt: new Date('2026-08-01Z'), activatedByUserId: actor.id, activatedAt: new Date('2026-08-01Z') } });
    const entry = await h.prisma.timetableEntry.create({ data: { timetableVersionId: timetable.id, academicYearId: year.id, weekday: 'MONDAY', timeSlotDefinitionId: slot.id, schoolClassId: schoolClass.id, subjectId: subject.id, teachingAssignmentId: assignment.id, teacherUserId: actor.id } });
    const plan = await h.prisma.ppctPlan.create({ data: { academicYearId: year.id, subjectId: subject.id, gradeLevel: 10 } }); const version = await h.prisma.ppctVersion.create({ data: { ppctPlanId: plan.id, versionNumber: 1, status: 'PUBLISHED', createdByUserId: actor.id, publishedByUserId: actor.id, publishedAt: new Date('2026-08-01Z') } }); const item = await h.prisma.ppctItem.create({ data: { ppctPlanId: plan.id } }); const revision = await h.prisma.ppctItemRevision.create({ data: { ppctVersionId: version.id, ppctPlanId: plan.id, ppctItemId: item.id, sequence: 1, title: 'Lesson', lessonType: 'LESSON' } }); const association = await h.prisma.ppctClassAssociation.create({ data: { academicYearId: year.id, schoolClassId: schoolClass.id, subjectId: subject.id, gradeLevel: 10, ppctPlanId: plan.id, ppctVersionId: version.id, effectiveFrom: new Date('2026-08-01Z'), createdByUserId: actor.id } });
    const staffSubject = await h.prisma.staffSubject.create({ data: { userId: actor.id, subjectId: subject.id, validFrom: new Date('2026-08-01Z') } });
    const makeup = await h.prisma.makeupTeachingSchedule.create({ data: { academicYearId: year.id, originalTimetableVersionId: timetable.id, originalTimetableEntryId: entry.id, originalCivilDate: new Date('2026-08-10Z'), originalAcademicCalendarVersionId: calendar.id, originalTimeSlotDefinitionId: slot.id, schoolClassId: schoolClass.id, subjectId: subject.id, originalTeachingAssignmentId: assignment.id, responsibleTeacherUserId: actor.id, ppctClassAssociationId: association.id, ppctPlanId: plan.id, ppctVersionId: version.id, ppctItemId: item.id, targetCivilDate: new Date('2026-08-11Z'), targetAcademicCalendarVersionId: calendar.id, targetTimeSlotDefinitionId: makeupSlot.id, scheduledTeacherUserId: actor.id, eligibilityCheckedAt: new Date('2026-08-01Z'), eligibilityWasActive: true, eligibilityWasTeachingStaff: true, eligibilitySameSubject: true, eligibilityStaffSubjectId: staffSubject.id, createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: actor.id } });
    const activity = await h.prisma.specialActivity.create({ data: { academicYearId: year.id, academicCalendarVersionId: calendar.id, civilDate: new Date('2026-08-10Z'), scope: 'SCHOOL_WIDE', title: 'Activity', createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: actor.id, timeSlots: { create: { academicYearId: year.id, timeSlotDefinitionId: slot.id } }, staffing: { create: { scheduledTeacherUserId: actor.id, staffProfileId: (await h.prisma.staffProfile.findUniqueOrThrow({ where: { userId: actor.id } })).id, eligibilityCheckedAt: new Date('2026-08-01Z'), eligibilityWasActive: true, eligibilityWasTeachingStaff: true } } }, include: { timeSlots: true, staffing: true } });
    return { actor, year, calendar, week, segment, schoolClass, subject, slot, makeupSlot, assignment, timetable, entry, plan, version, item, revision, association, makeup, activity };
  }
  const normalBody = (f: Awaited<ReturnType<typeof fixture>>, requestKey = crypto.randomUUID(), replacesId?: string) => ({ academicYearId: f.year.id, schoolClassId: f.schoolClass.id, subjectId: f.subject.id, timetableEntryId: f.entry.id, sourceCivilDate: '2026-08-10', requestKey, replacesId });
  const activityBody = (f: Awaited<ReturnType<typeof fixture>>, requestKey = crypto.randomUUID(), replacesId?: string) => ({ specialActivityId: f.activity.id, specialActivityStaffingId: f.activity.staffing[0]!.id, specialActivityTimeSlotId: f.activity.timeSlots[0]!.id, requestKey, replacesId });

  it('DB1 NORMAL persists complete relational provenance and execution+audit atomically', async () => { const f = await fixture(); const response = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f)); expect(response.status).toBe(201); expect(response.body.outcome).toBe('CREATED'); const row = await h.prisma.curricularTeachingExecution.findUniqueOrThrow({ where: { id: response.body.item.id } }); expect(row).toMatchObject({ originalTimetableEntryId: f.entry.id, originalTeachingAssignmentId: f.assignment.id, ppctItemRevisionId: f.revision.id, actualTeacherUserId: f.actor.id }); expect(await h.prisma.auditEvent.count({ where: { entityId: row.id, action: 'TEACHING_EXECUTION_CONFIRMED', result: 'SUCCESS' } })).toBe(1); });
  it('DB2 SAME_SUBJECT_SUBSTITUTION persists exact disposition and assigned-teacher relational provenance', async () => { const f = await fixture(); const substitute = await h.actor({ grants: [{ capabilityKey: 'TEACHING_EXECUTION_RECORD', scopeType: 'PERSONAL' }] }); const proof = await h.prisma.staffSubject.create({ data: { userId: substitute.id, subjectId: f.subject.id, validFrom: new Date('2026-08-01Z') } }); const disposition = await h.prisma.operationalLessonDisposition.create({ data: { academicYearId: f.year.id, timetableVersionId: f.timetable.id, timetableEntryId: f.entry.id, sourceCivilDate: new Date('2026-08-10Z'), academicCalendarVersionId: f.calendar.id, timeSlotDefinitionId: f.slot.id, schoolClassId: f.schoolClass.id, subjectId: f.subject.id, teachingAssignmentId: f.assignment.id, responsibleTeacherUserId: f.actor.id, dispositionType: 'SAME_SUBJECT_SUBSTITUTION', assignedTeacherUserId: substitute.id, eligibilityCheckedAt: new Date('2026-08-01Z'), eligibilityWasActive: true, eligibilityWasTeachingStaff: true, eligibilitySameSubject: true, eligibilityStaffSubjectId: proof.id, createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: f.actor.id } }); const response = await substitute.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f)); expect(response.status).toBe(201); expect(response.body.outcome).toBe('CREATED'); expect(await h.prisma.curricularTeachingExecution.findUniqueOrThrow({ where: { id: response.body.item.id } })).toMatchObject({ operationalLessonDispositionId: disposition.id, actualTeacherUserId: substitute.id, originalTeachingAssignmentId: f.assignment.id }); });
  it('DB3 MAKEUP retains separate original and target FK-consistent bundles', async () => { const f = await fixture(); const response = await f.actor.agent.post('/api/teaching-executions/curricular/makeup').set('Origin', testOrigin).send({ makeupTeachingScheduleId: f.makeup.id, requestKey: crypto.randomUUID() }); expect(response.status).toBe(201); expect(response.body.outcome).toBe('CREATED'); expect(await h.prisma.curricularTeachingExecution.findUniqueOrThrow({ where: { id: response.body.item.id } })).toMatchObject({ sourceCivilDate: new Date('2026-08-10Z'), sourceTimeSlotDefinitionId: f.slot.id, executionCivilDate: new Date('2026-08-11Z'), executionTimeSlotDefinitionId: f.makeupSlot.id, makeupTeachingScheduleId: f.makeup.id }); });
  it('DB4a NORMAL/NORMAL obligation concurrency with different request keys creates exactly one ACTIVE survivor', async () => { const f = await fixture(); const responses = await Promise.all([f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, crypto.randomUUID())), f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, crypto.randomUUID()))]); expect(responses.map((x) => x.status).every((x) => [201,409].includes(x))).toBe(true); expect(responses.some((x) => x.status === 201 && x.body.outcome === 'CREATED')).toBe(true); expect(await h.prisma.curricularTeachingExecution.count({ where: { status: 'ACTIVE' } })).toBe(1); });
  it('DB4b same-key semantic concurrency converges on one curricular execution identity', async () => { const f = await fixture(); const key = crypto.randomUUID(); const responses = await Promise.all([f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, key)), f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, key))]); expect(responses.map((x) => x.status)).toEqual([201,201]); expect(responses.map((x) => x.body.outcome).sort()).toEqual(['CREATED','IDEMPOTENT_REPLAY']); expect(new Set(responses.map((x) => x.body.item.id))).toHaveSize(1); expect(await h.prisma.curricularTeachingExecution.count({ where: { status: 'ACTIVE' } })).toBe(1); });
  it('DB5 independently valid NORMAL/MAKEUP concurrency with different keys creates exactly one ACTIVE obligation owner', async () => { const f = await fixture(); const responses = await Promise.all([f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, crypto.randomUUID())), f.actor.agent.post('/api/teaching-executions/curricular/makeup').set('Origin', testOrigin).send({ makeupTeachingScheduleId: f.makeup.id, requestKey: crypto.randomUUID() })]); expect(responses.map((x) => x.status).every((x) => [201,409].includes(x))).toBe(true); expect(responses.some((x) => x.status === 201 && x.body.outcome === 'CREATED')).toBe(true); expect(await h.prisma.curricularTeachingExecution.count({ where: { status: 'ACTIVE' } })).toBe(1); });
  it('DB6 duplicate activity concurrency with different keys creates exactly one ACTIVE survivor', async () => { const f = await fixture(); const responses = await Promise.all([f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f, crypto.randomUUID())), f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f, crypto.randomUUID()))]); expect(responses.map((x) => x.status).every((x) => [201,409].includes(x))).toBe(true); expect(responses.some((x) => x.status === 201 && x.body.outcome === 'CREATED')).toBe(true); expect(await h.prisma.specialActivityParticipationExecution.count({ where: { status: 'ACTIVE' } })).toBe(1); });
  it('DB7 failed validation leaves neither execution nor success audit', async () => { const f = await fixture(); const response = await f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send({ ...activityBody(f), specialActivityStaffingId: crypto.randomUUID() }); expect(response.status).toBe(409); expect(await h.prisma.specialActivityParticipationExecution.count()).toBe(0); expect(await h.prisma.auditEvent.count({ where: { action: 'TEACHING_EXECUTION_CONFIRMED', result: 'SUCCESS' } })).toBe(0); });
  it('DB8 curricular and activity replacement topology FKs reject existing cross-unit linkage', async () => {
    const f = await fixture();
    const firstNormal = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f));
    expect(firstNormal.status).toBe(201);
    const secondItem = await h.prisma.ppctItem.create({ data: { ppctPlanId: f.plan.id } });
    await h.prisma.ppctItemRevision.create({ data: { ppctVersionId: f.version.id, ppctPlanId: f.plan.id, ppctItemId: secondItem.id, sequence: 2, title: 'Lesson 2', lessonType: 'LESSON' } });
    const secondNormal = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send({ ...normalBody(f), sourceCivilDate: '2026-08-17' });
    expect(secondNormal.status).toBe(201);
    expect(secondNormal.body.item.id).not.toBe(firstNormal.body.item.id);
    expect(secondNormal.body.item.ppctItemId).not.toBe(firstNormal.body.item.ppctItemId);
    await expect(h.prisma.curricularTeachingExecution.update({ where: { id: firstNormal.body.item.id }, data: { replacesId: secondNormal.body.item.id } })).rejects.toMatchObject({ code: 'P2003' });

    const firstActivity = await f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f));
    expect(firstActivity.status).toBe(201);
    const secondActor = await h.actor({ grants: [{ capabilityKey: 'TEACHING_EXECUTION_RECORD', scopeType: 'PERSONAL' }] });
    const secondStaffing = await h.prisma.specialActivityStaffing.create({ data: { specialActivityId: f.activity.id, scheduledTeacherUserId: secondActor.id, staffProfileId: (await h.prisma.staffProfile.findUniqueOrThrow({ where: { userId: secondActor.id } })).id, eligibilityCheckedAt: new Date('2026-08-01Z'), eligibilityWasActive: true, eligibilityWasTeachingStaff: true } });
    const secondActivity = await secondActor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send({ specialActivityId: f.activity.id, specialActivityStaffingId: secondStaffing.id, specialActivityTimeSlotId: f.activity.timeSlots[0]!.id, requestKey: crypto.randomUUID() });
    expect(secondActivity.status).toBe(201);
    expect(secondActivity.body.item.id).not.toBe(firstActivity.body.item.id);
    expect(secondActivity.body.item.specialActivityStaffingId).not.toBe(firstActivity.body.item.specialActivityStaffingId);
    await expect(h.prisma.specialActivityParticipationExecution.update({ where: { id: firstActivity.body.item.id }, data: { replacesId: secondActivity.body.item.id } })).rejects.toMatchObject({ code: 'P2003' });
  });
  it('DB9 reversal retains immutable history and permits separately validated replacements in both families', async () => { const f = await fixture(); const made = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f)); expect(made.status).toBe(201); expect(made.body.outcome).toBe('CREATED'); const reversed = await f.actor.agent.post(`/api/teaching-executions/curricular/${made.body.item.id}/reverse`).set('Origin', testOrigin).send({ requestKey: crypto.randomUUID(), expectedUpdatedAt: made.body.item.updatedAt, reversalReason: 'Correction' }); expect(reversed.status).toBe(200); const replacement = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f, crypto.randomUUID(), made.body.item.id)); expect(replacement.status).toBe(201); expect(await h.prisma.curricularTeachingExecution.count()).toBe(2); const activity = await f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f)); expect(activity.status).toBe(201); expect(activity.body.outcome).toBe('CREATED'); const activityReversed = await f.actor.agent.post(`/api/teaching-executions/activity-participations/${activity.body.item.id}/reverse`).set('Origin', testOrigin).send({ requestKey: crypto.randomUUID(), expectedUpdatedAt: activity.body.item.updatedAt, reversalReason: 'Correction' }); expect(activityReversed.status).toBe(200); expect((await f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f, crypto.randomUUID(), activity.body.item.id))).status).toBe(201); });
  it('DB10 database uniqueness indexes are present for curricular obligations and activity participation', async () => { const indexes = await h.prisma.$queryRaw<Array<{ indexname: string }>>(Prisma.sql`SELECT indexname FROM pg_indexes WHERE indexname IN ('curricular_exec_one_active_obligation_key','activity_participation_one_active_key') ORDER BY indexname`); expect(indexes.map((x) => x.indexname)).toEqual(['activity_participation_one_active_key','curricular_exec_one_active_obligation_key']); });
});
