import { ProgressDebtService } from '../../src/progress-debt/progress-debt.service';

const asOf = new Date('2026-08-12T12:00:00.000Z');
const clock = { now: () => new Date('2026-08-13T00:00:00.000Z') };
const expected = { distributionObligationKey: 'key', ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'version', ppctItemId: 'item', ppctItemRevisionId: 'revision', sequence: 1, title: 'Lesson', lessonType: 'LESSON' };

function allocation(overrides: Record<string, unknown> = {}) {
  const occurrence = { occurrenceKey: 'NORMAL:entry:2026-08-10', family: 'NORMAL_TIMETABLE_OPPORTUNITY', civilDate: '2026-08-10', academicYearId: 'year', academicCalendarVersionId: 'calendar', timetableVersionId: 'timetable', timetableEntryId: 'entry', timeSlot: { id: 'slot', weekday: 'MONDAY', session: 'MORNING', startTime: '07:00:00', endTime: '07:45:00' }, schoolClass: { id: 'class', gradeLevel: 10 }, subjectId: 'subject', teachingAssignmentId: 'assignment', responsibleTeacherUserId: 'teacher', ppctBinding: { ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'version', ppctVersionStatus: 'PUBLISHED' }, effectiveKind: 'BASE_TIMETABLE', interruptionIds: [], exceptionIds: [], suppressingSpecialActivityIds: [], disposition: null, ...overrides };
  return { status: 'PASS', normalAllocations: [{ occurrence, allocationEffect: 'CONSUMES_NEXT_ITEM', allocationStatus: 'ALLOCATED', expectedPpctItem: expected }], makeupSourceMatches: [], findings: [] };
}

function execution(overrides: Record<string, unknown> = {}) {
  return { id: 'execution', kind: 'NORMAL', status: 'ACTIVE', academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', sourceNormalOccurrenceKey: 'NORMAL:entry:2026-08-10', originalTimetableVersionId: 'timetable', originalTimetableEntryId: 'entry', sourceCivilDate: new Date('2026-08-10T00:00:00.000Z'), sourceAcademicCalendarVersionId: 'calendar', sourceTimeSlotDefinitionId: 'slot', originalTeachingAssignmentId: 'assignment', responsibleTeacherUserId: 'teacher', ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'version', ppctItemId: 'item', ppctItemRevisionId: 'revision', operationalLessonDispositionId: null, operationalDispositionType: null, makeupTeachingScheduleId: null, executionCivilDate: new Date('2026-08-10T00:00:00.000Z'), executionAcademicCalendarVersionId: 'calendar', executionTimeSlotDefinitionId: 'slot', actualTeacherUserId: 'teacher', executionTimeSlot: { endTime: new Date('1970-01-01T07:45:00.000Z') }, ...overrides };
}

function harness(result: unknown = allocation(), executions: object[] = [], schedules: object[] = []) {
  const tx = { curricularTeachingExecution: { findMany: jest.fn().mockResolvedValue(executions) }, makeupTeachingSchedule: { findMany: jest.fn().mockResolvedValue(schedules) } };
  const prisma = { $transaction: jest.fn(async (callback: (client: typeof tx) => unknown) => callback(tx)) };
  const resolver = { resolveInTransaction: jest.fn().mockResolvedValue(result) };
  const service = new ProgressDebtService(prisma as never, resolver as never, clock);
  return { tx, prisma, resolver, service };
}

const input = () => ({ academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', asOfInstant: asOf });

describe('ProgressDebtService', () => {
  it('P2 excludes an original source slot that has not ended by asOf', async () => {
    const h = harness(allocation({ civilDate: '2026-08-12', occurrenceKey: 'NORMAL:entry:2026-08-12', timeSlot: { id: 'slot', weekday: 'MONDAY', session: 'MORNING', startTime: '19:00:00', endTime: '20:00:00' } }));
    await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { distributedElapsedCount: 0 } });
  });
  it('P3 classifies elapsed BASE without execution as a gap, not debt', async () => { const h = harness(); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { openDebtCount: 0, unconfirmedGapCount: 1 } }); });
  it('P4 classifies elapsed SAME_SUBJECT_SUBSTITUTION without execution as a gap', async () => { const h = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'SAME_SUBJECT_SUBSTITUTION', assignedTeacherUserId: 'substitute' } })); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { unconfirmedGapCount: 1 } }); });
  it('P5 classifies ABSENCE_NO_REPLACEMENT as debt and late', async () => { const h = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'ABSENCE_NO_REPLACEMENT', assignedTeacherUserId: null } })); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { openDebtCount: 1, lateCount: 1 } }); });
  it('P6 classifies DIFFERENT_SUBJECT_SUPERVISION as debt and late', async () => { const h = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'DIFFERENT_SUBJECT_SUPERVISION', assignedTeacherUserId: 'other' } })); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { openDebtCount: 1, lateCount: 1 } }); });
  it('P7 credits an ended exact ACTIVE NORMAL execution', async () => { const h = harness(allocation(), [execution()]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { completedCount: 1 } }); });
  it('P8 gives REVERSED NORMAL no completion credit', async () => { const h = harness(allocation(), [execution({ status: 'REVERSED' })]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { completedCount: 0, unconfirmedGapCount: 1 } }); });
  it('P9 ignores an ACTIVE execution whose actual slot ends after cutoff', async () => { const h = harness(allocation(), [execution({ executionCivilDate: new Date('2026-08-12T00:00:00.000Z'), executionTimeSlot: { endTime: new Date('1970-01-01T23:00:00.000Z') } })]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { completedCount: 0, unconfirmedGapCount: 1 } }); });
  it('P10 does not let a MakeupTeachingSchedule alone close debt', async () => { const h = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'ABSENCE_NO_REPLACEMENT', assignedTeacherUserId: null } })); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { openDebtCount: 1 } }); });
  it('P11 credits exact ACTIVE MAKEUP without new distribution', async () => {
    const match = { makeupTeachingScheduleId: 'schedule', sourceNormalOccurrenceKey: 'NORMAL:entry:2026-08-10', status: 'MATCH', expectedPpctItem: expected };
    const schedule = { id: 'schedule', status: 'ACTIVE', academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', originalTimetableVersionId: 'timetable', originalTimetableEntryId: 'entry', originalCivilDate: new Date('2026-08-10T00:00:00.000Z'), originalAcademicCalendarVersionId: 'calendar', originalTimeSlotDefinitionId: 'slot', originalTeachingAssignmentId: 'assignment', responsibleTeacherUserId: 'teacher', ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'version', ppctItemId: 'item', targetCivilDate: new Date('2026-08-11T00:00:00.000Z'), targetAcademicCalendarVersionId: 'target-calendar', targetTimeSlotDefinitionId: 'target-slot', scheduledTeacherUserId: 'makeup-teacher' };
    const h = harness({ ...allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'ABSENCE_NO_REPLACEMENT', assignedTeacherUserId: null } }), makeupSourceMatches: [match] }, [execution({ kind: 'MAKEUP', makeupTeachingScheduleId: 'schedule', executionCivilDate: new Date('2026-08-11T00:00:00.000Z'), executionAcademicCalendarVersionId: 'target-calendar', executionTimeSlotDefinitionId: 'target-slot', actualTeacherUserId: 'makeup-teacher' })], [schedule]);
    await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { distributedElapsedCount: 1, completedCount: 1 } });
  });
  it('P12 reopens proven debt when MAKEUP is REVERSED', async () => { const h = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'disposition', dispositionType: 'ABSENCE_NO_REPLACEMENT', assignedTeacherUserId: null } }), [execution({ kind: 'MAKEUP', status: 'REVERSED' })]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ counts: { openDebtCount: 1 } }); });
  it('P13 returns BLOCKED null counts when upstream allocation is blocked', async () => { const h = harness({ status: 'BLOCKED', normalAllocations: [], makeupSourceMatches: [], findings: [{ entityIds: ['allocation'] }] }); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED', counts: null }); });
  it('P14 blocks PPCT item and revision provenance drift', async () => { for (const drift of [{ ppctItemId: 'other-item' }, { ppctItemRevisionId: 'other-revision' }]) { const h = harness(allocation(), [execution(drift)]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED', findings: [expect.objectContaining({ code: 'RECONCILIATION_REQUIRED' })] }); } });
  it('blocks ACTIVE NORMAL non-PPCT retained source drift', async () => { const h = harness(allocation(), [execution({ originalTimetableVersionId: 'other-timetable' })]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED', counts: null, findings: [expect.objectContaining({ code: 'RECONCILIATION_REQUIRED' })] }); });
  it('P15 blocks NORMAL BASE and substitution disposition identity drift', async () => { const base = harness(allocation(), [execution({ operationalLessonDispositionId: 'drift' })]); await expect(base.service.resolveInTransaction(base.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED' }); const substitution = harness(allocation({ effectiveKind: 'OPERATIONAL_DISPOSITION', disposition: { id: 'substitution', dispositionType: 'SAME_SUBJECT_SUBSTITUTION', assignedTeacherUserId: 'substitute' } }), [execution({ operationalLessonDispositionId: 'wrong', operationalDispositionType: 'SAME_SUBJECT_SUBSTITUTION', actualTeacherUserId: 'substitute' })]); await expect(substitution.service.resolveInTransaction(substitution.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED' }); });
  it('P16 blocks MAKEUP schedule source and target provenance drift', async () => { const match = { makeupTeachingScheduleId: 'schedule', sourceNormalOccurrenceKey: 'NORMAL:entry:2026-08-10', status: 'MATCH', expectedPpctItem: expected }; const h = harness({ ...allocation(), makeupSourceMatches: [match] }, [execution({ kind: 'MAKEUP', makeupTeachingScheduleId: 'schedule', executionCivilDate: new Date('2026-08-11T00:00:00.000Z'), executionAcademicCalendarVersionId: 'target-calendar', executionTimeSlotDefinitionId: 'target-slot', actualTeacherUserId: 'makeup-teacher' })], [{ id: 'schedule', status: 'ACTIVE', academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', originalTimetableVersionId: 'wrong-source', originalTimetableEntryId: 'entry', originalCivilDate: new Date('2026-08-10T00:00:00.000Z'), originalAcademicCalendarVersionId: 'calendar', originalTimeSlotDefinitionId: 'slot', originalTeachingAssignmentId: 'assignment', responsibleTeacherUserId: 'teacher', ppctClassAssociationId: 'association', ppctPlanId: 'plan', ppctVersionId: 'version', ppctItemId: 'item', targetCivilDate: new Date('2026-08-12T00:00:00.000Z'), targetAcademicCalendarVersionId: 'target-calendar', targetTimeSlotDefinitionId: 'target-slot', scheduledTeacherUserId: 'makeup-teacher' }]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED' }); });
  it('P17 blocks multiple ended ACTIVE fulfillments', async () => { const h = harness(allocation(), [execution(), execution({ id: 'second' })]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED', counts: null, findings: [expect.objectContaining({ code: 'ACTIVE_FULFILLMENT_AMBIGUOUS' })] }); });
  it('P18 never queries Special Activity participation executions', async () => { const h = harness(); await h.service.resolveInTransaction(h.tx as never, input()); expect((h.tx as Record<string, unknown>).specialActivityParticipationExecution).toBeUndefined(); });
  it('blocks MAKEUP MATCH when a non-revision PPCT obligation identity differs', async () => { const mismatch = { ...expected, ppctVersionId: 'other-version' }; const h = harness({ ...allocation(), makeupSourceMatches: [{ makeupTeachingScheduleId: 'schedule', sourceNormalOccurrenceKey: 'NORMAL:entry:2026-08-10', status: 'MATCH', expectedPpctItem: mismatch }] }, [execution({ kind: 'MAKEUP', makeupTeachingScheduleId: 'schedule' })], [{ id: 'schedule', status: 'ACTIVE' }]); await expect(h.service.resolveInTransaction(h.tx as never, input())).resolves.toMatchObject({ status: 'BLOCKED', counts: null, findings: [expect.objectContaining({ code: 'RECONCILIATION_REQUIRED' })] }); });
  it('P19 opens one RepeatableRead transaction and passes exact allocator input through the same tx', async () => { const h = harness(); await h.service.resolve(input()); expect(h.prisma.$transaction).toHaveBeenCalledTimes(1); expect(h.prisma.$transaction).toHaveBeenCalledWith(expect.any(Function), { isolationLevel: 'RepeatableRead' }); expect(h.resolver.resolveInTransaction).toHaveBeenCalledWith(h.tx, { academicYearId: 'year', schoolClassId: 'class', subjectId: 'subject', throughCivilDate: '2026-08-12' }); });
  it('rejects invalid and future asOf instants', async () => { const h = harness(); await expect(h.service.resolveInTransaction(h.tx as never, { ...input(), asOfInstant: new Date('invalid') })).rejects.toThrow('asOfInstant'); await expect(h.service.resolveInTransaction(h.tx as never, { ...input(), asOfInstant: new Date('2026-08-14T00:00:00.000Z') })).rejects.toThrow('future'); });
});
