import { OperationalLessonDispositionType } from '@prisma/client';
import { ProgressDebtService } from '../../src/progress-debt/progress-debt.service';
import { integration, normalizedCode, Phase01Harness, testOrigin } from '../helpers/phase01-test-harness';

const SOURCE_DATE = '2026-08-10';
const MAKEUP_DATE = '2026-08-11';
const SOURCE_AS_OF = new Date('2026-08-10T01:00:00.000Z');
const MAKEUP_AS_OF = new Date('2026-08-11T01:00:00.000Z');

integration('Progress/debt projection (PostgreSQL)', () => {
  const h = new Phase01Harness();
  beforeAll(async () => h.start());
  afterAll(async () => { try { await clean(); } finally { await h.stop(); } });
  beforeEach(async () => clean());

  async function clean() {
    await h.prisma.specialActivityParticipationExecution.deleteMany(); await h.prisma.curricularTeachingExecution.deleteMany();
    await h.prisma.specialActivityStaffing.deleteMany(); await h.prisma.specialActivityClassTarget.deleteMany(); await h.prisma.specialActivityTimeSlot.deleteMany(); await h.prisma.specialActivity.deleteMany();
    await h.prisma.makeupTeachingSchedule.deleteMany(); await h.prisma.operationalLessonDisposition.deleteMany(); await h.prisma.calendarExceptionTimeSlot.deleteMany(); await h.prisma.calendarException.deleteMany();
    await h.prisma.ppctItemLineage.deleteMany(); await h.prisma.ppctClassAssociation.deleteMany(); await h.prisma.ppctItemRevision.deleteMany(); await h.prisma.ppctItem.deleteMany(); await h.prisma.ppctVersion.deleteMany(); await h.prisma.ppctPlan.deleteMany();
    await h.clean();
  }

  async function fixture() {
    const lifecycleAt = new Date('2026-08-01T00:00:00.000Z');
    await h.seedCapabilities([{ key: 'TEACHING_EXECUTION_RECORD', scopes: ['PERSONAL'] }]);
    const actor = await h.actor({ grants: [{ capabilityKey: 'TEACHING_EXECUTION_RECORD', scopeType: 'PERSONAL' }] });
    const year = await h.prisma.academicYear.create({ data: { code: normalizedCode('PROG'), name: 'Progress year' } });
    const calendar = await h.prisma.academicCalendarVersion.create({ data: { academicYearId: year.id, versionNumber: 1, startDate: new Date('2026-08-01Z'), endDate: new Date('2027-05-31Z'), officialWeekCount: 35, reserveWeekCount: 1, teachingWeekdays: ['MONDAY', 'TUESDAY'], isActive: true, activatedAt: lifecycleAt } });
    const week = await h.prisma.academicWeek.create({ data: { calendarVersionId: calendar.id, kind: 'OFFICIAL', officialWeekNumber: 1, displayLabel: 'Week 1', sortOrder: 1 } });
    await h.prisma.academicWeekSegment.create({ data: { academicWeekId: week.id, calendarVersionId: calendar.id, label: 'Week 1', segmentOrder: 1, startDate: new Date('2026-08-01Z'), endDate: new Date('2026-08-31Z') } });
    const schoolClass = await h.prisma.schoolClass.create({ data: { academicYearId: year.id, code: normalizedCode('C'), name: '10A', gradeLevel: 10 } });
    const subject = await h.prisma.subject.create({ data: { code: normalizedCode('S'), name: 'Subject' } });
    const slot = await h.prisma.timeSlotDefinition.create({ data: { academicYearId: year.id, weekday: 'MONDAY', session: 'MORNING', ordinal: 1, revision: 1, displayLabel: 'Source', startTime: new Date('1970-01-01T07:00:00Z'), endTime: new Date('1970-01-01T07:45:00Z'), allowRegularTeaching: true, allowMakeupTeaching: true } });
    const activitySlot = await h.prisma.timeSlotDefinition.create({ data: { academicYearId: year.id, weekday: 'MONDAY', session: 'MORNING', ordinal: 2, revision: 1, displayLabel: 'Activity', startTime: new Date('1970-01-01T06:00:00Z'), endTime: new Date('1970-01-01T06:30:00Z'), allowRegularTeaching: false, allowMakeupTeaching: false } });
    const makeupSlot = await h.prisma.timeSlotDefinition.create({ data: { academicYearId: year.id, weekday: 'TUESDAY', session: 'MORNING', ordinal: 1, revision: 1, displayLabel: 'Makeup', startTime: new Date('1970-01-01T07:00:00Z'), endTime: new Date('1970-01-01T07:45:00Z'), allowRegularTeaching: false, allowMakeupTeaching: true } });
    const assignment = await h.prisma.teachingAssignment.create({ data: { academicYearId: year.id, schoolClassId: schoolClass.id, subjectId: subject.id, teacherUserId: actor.id, validFrom: new Date('2026-08-01Z') } });
    const timetable = await h.prisma.timetableVersion.create({ data: { academicYearId: year.id, versionNumber: 1, status: 'ACTIVE', calendarVersionId: calendar.id, effectiveAcademicWeekId: week.id, effectiveFrom: new Date(`${SOURCE_DATE}Z`), createdByUserId: actor.id, validatedByUserId: actor.id, validatedAt: lifecycleAt, approvedByUserId: actor.id, approvedAt: lifecycleAt, activatedByUserId: actor.id, activatedAt: lifecycleAt } });
    const entry = await h.prisma.timetableEntry.create({ data: { timetableVersionId: timetable.id, academicYearId: year.id, weekday: 'MONDAY', timeSlotDefinitionId: slot.id, schoolClassId: schoolClass.id, subjectId: subject.id, teachingAssignmentId: assignment.id, teacherUserId: actor.id } });
    const plan = await h.prisma.ppctPlan.create({ data: { academicYearId: year.id, subjectId: subject.id, gradeLevel: 10 } });
    const version = await h.prisma.ppctVersion.create({ data: { ppctPlanId: plan.id, versionNumber: 1, status: 'PUBLISHED', createdByUserId: actor.id, publishedByUserId: actor.id, publishedAt: lifecycleAt } });
    const item = await h.prisma.ppctItem.create({ data: { ppctPlanId: plan.id } });
    await h.prisma.ppctItemRevision.create({ data: { ppctVersionId: version.id, ppctPlanId: plan.id, ppctItemId: item.id, sequence: 1, title: 'Lesson', lessonType: 'LESSON' } });
    const association = await h.prisma.ppctClassAssociation.create({ data: { academicYearId: year.id, schoolClassId: schoolClass.id, subjectId: subject.id, gradeLevel: 10, ppctPlanId: plan.id, ppctVersionId: version.id, effectiveFrom: new Date('2026-08-01Z'), createdByUserId: actor.id } });
    const staffSubject = await h.prisma.staffSubject.create({ data: { userId: actor.id, subjectId: subject.id, validFrom: new Date('2026-08-01Z') } });
    const makeup = await h.prisma.makeupTeachingSchedule.create({ data: { academicYearId: year.id, originalTimetableVersionId: timetable.id, originalTimetableEntryId: entry.id, originalCivilDate: new Date(`${SOURCE_DATE}Z`), originalAcademicCalendarVersionId: calendar.id, originalTimeSlotDefinitionId: slot.id, schoolClassId: schoolClass.id, subjectId: subject.id, originalTeachingAssignmentId: assignment.id, responsibleTeacherUserId: actor.id, ppctClassAssociationId: association.id, ppctPlanId: plan.id, ppctVersionId: version.id, ppctItemId: item.id, targetCivilDate: new Date(`${MAKEUP_DATE}Z`), targetAcademicCalendarVersionId: calendar.id, targetTimeSlotDefinitionId: makeupSlot.id, scheduledTeacherUserId: actor.id, eligibilityCheckedAt: lifecycleAt, eligibilityWasActive: true, eligibilityWasTeachingStaff: true, eligibilitySameSubject: true, eligibilityStaffSubjectId: staffSubject.id, createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: actor.id } });
    const profile = await h.prisma.staffProfile.findUniqueOrThrow({ where: { userId: actor.id } });
    const activity = await h.prisma.specialActivity.create({ data: { academicYearId: year.id, academicCalendarVersionId: calendar.id, civilDate: new Date(`${SOURCE_DATE}Z`), scope: 'SCHOOL_WIDE', title: 'Activity', createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: actor.id, timeSlots: { create: { timeSlotDefinitionId: activitySlot.id } }, staffing: { create: { scheduledTeacherUserId: actor.id, staffProfileId: profile.id, eligibilityCheckedAt: lifecycleAt, eligibilityWasActive: true, eligibilityWasTeachingStaff: true } } }, include: { timeSlots: true, staffing: true } });
    return { actor, year, calendar, schoolClass, subject, slot, assignment, timetable, entry, plan, makeup, activity, service: h.app.get(ProgressDebtService) };
  }

  function resolve(f: Awaited<ReturnType<typeof fixture>>, asOfInstant = SOURCE_AS_OF) { return f.service.resolve({ academicYearId: f.year.id, schoolClassId: f.schoolClass.id, subjectId: f.subject.id, asOfInstant }); }
  function normalBody(f: Awaited<ReturnType<typeof fixture>>) { return { academicYearId: f.year.id, schoolClassId: f.schoolClass.id, subjectId: f.subject.id, timetableEntryId: f.entry.id, sourceCivilDate: SOURCE_DATE, requestKey: crypto.randomUUID() }; }
  function activityBody(f: Awaited<ReturnType<typeof fixture>>) { return { specialActivityId: f.activity.id, specialActivityStaffingId: f.activity.staffing[0]!.id, specialActivityTimeSlotId: f.activity.timeSlots[0]!.id, requestKey: crypto.randomUUID() }; }
  async function absence(f: Awaited<ReturnType<typeof fixture>>) { return h.prisma.operationalLessonDisposition.create({ data: { academicYearId: f.year.id, timetableVersionId: f.timetable.id, timetableEntryId: f.entry.id, sourceCivilDate: new Date(`${SOURCE_DATE}Z`), academicCalendarVersionId: f.calendar.id, timeSlotDefinitionId: f.slot.id, schoolClassId: f.schoolClass.id, subjectId: f.subject.id, teachingAssignmentId: f.assignment.id, responsibleTeacherUserId: f.actor.id, dispositionType: OperationalLessonDispositionType.ABSENCE_NO_REPLACEMENT, createRequestKey: crypto.randomUUID(), createRequestFingerprint: crypto.randomUUID(), createdByUserId: f.actor.id } }); }
  async function counts(f: Awaited<ReturnType<typeof fixture>>) { return Promise.all([h.prisma.curricularTeachingExecution.count({ where: { academicYearId: f.year.id } }), h.prisma.specialActivityParticipationExecution.count({ where: { academicYearId: f.year.id } }), h.prisma.makeupTeachingSchedule.count({ where: { academicYearId: f.year.id } }), h.prisma.operationalLessonDisposition.count({ where: { academicYearId: f.year.id } }), h.prisma.ppctClassAssociation.count({ where: { academicYearId: f.year.id } }), h.prisma.ppctVersion.count({ where: { ppctPlanId: f.plan.id } }), h.prisma.ppctItem.count({ where: { ppctPlanId: f.plan.id } }), h.prisma.ppctItemRevision.count({ where: { ppctPlanId: f.plan.id } }), h.prisma.timetableVersion.count({ where: { academicYearId: f.year.id } }), h.prisma.timetableEntry.count({ where: { academicYearId: f.year.id } }), h.prisma.auditEvent.count({ where: { actorUserId: f.actor.id } })]); }

  it('DB1 elapsed BASE direct obligation without execution is an unconfirmed gap', async () => { const f = await fixture(); await expect(resolve(f)).resolves.toMatchObject({ status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 0, openDebtCount: 0, unconfirmedGapCount: 1 } }); });
  it('DB2 ACTIVE ABSENCE_NO_REPLACEMENT without fulfillment is proven debt and late', async () => { const f = await fixture(); await absence(f); await expect(resolve(f)).resolves.toMatchObject({ status: 'PASS', counts: { openDebtCount: 1, lateCount: 1, unconfirmedGapCount: 0 } }); });
  it('DB3 exact persisted ACTIVE NORMAL fulfillment completes the direct obligation', async () => { const f = await fixture(); const response = await f.actor.agent.post('/api/teaching-executions/curricular/normal').set('Origin', testOrigin).send(normalBody(f)); expect(response.status).toBe(201); await expect(resolve(f)).resolves.toMatchObject({ status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 1 } }); });
  it('DB4 active MakeupTeachingSchedule without MAKEUP execution leaves debt open', async () => { const f = await fixture(); await absence(f); await expect(resolve(f, MAKEUP_AS_OF)).resolves.toMatchObject({ status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 0, openDebtCount: 1, lateCount: 1 } }); });
  it('DB5 exact persisted ACTIVE MAKEUP completes its original obligation without new distribution', async () => { const f = await fixture(); await absence(f); const response = await f.actor.agent.post('/api/teaching-executions/curricular/makeup').set('Origin', testOrigin).send({ makeupTeachingScheduleId: f.makeup.id, requestKey: crypto.randomUUID() }); expect(response.status).toBe(201); await expect(resolve(f, MAKEUP_AS_OF)).resolves.toMatchObject({ status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 1, openDebtCount: 0 } }); });
  it('DB6 REVERSED MAKEUP reopens debt while positive proof remains', async () => { const f = await fixture(); await absence(f); const made = await f.actor.agent.post('/api/teaching-executions/curricular/makeup').set('Origin', testOrigin).send({ makeupTeachingScheduleId: f.makeup.id, requestKey: crypto.randomUUID() }); expect(made.status).toBe(201); const reversed = await f.actor.agent.post(`/api/teaching-executions/curricular/${made.body.item.id}/reverse`).set('Origin', testOrigin).send({ requestKey: crypto.randomUUID(), expectedUpdatedAt: made.body.item.updatedAt, reversalReason: 'Correction' }); expect(reversed.status).toBe(200); await expect(resolve(f, MAKEUP_AS_OF)).resolves.toMatchObject({ status: 'PASS', counts: { completedCount: 0, openDebtCount: 1, lateCount: 1 } }); });
  it('DB7 SpecialActivityParticipationExecution has zero curricular projection effect', async () => { const f = await fixture(); const response = await f.actor.agent.post('/api/teaching-executions/activity-participations').set('Origin', testOrigin).send(activityBody(f)); expect(response.status).toBe(201); await expect(resolve(f)).resolves.toMatchObject({ status: 'PASS', counts: { distributedElapsedCount: 1, completedCount: 0, openDebtCount: 0, unconfirmedGapCount: 1 } }); });
  it('DB8 projection keeps all relevant persisted rows and audit events unchanged', async () => { const f = await fixture(); await absence(f); const before = await counts(f); await resolve(f); expect(await counts(f)).toEqual(before); });
});
