import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { Button } from '../components/ui/button';
import { FormField } from '../components/ui/form-field';
import { DataTable, EmptyState, MutationNotice, PageHeader, PageLoading, Pagination, QueryFailure, SelectField, StatusText } from '../components/ui/management';
import { catalogApi, type CatalogInput } from '../lib/management-api';

export function CatalogPage({ kind }: { kind: 'subject-groups' | 'subjects' }) {
  const isGroup = kind === 'subject-groups';
  const title = isGroup ? 'Tổ chuyên môn' : 'Môn học';
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [editing, setEditing] = useState<{ id?: string; code: string; name: string } | null>(null); const [success, setSuccess] = useState(''); const [confirmId, setConfirmId] = useState<string>();
  const api = catalogApi(kind); const key = ['catalog', kind, { page, status }] as const;
  const query = useQuery({ queryKey: key, queryFn: () => api.list({ page, pageSize: 20, status: status || undefined }) });
  const save = useMutation({ mutationFn: (input: CatalogInput & { id?: string }) => input.id ? api.update(input.id, input) : api.create(input), onSuccess: async () => { setSuccess('Đã lưu danh mục.'); setEditing(null); await queryClient.invalidateQueries({ queryKey: ['catalog', kind] }); } });
  const statusMutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'activate' | 'deactivate' }) => api.action(id, action), onSuccess: async () => { setSuccess('Đã cập nhật trạng thái.'); setConfirmId(undefined); await queryClient.invalidateQueries({ queryKey: ['catalog', kind] }); } });
  function submit(event: FormEvent) { event.preventDefault(); if (!editing?.code.trim() || !editing.name.trim()) return; save.mutate(editing); }
  return <div className="management-page catalog-register"><PageHeader eyebrow="Danh mục nhà trường" title={title} action={<Button type="button" onClick={() => { setSuccess(''); setEditing({ code: '', name: '' }); }}>Thêm {isGroup ? 'tổ' : 'môn'}</Button>}>Quản lý mã, tên và trạng thái. Bản ghi ngừng hoạt động vẫn được giữ trong lịch sử.</PageHeader><MutationNotice error={save.error ?? statusMutation.error} success={success} />{editing && <form className="inline-work-form" onSubmit={submit}><h2>{editing.id ? `Chỉnh sửa ${title.toLowerCase()}` : `Thêm ${title.toLowerCase()}`}</h2><div className="form-grid"><FormField label="Mã" name="catalog-code" value={editing.code} maxLength={50} onChange={(e) => setEditing({ ...editing, code: e.target.value })} required /><FormField label="Tên" name="catalog-name" value={editing.name} maxLength={150} onChange={(e) => setEditing({ ...editing, name: e.target.value })} required /></div><div className="form-actions"><Button type="submit" loading={save.isPending}>{editing.id ? 'Lưu thay đổi' : 'Thêm vào danh mục'}</Button><Button type="button" variant="quiet" onClick={() => setEditing(null)}>Hủy</Button></div></form>}<div className="filter-bar"><SelectField label="Trạng thái" id={`${kind}-status`} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="INACTIVE">Ngừng hoạt động</option></SelectField></div>{query.isPending ? <PageLoading /> : query.isError ? <QueryFailure error={query.error} retry={() => void query.refetch()} /> : query.data.items.length === 0 ? <EmptyState filtered={Boolean(status)} /> : <><DataTable label={`Danh sách ${title.toLowerCase()}`} headings={['Mã', 'Tên', 'Trạng thái', 'Thao tác']}>{query.data.items.map((item) => <tr key={item.id}><td className="technical-value">{item.code}</td><td>{item.name}</td><td><StatusText active={item.status === 'ACTIVE'} activeLabel="Đang hoạt động" inactiveLabel="Ngừng hoạt động" /></td><td><div className="row-actions"><Button type="button" variant="quiet" onClick={() => setEditing({ id: item.id, code: item.code, name: item.name })}>Sửa {item.code}</Button>{confirmId === item.id ? <><span>Xác nhận {item.status === 'ACTIVE' ? 'ngừng' : 'kích hoạt'}?</span><Button type="button" variant="secondary" loading={statusMutation.isPending} onClick={() => statusMutation.mutate({ id: item.id, action: item.status === 'ACTIVE' ? 'deactivate' : 'activate' })}>Xác nhận</Button><Button type="button" variant="quiet" onClick={() => setConfirmId(undefined)}>Hủy</Button></> : <Button type="button" variant="quiet" onClick={() => setConfirmId(item.id)}>{item.status === 'ACTIVE' ? 'Ngừng hoạt động' : 'Kích hoạt'}</Button>}</div></td></tr>)}</DataTable><Pagination page={query.data.page} pageSize={query.data.pageSize} total={query.data.total} onPage={setPage} /></>}</div>;
}
