import type { CivilDateString, HomeroomAssignmentRecord, HomeroomAssignmentTeacherSummary } from '@baogiang/contracts';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState, type FormEvent } from 'react';
import { Button } from '../components/ui/button';
import { FormField } from '../components/ui/form-field';
import { DataTable, EmptyState, MutationNotice, PageHeader, PageLoading, Pagination, QueryFailure, SelectField, TextareaField } from '../components/ui/management';
import { formatCivilDate } from '../lib/academic-structure-api';
import { buildHomeroomInput, homeroomAssignmentApi, isBoundedHistorical, type ChangeHomeroomTeacherInput, type CorrectHomeroomAssignmentInput, type HomeroomAssignmentInput } from '../lib/homeroom-assignment-api';
import { isCivilDate, nextCivilDate, optionalNote } from '../lib/teaching-assignment-api';

type Filters = { schoolClassId: string; teacherUserId: string; activeOn: string };
type CandidateDraft = { teacherUserId: string; search: string; validFrom: string; validUntil: string; entryReason: string };
type CreateDraft = CandidateDraft & { kind: 'create'; schoolClassId: string; note: string };
type EndDraft = { kind: 'end'; row: HomeroomAssignmentRecord; endDate: string };
type ChangeDraft = CandidateDraft & { kind: 'change'; row: HomeroomAssignmentRecord; note: string };
type ReplacementDraft = CandidateDraft & { note: string };
type CorrectDraft = { kind: 'correct'; row: HomeroomAssignmentRecord; reason: string; replacements: ReplacementDraft[]; selected: number };
type Workflow = CreateDraft | EndDraft | ChangeDraft | CorrectDraft;
type Teacher = HomeroomAssignmentTeacherSummary;
const pageSize = 20;
const emptyFilters: Filters = { schoolClassId: '', teacherUserId: '', activeOn: '' };
const blankCandidate = (): CandidateDraft => ({ teacherUserId: '', search: '', validFrom: '', validUntil: '', entryReason: '' });

export function HomeroomAssignmentsPage() {
  const client = useQueryClient();
  const [selectedYearId, setSelectedYearId] = useState(''); const [page, setPage] = useState(1); const [filters, setFilters] = useState<Filters>(emptyFilters);
  const [workflow, setWorkflow] = useState<Workflow>(); const [success, setSuccess] = useState(''); const [formError, setFormError] = useState('');
  const years = useQuery({ queryKey: ['homeroom-assignment-years'], queryFn: () => homeroomAssignmentApi.years({ page: 1, pageSize: 100 }) });
  useEffect(() => { if (!selectedYearId && years.data?.items[0]) setSelectedYearId(years.data.items[0].id); }, [selectedYearId, years.data]);
  const workspace = useQuery({ queryKey: ['homeroom-assignment-workspace', selectedYearId], queryFn: () => homeroomAssignmentApi.workspace(selectedYearId), enabled: Boolean(selectedYearId) });
  const assignments = useQuery({ queryKey: ['homeroom-assignments', selectedYearId, page, filters], queryFn: () => homeroomAssignmentApi.list(selectedYearId, { page, pageSize, schoolClassId: filters.schoolClassId || undefined, teacherUserId: filters.teacherUserId || undefined, activeOn: isCivilDate(filters.activeOn) ? filters.activeOn : undefined }), enabled: Boolean(selectedYearId) });
  const candidate = selectedCandidate(workflow);
  const businessDate = workspace.data?.businessDate;
  const historical = Boolean(candidate && businessDate && isBoundedHistorical(candidate.validUntil, businessDate));
  const candidateDatesValid = Boolean(candidate && isCivilDate(candidate.validFrom) && (!candidate.validUntil || (isCivilDate(candidate.validUntil) && candidate.validUntil >= candidate.validFrom)));
  const eligible = useQuery({ queryKey: ['homeroom-assignment-eligible-teachers', selectedYearId, candidate?.validFrom, candidate?.validUntil ?? ''], queryFn: () => homeroomAssignmentApi.eligibleTeachers(selectedYearId, { validFrom: candidate!.validFrom as CivilDateString, ...(isCivilDate(candidate?.validUntil ?? '') ? { validUntil: candidate!.validUntil as CivilDateString } : {}), page: 1, pageSize: 100 }), enabled: Boolean(selectedYearId && workspace.data?.activeCalendar && candidateDatesValid && !historical) });
  const historicalTeachers = useQuery({ queryKey: ['homeroom-assignment-historical-teachers', selectedYearId, candidate?.search.trim() ?? ''], queryFn: () => homeroomAssignmentApi.historicalTeachers(selectedYearId, { q: candidate!.search.trim(), page: 1, pageSize: 100 }), enabled: Boolean(selectedYearId && historical && (candidate?.search.trim().length ?? 0) >= 2) });
  const candidates = historical ? historicalTeachers.data?.items ?? [] : eligible.data?.items ?? [];
  const candidatePending = historical ? historicalTeachers.isPending : eligible.isPending; const candidateError = historical ? historicalTeachers.error : eligible.error;
  const invalidate = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['homeroom-assignments', selectedYearId] }), client.invalidateQueries({ queryKey: ['homeroom-assignment-workspace', selectedYearId] }), client.invalidateQueries({ queryKey: ['homeroom-assignment-eligible-teachers', selectedYearId] }), client.invalidateQueries({ queryKey: ['homeroom-assignment-historical-teachers', selectedYearId] })]); };
  const createMutation = useMutation({ mutationFn: (input: HomeroomAssignmentInput) => homeroomAssignmentApi.create(selectedYearId, input), onMutate: clearFeedback, onSuccess: async () => { setWorkflow(undefined); setSuccess('Đã tạo phân công chủ nhiệm.'); await invalidate(); } });
  const endMutation = useMutation({ mutationFn: ({ id, endDate }: { id: string; endDate: CivilDateString }) => homeroomAssignmentApi.end(id, endDate), onMutate: clearFeedback, onSuccess: async () => { setWorkflow(undefined); setSuccess('Đã kết thúc phân công; lịch sử vẫn được giữ lại.'); await invalidate(); } });
  const changeMutation = useMutation({ mutationFn: ({ id, input }: { id: string; input: ChangeHomeroomTeacherInput }) => homeroomAssignmentApi.changeTeacher(id, input), onMutate: clearFeedback, onSuccess: async () => { setWorkflow(undefined); setSuccess('Đã đổi giáo viên chủ nhiệm và giữ lại phân công trước đó trong lịch sử.'); await invalidate(); } });
  const correctMutation = useMutation({ mutationFn: ({ id, input }: { id: string; input: CorrectHomeroomAssignmentInput }) => homeroomAssignmentApi.correct(id, input), onMutate: clearFeedback, onSuccess: async () => { setWorkflow(undefined); setSuccess('Đã hiệu chỉnh bằng các bản ghi thay thế; bản ghi nguồn được giữ với trạng thái đảo.'); await invalidate(); } });
  function clearFeedback() { setSuccess(''); setFormError(''); }
  function reset() { clearFeedback(); createMutation.reset(); endMutation.reset(); changeMutation.reset(); correctMutation.reset(); }
  function begin(next: Workflow) { reset(); setWorkflow(next); }
  function changeYear(id: string) { setSelectedYearId(id); setPage(1); setFilters(emptyFilters); setWorkflow(undefined); reset(); }
  function updateFilter<K extends keyof Filters>(key: K, value: Filters[K]) { setFilters((current) => ({ ...current, [key]: value })); setPage(1); }
  const activeCalendar = workspace.data?.activeCalendar ?? null; const activeClasses = workspace.data?.classes.filter((item) => item.status === 'ACTIVE') ?? [];
  const mutationError = createMutation.error ?? endMutation.error ?? changeMutation.error ?? correctMutation.error;
  if (years.isPending) return <div className="management-page"><PageLoading /></div>;
  if (years.isError) return <div className="management-page"><QueryFailure error={years.error} retry={() => void years.refetch()} /></div>;
  if (!years.data.items.length) return <div className="management-page homeroom-ledger"><PageHeader eyebrow="Sổ chủ nhiệm" title="Phân công chủ nhiệm">Theo dõi trách nhiệm giáo viên chủ nhiệm theo ngày dân sự.</PageHeader><EmptyState title="Chưa có năm học" message="Thiết lập năm học để xem lịch sử phân công chủ nhiệm." /></div>;
  const filtered = Object.values(filters).some(Boolean);
  return <div className="management-page homeroom-ledger">
    <PageHeader eyebrow="Sổ chủ nhiệm" title="Phân công chủ nhiệm" action={<Button type="button" disabled={!activeCalendar || workspace.isPending} onClick={() => begin({ kind: 'create', schoolClassId: '', note: '', ...blankCandidate() })}>Tạo phân công</Button>}>Quản trị lịch sử giáo viên chủ nhiệm theo lớp và khoảng hiệu lực.</PageHeader>
    <section className="homeroom-ledger__context" aria-labelledby="homeroom-context"><div className="margin-rail" aria-hidden="true" /><div><h2 id="homeroom-context">Ngữ cảnh năm học</h2><SelectField label="Năm học" id="homeroom-year" value={selectedYearId} onChange={(event) => changeYear(event.target.value)}>{years.data.items.map((year) => <option key={year.id} value={year.id}>{year.code} — {year.name}</option>)}</SelectField>{workspace.isPending ? <PageLoading /> : workspace.isError ? <QueryFailure error={workspace.error} retry={() => void workspace.refetch()} /> : <><p className="calendar-envelope"><strong>Ngày nghiệp vụ do hệ thống xác định:</strong> <span className="technical-value">{formatCivilDate(workspace.data.businessDate)}</span></p>{activeCalendar ? <p className="calendar-envelope"><strong>Phiên lịch đang áp dụng:</strong> <span className="technical-value">{formatCivilDate(activeCalendar.startDate)} – {formatCivilDate(activeCalendar.endDate)}</span></p> : <p className="limitation-note"><strong>Chưa có phiên lịch đang áp dụng.</strong> Lịch sử vẫn đọc được, nhưng chưa thể tạo, kết thúc, đổi giáo viên hoặc hiệu chỉnh; hệ thống cũng không truy vấn ứng viên.</p>}</>}</div></section>
    <MutationNotice error={mutationError} success={success} />{formError && <p className="form-field__error" role="alert"><span aria-hidden="true">!</span> {formError}</p>}
    {workflow && activeCalendar && workspace.data && <WorkflowForm workflow={workflow} calendar={activeCalendar} businessDate={workspace.data.businessDate} classes={activeClasses} candidates={candidates} pending={candidatePending} error={candidateError} onRetry={() => historical ? void historicalTeachers.refetch() : void eligible.refetch()} onChange={setWorkflow} onCancel={() => setWorkflow(undefined)} onCreate={(input) => createMutation.mutate(input)} onEnd={(id, endDate) => endMutation.mutate({ id, endDate })} onChangeTeacher={(id, input) => changeMutation.mutate({ id, input })} onCorrect={(id, input) => correctMutation.mutate({ id, input })} submitting={createMutation.isPending || endMutation.isPending || changeMutation.isPending || correctMutation.isPending} setError={setFormError} />}
    {workspace.data && <div className="filter-bar homeroom-ledger__filters"><SelectField label="Lớp" id="homeroom-filter-class" value={filters.schoolClassId} onChange={(event) => updateFilter('schoolClassId', event.target.value)}><option value="">Tất cả</option>{workspace.data.classes.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</SelectField><SelectField label="Giáo viên trong lịch sử" id="homeroom-filter-teacher" value={filters.teacherUserId} onChange={(event) => updateFilter('teacherUserId', event.target.value)}><option value="">Tất cả</option>{workspace.data.historicalTeachers.map((item) => <option key={item.userId} value={item.userId}>{teacherLabel(item)}</option>)}</SelectField><FormField label="Hiệu lực tại" name="homeroom-filter-active-on" type="date" value={filters.activeOn} onChange={(event) => updateFilter('activeOn', event.target.value)} />{filtered && <Button type="button" variant="quiet" onClick={() => { setFilters(emptyFilters); setPage(1); }}>Xóa bộ lọc</Button>}</div>}
    {assignments.isPending ? <PageLoading /> : assignments.isError ? <QueryFailure error={assignments.error} retry={() => void assignments.refetch()} /> : !assignments.data.items.length ? <EmptyState filtered={filtered} title={filtered ? 'Không có phân công phù hợp bộ lọc' : 'Chưa có lịch sử phân công chủ nhiệm'} message={filtered ? 'Điều chỉnh lớp, giáo viên hoặc ngày hiệu lực rồi thử lại.' : 'Các lần tạo, đổi, kết thúc và hiệu chỉnh sẽ xuất hiện tại đây.'} /> : <><DataTable label="Sổ phân công chủ nhiệm" headings={['Lớp', 'Giáo viên', 'Hiệu lực', 'Trạng thái và truy vết', 'Thao tác']}>{assignments.data.items.map((row) => <AssignmentRow key={row.id} row={row} activeCalendar={activeCalendar} onEnd={() => begin({ kind: 'end', row, endDate: '' })} onChange={() => begin({ kind: 'change', row, note: '', ...blankCandidate() })} onCorrect={() => begin({ kind: 'correct', row, reason: '', selected: 0, replacements: [{ note: '', ...blankCandidate(), validFrom: row.validFrom, validUntil: row.validUntil ?? '' }] })} />)}</DataTable><Pagination page={assignments.data.page} pageSize={assignments.data.pageSize} total={assignments.data.total} onPage={setPage} /></>}
  </div>;
}

function selectedCandidate(workflow: Workflow | undefined): CandidateDraft | undefined { if (!workflow || workflow.kind === 'end') return undefined; return workflow.kind === 'correct' ? workflow.replacements[workflow.selected] : workflow; }
function teacherLabel(teacher: Teacher): string { return `${teacher.displayName}${teacher.staffCode ? ` — ${teacher.staffCode}` : ''}${teacher.userStatus !== 'ACTIVE' ? ' (không còn hoạt động)' : ''}${teacher.isTeachingStaff === false ? ' (không còn là giáo viên)' : ''}`; }

function AssignmentRow({ row, activeCalendar, onEnd, onChange, onCorrect }: { row: HomeroomAssignmentRecord; activeCalendar: { endDate: CivilDateString } | null; onEnd(): void; onChange(): void; onCorrect(): void }) {
  const canMutate = row.status === 'ACTIVE' && Boolean(activeCalendar); const changeMax = row.validUntil ?? activeCalendar?.endDate; const canChange = Boolean(changeMax && nextCivilDate(row.validFrom) <= changeMax);
  return <tr><td><strong>{row.schoolClass.name}</strong><small className="technical-value table-secondary">{row.schoolClass.code} · Khối {row.schoolClass.gradeLevel}</small></td><td><strong>{row.teacher.displayName}</strong><small className="technical-value table-secondary">{row.teacher.staffCode ?? row.teacher.username}</small></td><td><span className="technical-value">{formatCivilDate(row.validFrom)}</span><small className="table-secondary">{row.validUntil ? `đến ${formatCivilDate(row.validUntil)}` : 'Chưa ấn định ngày kết thúc'}</small></td><td><strong>{row.status === 'ACTIVE' ? 'Đang hiệu lực' : 'Đã đảo / hiệu chỉnh'}</strong>{row.entryReason && <small className="table-secondary">Nguồn: {row.entryReason}</small>}{row.note && <small className="table-secondary">Ghi chú: {row.note}</small>}{row.replacesId && <small className="technical-value table-secondary">Thay thế: {row.replacesId}</small>}{row.reversalReason && <small className="table-secondary">Lý do đảo: {row.reversalReason}</small>}</td><td><div className="row-actions">{canMutate && <Button type="button" variant="quiet" onClick={onEnd}>Kết thúc</Button>}{canMutate && <Button type="button" variant="quiet" disabled={!canChange} onClick={onChange}>Đổi giáo viên</Button>}{canMutate && <Button type="button" variant="quiet" onClick={onCorrect}>Hiệu chỉnh</Button>}</div></td></tr>;
}

function WorkflowForm(props: { workflow: Workflow; calendar: { startDate: CivilDateString; endDate: CivilDateString }; businessDate: CivilDateString; classes: Array<{ id: string; code: string; name: string }>; candidates: Teacher[]; pending: boolean; error: unknown; submitting: boolean; onRetry(): void; onChange(next: Workflow): void; onCancel(): void; onCreate(input: HomeroomAssignmentInput): void; onEnd(id: string, endDate: CivilDateString): void; onChangeTeacher(id: string, input: ChangeHomeroomTeacherInput): void; onCorrect(id: string, input: CorrectHomeroomAssignmentInput): void; setError(message: string): void }) {
  const { workflow } = props;
  if (workflow.kind === 'end') return <form className="inline-work-form homeroom-workflow" onSubmit={(event) => { event.preventDefault(); const max = workflow.row.validUntil ?? props.calendar.endDate; if (!isCivilDate(workflow.endDate) || workflow.endDate < workflow.row.validFrom || workflow.endDate > max) return props.setError(`Chọn ngày kết thúc từ ${formatCivilDate(workflow.row.validFrom)} đến ${formatCivilDate(max)}.`); props.onEnd(workflow.row.id, workflow.endDate); }}><h2>Kết thúc phân công chủ nhiệm</h2><p><strong>{workflow.row.schoolClass.name}</strong> — {workflow.row.teacher.displayName}</p><FormField label="Ngày kết thúc" name="homeroom-end-date" type="date" min={workflow.row.validFrom} max={workflow.row.validUntil ?? props.calendar.endDate} value={workflow.endDate} onChange={(event) => props.onChange({ ...workflow, endDate: event.target.value })} required /><div className="form-actions"><Button type="submit" variant="secondary" loading={props.submitting}>Xác nhận kết thúc</Button><Button type="button" variant="quiet" onClick={props.onCancel}>Hủy</Button></div></form>;
  if (workflow.kind === 'correct') return <CorrectionForm {...props} />;
  const temporal: CreateDraft | ChangeDraft = workflow; const isCreate = temporal.kind === 'create'; const bounded = isBoundedHistorical(temporal.validUntil, props.businessDate); const max = temporal.kind === 'change' ? temporal.row.validUntil ?? props.calendar.endDate : props.calendar.endDate; const min = temporal.kind === 'change' ? nextCivilDate(temporal.row.validFrom) : props.calendar.startDate;
  function submit(event: FormEvent) { event.preventDefault(); if (!isCivilDate(temporal.validFrom) || !temporal.teacherUserId) return props.setError('Chọn ngày hiệu lực và giáo viên.'); if (temporal.validFrom < min || temporal.validFrom > max || (temporal.validUntil && (!isCivilDate(temporal.validUntil) || temporal.validUntil < temporal.validFrom || temporal.validUntil > max))) return props.setError('Khoảng hiệu lực phải nằm trong phiên lịch hợp lệ.'); if (bounded && !temporal.entryReason.trim()) return props.setError('Phân công lịch sử phải nêu nguồn hoặc lý do nhập.'); if (temporal.kind === 'create') { if (!temporal.schoolClassId) return props.setError('Chọn lớp.'); props.onCreate(buildHomeroomInput({ ...temporal, validFrom: temporal.validFrom as CivilDateString })); } else props.onChangeTeacher(temporal.row.id, { newTeacherUserId: temporal.teacherUserId, effectiveFrom: temporal.validFrom as CivilDateString, ...(optionalNote(temporal.note) ? { note: optionalNote(temporal.note) } : {}), ...(optionalNote(temporal.entryReason) ? { entryReason: optionalNote(temporal.entryReason) } : {}) }); }
  const update = (patch: Partial<CreateDraft | ChangeDraft>, resetTeacher = false) => props.onChange({ ...temporal, ...patch, ...(resetTeacher ? { teacherUserId: '' } : {}) } as Workflow);
  return <form className="inline-work-form homeroom-workflow" onSubmit={submit} noValidate><h2>{isCreate ? 'Tạo phân công chủ nhiệm' : 'Đổi giáo viên chủ nhiệm'}</h2>{temporal.kind === 'change' && <p><strong>{temporal.row.schoolClass.name}</strong> — giáo viên hiện tại: {temporal.row.teacher.displayName}</p>}<div className="form-grid">{temporal.kind === 'create' && <SelectField label="Lớp" id="homeroom-create-class" value={temporal.schoolClassId} onChange={(event) => update({ schoolClassId: event.target.value }, true)} required><option value="">Chọn lớp</option>{props.classes.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</SelectField>}<CandidateFields draft={temporal} min={min} max={max} businessDate={props.businessDate} candidates={props.candidates} pending={props.pending} error={props.error} onRetry={props.onRetry} onChange={(patch, resetTeacher) => update(patch, resetTeacher)} /> <TextareaField label="Ghi chú" id="homeroom-note" maxLength={500} value={temporal.note} onChange={(event) => update({ note: event.target.value })} /></div><div className="form-actions"><Button type="submit" loading={props.submitting}>{isCreate ? 'Lưu phân công' : 'Xác nhận đổi giáo viên'}</Button><Button type="button" variant="quiet" onClick={props.onCancel}>Hủy</Button></div></form>;
}

function CandidateFields({ draft, min, max, businessDate, candidates, pending, error, onRetry, onChange }: { draft: CandidateDraft; min: CivilDateString; max: CivilDateString; businessDate: CivilDateString; candidates: Teacher[]; pending: boolean; error: unknown; onRetry(): void; onChange(patch: Partial<CandidateDraft>, resetTeacher?: boolean): void }) { const historical = isBoundedHistorical(draft.validUntil, businessDate); const datesReady = isCivilDate(draft.validFrom) && (!draft.validUntil || isCivilDate(draft.validUntil)); return <><FormField label="Có hiệu lực từ" name="homeroom-valid-from" type="date" min={min} max={max} value={draft.validFrom} onChange={(event) => onChange({ validFrom: event.target.value }, true)} required /><FormField label="Có hiệu lực đến" name="homeroom-valid-until" type="date" min={draft.validFrom || min} max={max} value={draft.validUntil} onChange={(event) => onChange({ validUntil: event.target.value }, true)} />{historical && <><FormField label="Tìm danh tính giáo viên lịch sử" name="homeroom-historical-search" value={draft.search} minLength={2} onChange={(event) => onChange({ search: event.target.value }, true)} hint="Nhập ít nhất 2 ký tự; chỉ tìm trong danh tính lịch sử được phép." /><TextareaField label="Nguồn hoặc lý do nhập lịch sử" id="homeroom-entry-reason" maxLength={2000} value={draft.entryReason} onChange={(event) => onChange({ entryReason: event.target.value })} required /></>}<SelectField label={historical ? 'Giáo viên theo danh tính lịch sử' : 'Giáo viên đủ điều kiện'} id="homeroom-teacher" value={draft.teacherUserId} disabled={!datesReady || pending || Boolean(error) || (historical && draft.search.trim().length < 2)} onChange={(event) => onChange({ teacherUserId: event.target.value })} required><option value="">{pending ? 'Đang tìm giáo viên…' : historical && draft.search.trim().length < 2 ? 'Nhập ít nhất 2 ký tự để tìm' : 'Chọn giáo viên'}</option>{candidates.map((item) => <option key={item.userId} value={item.userId}>{teacherLabel(item)}</option>)}</SelectField>{error && <QueryFailure error={error} retry={onRetry} />}{datesReady && !pending && !error && candidates.length === 0 && (!historical || draft.search.trim().length >= 2) && <p className="candidate-empty">Không có giáo viên phù hợp với điều kiện này.</p>}</>;
}

function CorrectionForm(props: Parameters<typeof WorkflowForm>[0]) { const workflow = props.workflow as CorrectDraft; const selected = workflow.replacements[workflow.selected]!; const patch = (value: Partial<ReplacementDraft>, resetTeacher = false) => { const replacements = workflow.replacements.map((item, index) => index === workflow.selected ? { ...item, ...value, ...(resetTeacher ? { teacherUserId: '' } : {}) } : item); props.onChange({ ...workflow, replacements }); }; function submit(event: FormEvent) { event.preventDefault(); if (!workflow.reason.trim()) return props.setError('Nêu lý do hiệu chỉnh.'); if (!workflow.replacements.length || workflow.replacements.length > 50) return props.setError('Cần từ 1 đến 50 bản ghi thay thế.'); const sourceStart = workflow.row.validFrom; const sourceEnd = workflow.row.validUntil ?? props.calendar.endDate; const ordered = workflow.replacements.map((item) => ({ ...item, validUntil: item.validUntil || undefined })).sort((a, b) => a.validFrom.localeCompare(b.validFrom)); for (const item of ordered) { if (!item.teacherUserId || !isCivilDate(item.validFrom) || item.validFrom < sourceStart || item.validFrom > sourceEnd || (item.validUntil && (!isCivilDate(item.validUntil) || item.validUntil < item.validFrom || item.validUntil > sourceEnd))) return props.setError('Mỗi thay thế phải có giáo viên và khoảng hiệu lực nằm trong bản ghi nguồn.'); if (isBoundedHistorical(item.validUntil ?? '', props.businessDate) && !item.entryReason.trim()) return props.setError('Mỗi thay thế lịch sử phải nêu nguồn hoặc lý do nhập.'); } for (let i = 1; i < ordered.length; i += 1) if ((ordered[i - 1]!.validUntil ?? sourceEnd) >= ordered[i]!.validFrom) return props.setError('Các khoảng thay thế không được chồng lấn; khoảng trống được phép.'); props.onCorrect(workflow.row.id, { reason: workflow.reason.trim(), replacements: ordered.map((item) => ({ teacherUserId: item.teacherUserId, validFrom: item.validFrom as CivilDateString, ...(isCivilDate(item.validUntil ?? '') ? { validUntil: item.validUntil as CivilDateString } : {}), ...(optionalNote(item.note) ? { note: optionalNote(item.note) } : {}), ...(optionalNote(item.entryReason) ? { entryReason: optionalNote(item.entryReason) } : {}) })) }); }
  return <form className="inline-work-form homeroom-workflow" onSubmit={submit} noValidate><h2>Hiệu chỉnh phân công chủ nhiệm</h2><p><strong>{workflow.row.schoolClass.name}</strong> — bản ghi nguồn sẽ được đảo và thay bằng các khoảng bạn xác nhận.</p><TextareaField label="Lý do hiệu chỉnh" id="homeroom-correction-reason" maxLength={2000} value={workflow.reason} onChange={(event) => props.onChange({ ...workflow, reason: event.target.value })} required /><div className="correction-picker"><SelectField label="Bản ghi thay thế đang chỉnh" id="homeroom-correction-selected" value={String(workflow.selected)} onChange={(event) => props.onChange({ ...workflow, selected: Number(event.target.value) })}>{workflow.replacements.map((_, index) => <option key={index} value={index}>Thay thế {index + 1}</option>)}</SelectField><Button type="button" variant="secondary" disabled={workflow.replacements.length >= 50} onClick={() => props.onChange({ ...workflow, selected: workflow.replacements.length, replacements: [...workflow.replacements, { note: '', ...blankCandidate(), validFrom: workflow.row.validFrom, validUntil: workflow.row.validUntil ?? '' }] })}>Thêm khoảng</Button><Button type="button" variant="quiet" disabled={workflow.replacements.length <= 1} onClick={() => { const replacements = workflow.replacements.filter((_, index) => index !== workflow.selected); props.onChange({ ...workflow, replacements, selected: Math.max(0, workflow.selected - 1) }); }}>Bỏ khoảng</Button></div><div className="form-grid"><CandidateFields draft={selected} min={workflow.row.validFrom} max={workflow.row.validUntil ?? props.calendar.endDate} businessDate={props.businessDate} candidates={props.candidates} pending={props.pending} error={props.error} onRetry={props.onRetry} onChange={patch} /><TextareaField label="Ghi chú" id="homeroom-correction-note" maxLength={500} value={selected.note} onChange={(event) => patch({ note: event.target.value })} /></div><div className="form-actions"><Button type="submit" loading={props.submitting}>Xác nhận hiệu chỉnh</Button><Button type="button" variant="quiet" onClick={props.onCancel}>Hủy</Button></div></form>;
}
