import type { SchoolClassRecord } from '@baogiang/contracts';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { AcademicYearWorkspace } from '../components/academic/AcademicYearWorkspace';
import { Button } from '../components/ui/button';
import { FormField } from '../components/ui/form-field';
import { DataTable, EmptyState, MutationNotice, PageLoading, Pagination, QueryFailure, SelectField, StatusText } from '../components/ui/management';
import { normalizeCode, schoolClassesApi, schoolClassPatch, type SchoolClassInput } from '../lib/academic-structure-api';

type Draft = SchoolClassInput & { id?: string; original?: SchoolClassRecord };
export function SchoolClassesPage() {
  const { academicYearId = '' } = useParams(); const client = useQueryClient(); const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [grade, setGrade] = useState(''); const [draft, setDraft] = useState<Draft>(); const [confirm, setConfirm] = useState<{ id: string; action: 'activate' | 'deactivate' }>(); const [success, setSuccess] = useState('');
  const query = useQuery({ queryKey: ['school-classes', academicYearId, page, status, grade], queryFn: () => schoolClassesApi.list(academicYearId, { page, pageSize: 20, status: status || undefined, gradeLevel: grade ? Number(grade) : undefined }) });
  const save = useMutation({ mutationFn: ({ id, input }: { id?: string; input: Partial<SchoolClassInput> }) => id ? schoolClassesApi.update(id, input) : schoolClassesApi.create(academicYearId, input as SchoolClassInput), onMutate: () => setSuccess(''), onSuccess: async () => { setDraft(undefined); setSuccess('Đã lưu lớp học.'); await client.invalidateQueries({ queryKey: ['school-classes', academicYearId] }); } });
  const action = useMutation({ mutationFn: (value: { id: string; action: 'activate' | 'deactivate' }) => schoolClassesApi.action(value.id, value.action), onSuccess: async () => { setConfirm(undefined); setSuccess('Đã cập nhật trạng thái lớp; lịch sử vẫn được giữ.'); await client.invalidateQueries({ queryKey: ['school-classes', academicYearId] }); } });
  function submit(event: FormEvent) { event.preventDefault(); if (!draft) return; const input = draft.original ? schoolClassPatch(draft, draft.original) : { code: normalizeCode(draft.code), name: draft.name.trim(), gradeLevel: draft.gradeLevel }; if (Object.keys(input).length === 0) { setDraft(undefined); return; } save.mutate({ id: draft.id, input }); }
  return <AcademicYearWorkspace academicYearId={academicYearId}><section className="workspace-section" aria-labelledby="classes-heading"><div className="section-heading"><div><p className="utility-label">Danh sách theo năm</p><h2 id="classes-heading">Lớp học</h2><p>Lọc theo khối và trạng thái; vô hiệu hóa không xóa lớp khỏi lịch sử.</p></div><Button type="button" onClick={() => setDraft({ code: '', name: '', gradeLevel: 10 })}>Tạo lớp</Button></div><MutationNotice error={save.error ?? action.error} success={success} />
    {draft && <form className="long-form" onSubmit={submit}><h3>{draft.id ? 'Chỉnh sửa lớp học' : 'Tạo lớp học'}</h3><div className="form-grid"><FormField label="Mã lớp" name="class-code" maxLength={50} value={draft.code} onChange={(e) => setDraft({ ...draft, code: e.target.value })} required /><FormField label="Tên lớp" name="class-name" maxLength={150} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} required /><SelectField label="Khối" id="class-grade" value={draft.gradeLevel} onChange={(e) => setDraft({ ...draft, gradeLevel: Number(e.target.value) as 10 | 11 | 12 })}><option value={10}>Khối 10</option><option value={11}>Khối 11</option><option value={12}>Khối 12</option></SelectField></div><div className="form-actions"><Button type="submit" loading={save.isPending}>Lưu lớp học</Button><Button type="button" variant="quiet" onClick={() => setDraft(undefined)}>Hủy</Button></div></form>}
    <div className="filter-bar"><SelectField label="Trạng thái" id="class-status" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="INACTIVE">Đã vô hiệu hóa</option></SelectField><SelectField label="Khối" id="class-grade-filter" value={grade} onChange={(e) => { setGrade(e.target.value); setPage(1); }}><option value="">Tất cả</option><option value="10">Khối 10</option><option value="11">Khối 11</option><option value="12">Khối 12</option></SelectField></div>
    {query.isPending ? <PageLoading /> : query.isError ? <QueryFailure error={query.error} retry={() => void query.refetch()} /> : query.data.items.length === 0 ? <EmptyState filtered={Boolean(status || grade)} title={status || grade ? 'Không có lớp phù hợp bộ lọc' : 'Chưa có lớp học'} message={status || grade ? 'Điều chỉnh khối hoặc trạng thái rồi thử lại.' : 'Tạo lớp đầu tiên cho năm học này.'} /> : <><DataTable label="Sổ lớp học" headings={['Mã / tên lớp', 'Khối', 'Trạng thái', 'Thao tác']}>{query.data.items.map((row) => <tr key={row.id}><td><strong>{row.name}</strong><small className="technical-value table-secondary">{row.code}</small></td><td>Khối {row.gradeLevel}</td><td><StatusText active={row.status === 'ACTIVE'} inactiveLabel="Đã vô hiệu hóa" /></td><td><div className="row-actions"><Button type="button" variant="quiet" onClick={() => setDraft({ id: row.id, code: row.code, name: row.name, gradeLevel: row.gradeLevel, original: row })}>Sửa {row.code}</Button>{confirm?.id === row.id ? <><span>Xác nhận {confirm.action === 'activate' ? 'kích hoạt' : 'vô hiệu hóa'}?</span><Button type="button" variant="secondary" loading={action.isPending} onClick={() => action.mutate(confirm)}>Xác nhận</Button><Button type="button" variant="quiet" onClick={() => setConfirm(undefined)}>Hủy</Button></> : <Button type="button" variant="quiet" onClick={() => setConfirm({ id: row.id, action: row.status === 'ACTIVE' ? 'deactivate' : 'activate' })}>{row.status === 'ACTIVE' ? 'Vô hiệu hóa' : 'Kích hoạt'}</Button>}</div></td></tr>)}</DataTable><Pagination page={query.data.page} pageSize={query.data.pageSize} total={query.data.total} onPage={setPage} /></>}
  </section></AcademicYearWorkspace>;
}
